### ISSUE TITLE
traffic flow with sumo

### ISSUE THREAD

**Issue by monasabeti** [eclipse/sumo#10034]
@namdre
hello namdre
with which option of sumo i can calculate the traffic follow that will be reach to each edge of the motorway?
 for example 1 hour befor or i don't know the time that would be reasonable that i can undrestand the traffic flow.
by fcd file we can calculate traffic that happened and reported, but i look for the option that with trip of the vehicle how can i undrestand how many cars that will we have in a specific part of the motorway?
 
i am looking forward to hearing your feedback.

---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
With a trip file, you can only guess because the route will be calculated at simulation time.
To count the traffic on each edge without running the simulation you need an input file with full routes.
The tool https://sumo.dlr.de/docs/Tools/Routes.html#countedgeusagepy is made for this type of counting.
As an approximation you can perform fastest-path-routing on your trip file and count the edges in those routes:

`duarouter -n net.net.xml -r input.trips.xml -o fastest.rou.xml`

The actual routes in the simulation may differ because they take into account congestion.
