### ISSUE TITLE
Fix the width of the internal bike lane connection in an intersection

### ISSUE THREAD

**Issue by alexpagri** [eclipse/sumo#10051]
The width of an internal lane is usually the one of the successor lane.

In some cases, if the predecessor is a bike lane and the successor is a normal lane, the width of the internal bike connection will be too large.

**Comment by namdre** [comment]
Something else to consider for high fidelity simulations: if a (narrow) bike lane connection is built between a dedicated cycling lane and a normal road lane or vice versa, it is possible to build an internal shape that is right-aligned rather than center aligned with the wider lane. The simulation takes this special case into account when handling the lateral bike position in sublane simulation for a smoother trajectory.

**Comment by alexpagri** [comment]
Thank you for pointing that out!
We already did some tests with our new implementation and the "narrower" bike lanes allow even smoother trajectories.

However, for the left turn, the connection is left-aligned, which makes a hard time for bikes to turn from the rightmost sublane to the leftmost (during the crossing of the internal left-aligned lane). But this is not related in any way to this issue, it is related to #9959 (right alignment of bikes)

**Comment by namdre** [comment]
For the matter of left turns, take a look at vType attribute 'lcTurnAlignmentDistance' (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models)

This can be used to give vehicles sufficient time for moving to the correct side of the lane.
