### ISSUE TITLE
create edgeDataStats.py

### ISSUE THREAD

**Issue by rummel123** [eclipse/sumo#10104]
Create tool for calculating statistic values as mean, standard deviation, 1. quantile, median, etc. for each edge of a list of edge data files. 
Use `sumolib.miscutils.Statistics` for the calculations.
Result should be a new edge data file with statistic values for each numerical attribute. Add appropriate prefixes to the attribute names (e.g. `std_`).
Should work with #10103.
Add tests.

**Comment by rummel123** [comment]
tests are missing

**Comment by namdre** [comment]
`attributeCompare.py` now serves as a more general tool to compute such statistics

**Comment by namdre** [comment]
edgeDataDiff and edgeDataStatistics (could be renamed to edgeDataStats for consistency) still have their use because the generic tools attributeDiff and attributeCompare  produce output that doesn't have the same format as the input. Thus their output cannot be use for further processing with edgeData-tools (plot_net_dump.py, routeSampler.py ...)
