### ISSUE TITLE
Scale Traffic algorithm is not adequate for scheduled bus flows

### ISSUE THREAD

**Issue by rjmaris** [eclipse/sumo#10126]
I obeyed that e.g. increasing Scale traffic to 1.5 or higher, buses start to depart immediately after each other.
Upon closer inspection it pointed out that every vehicle is sent on tour according to the specified interval, while upon "firing", more than one vehicle is going on tour.

This behaviour can be resolved by dividing the vehicle interval time by the scale traffic factor.
  
---
**SUMO-version:** 1.12

**operating system:** Linux

**Comment by rjmaris** [comment]
Corollary à la Murphy:
If you specify the end time of bus flows to e.g. 3000 instead of default 3600, the behaviour is as expected. No bus on the final vehicle feed on 3600 will be injected into the system. I need that to ensure that only individual traffic affects the end time of a simulation.
BUT: If Scale Traffic is set to e.g. 1.5, buses are also fired on 3600...

**Comment by namdre** [comment]
- upscaling is now equidistant
- downscaling works as before (some of the vehicles are dropped). The difference is noticeable when using scale 0.66 on 3 vehicles with period 1200. Instead of having 2 vehicles with 1800s gap, there is one at 1200 and one at 2400.
- the bug with an extra vehicle in the end step has also been fixed.

**Comment by rjmaris** [comment]
Cool!
