### ISSUE TITLE
density-velocity graph

### ISSUE THREAD

**Issue by emotion68** [eclipse/sumo#10231]
Add your issue description here.
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
![image](https://user-images.githubusercontent.com/82993708/155909414-ea3ec62c-5f94-4235-9c1b-f94fdde790a2.png)
Why does my density-velocity graph not have any pattern? Shouldn't it be a downward trend?

**Comment by namdre** [comment]
Your plot poses many more questions
- what is *p*
- what are you *really* plotting on the y-axis (surely not s/m)
- where did this data come from. SUMO isn't giving you line plots for density (only scatter-plots) but it looks a bit too smooth for a piecewise linear interpolation of a scatterplot
- how many lanes is this for?
- is this only insertion flow or a scenario with junctions etc. ? For a scenario of  insertion flow you won't see a downward trend because it doesn't fall (much) below free flow density.

**Comment by emotion68** [comment]
> Your plot poses many more questions
> 
> * what is _p_
> * what are you _really_ plotting on the y-axis (surely not s/m)
> * where did this data come from. SUMO isn't giving you line plots for density (only scatter-plots) but it looks a bit too smooth for a piecewise linear interpolation of a scatterplot
> * how many lanes is this for?
> * is this only insertion flow or a scenario with junctions etc. ? For a scenario of  insertion flow you won't see a downward trend because it doesn't fall (much) below free flow density.

![image](https://user-images.githubusercontent.com/82993708/155945561-4116f6d0-b4c4-49a3-a6de-318420528d8e.png)
two lanes
have no junction
k-q graph is also not have any pattern

**Comment by namdre** [comment]
The  k-q graph clearly shows that your scenario is running without traffic breakdown and you only see the rising branch of the fundamental diagram. As already stated, this is to be expected from a single road without obstructions (because insertion at the start of an edge introduces no reason for the flow to breakdown downstream). 
I'm sure I linked this to you already but please read again https://sumo.dlr.de/docs/Tutorials/FundamentalDiagram.html
