### ISSUE TITLE
Question on stop state of the ego

### ISSUE THREAD

**Issue by pradeeporuganti** [eclipse/sumo#10349]
I am trying to understand why the stop state returned is 0 even though the vehicle has stopped at a traffic light. Is "stop" different from "halt" ? 

Additionally, is there a way to know if the ego vehicle has stopped for a traffic light or if the vehicle has stopped at an intersection (no traffic lights) to allow vehicles with the right-of-way (waiting in the intersection to take a left turn) ? Is there a way other than using a combination of getWaitingTime() and E2 lane area detectors to get this information ?

**Comment by namdre** [comment]
1. the stopped state indicates a voluntary stop such that of a bus which takes up passengers. This is distinct from the "halting" state where the vehicle is hindered by its environment.
2. you can use `vehicle.getNextTLS` to obtain the distance to upcoming traffic lights as well as their signal state. If the list is empty or the distance is high, the halting state must be caused by something else.
