### ISSUE TITLE
Incorrect Collision Detection

### ISSUE THREAD

**Issue by zhuhj-tery** [eclipse/sumo#10367]
Hello developer,
Recently, when I did some experiments where collisions could be deliberately caused, I encountered the case where the default collision detection module failed. In my experiments, I have set the minGapFactor to be 0, which means that only the physical overlap will be regarded as a collision. As shown in the trajectory file in the attachment, there should be no crash between CAV and BV_94f89ca6, however, the collision was detected by SUMO. I tried to turn on the debug mode for collision detection and I found out that in the final time step, the position of the BV was correct, while the longitudinal position of the CAV was still the position in the previous time step, which caused the crash detection. I'm wondering if there are any problems and how to fix it?
Thank you very much.
---
*If possible, upload an example that shows your problem.*
[trajectory.zip](https://github.com/eclipse/sumo/files/8308294/trajectory.zip)

**SUMO-version:**
sumo 1.9.0
**operating system:**
Linux

**Comment by namdre** [comment]
The given data is insufficient for understanding your setup. In the `.rou.xml` the CAV departs at step 10 whereas your fcd-output runs from step 0 to 7. Also, it is unclear how the other vehicles are spawned or controlled.
I'm assuming that you are running a simulation with TraCI control.
You could provide a traci-traceFile: https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands 
Note, that the failed detection could be also due to a bug in 1.9 that has been fixed since. I recommend trying with the latest release first.

**Comment by zhuhj-tery** [comment]
Thank you for your reply.
I have tried the latest version of sumo, i.e. sumo 1.12.0, which does not work, and the collision is still detected.
I can provide you with the Traci commands as shown in the attachment. Hope the error can be reproduced.
[tracitrace.log](https://github.com/eclipse/sumo/files/8309772/tracitrace.log)

**Comment by namdre** [comment]
The problem was triggered by issuing a moveToXY command that moved the vehicle by more than 4m in 0.1s (thereby exceeding the configured maxSpeed of 40m/s)
