### ISSUE TITLE
measure Files

### ISSUE THREAD

**Issue by ibrahimallam087** [eclipse/sumo#10370]
I'm trying to make routes from observation using dfrouter and I can't understand what is measure file in the command 
dfrouter --net-file net.net.xml --routes-output routes.rou.xml --emitters-output vehicles.rou.xml --measure-files flows.txt

**Comment by namdre** [comment]
measure file: a csv file as per this example: https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html#computing_flows

Note, that I would advise against using dfrouter for most projects since it is prone to creating implausible routes. The recommended tool is routeSampler.py: https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html#chosing_the_right_tool
