### ISSUE TITLE
Converting Shapefiles (extracted from PARAMICS) to SUMO XML network file

### ISSUE THREAD

**Issue by mohammad-bgr** [eclipse/sumo#10420]
Hi,
I am trying to import a shape file (that is exported from PARAMICS) to SUMO. I have 3 file type (*.dbf; *.shp; *.shx). I am following the instruction provided in the SUMO documentation and use the following command line:

netconvert -v --shapefile-prefix links -o net.net.xml --shapefile.from-id StartNode --shapefile.to-id EndNode --shapefile.use-defaults-on-failure
after running the code a *.net.net.xml file is created, but with some warnings attached. and as I go to open the xml file in netedit, I come up with the following error:

**Error: Could not build projection!
done.
Error: No nodes loaded.
Error: Failed to build network.**

I would be very grateful if someone could help me with this matter. Thanks in advance for your time.
  
---
*Please find the attached files regarding the shapefiles and the related error*

**SUMO-version:** Nightly Snapshots: Windows installer with all extras (contains GPL code) at 14/03/2022

**operating system:** Windows 11
[New folder.zip](https://github.com/eclipse/sumo/files/8356825/New.folder.zip)

**Comment by namdre** [comment]
Your shapefile comes without a projection and due to a bug this wasn't supported.
If you download the latest development version (https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version) the following command will work:

`netconvert -v --shapefile-prefix links -o net.net.xml --shapefile.from-id StartNode --shapefile.to-id EndNode --shapefile.use-defaults-on-failure --proj !`

The option `--proj !` ensures that no attempt at projecting the data is made.

Further recommended option for you network:
`--shapefile.laneNumber Lanes --shapefile.speed Speed(mph) --speed.factor 0.44704`
The latter converts the speed from mph into m/s (as needed by sumo)

**Comment by mohammad-bgr** [comment]
Thank you so much Dr. Erdmen for your guidance. I really appreciate it. I
tried the code you shared and it worked. However, there are some warnings
in the network file, junctions and edges shapes have been imported
inappropriately. I am trying to fix these manually by editing the network
in netedit. Thanks again.
Regards
Mohammad
