### ISSUE TITLE
When the signal light is green, the vehicle does not pass.

### ISSUE THREAD

**Issue by YunhaiGong** [eclipse/sumo#10455]
Add your issue description here.
Two errors description:
SUMO has 2 errors in the simulation process, as shown in the two pictures respectively. error_1 occurs at 2000 seconds, the signal light is green, but the vehicle does not pass. Error_2 occurs at 2775 seconds, when the bicycle phase is red, there are still bicycles passing, causing the motor vehicle to wait inside the intersection to give way.
*If possible, upload an example that shows your problem.*

**SUMO-version:**
sumo 1.11.0
**operating system:**
windows
[some_errors.zip](https://github.com/eclipse/sumo/files/8391117/some_errors.zip)
 10

**Comment by namdre** [comment]
Your scenario exposes multiple bugs (#10457, #10458). However, the main problem stems from the fact that the green light for bicycles is too low for the given level of traffic.  

The cycle paths form a roundabout-like structure and this is prone to deadlock as soon as the traffic density exceeds a certain level. For normal roundabouts this is prevented by giving right of way to vehicles *in* the roundabout and making surplus traffic wait *outside*. 
However, deadlock is a real problem for traffic light controlled roundabouts and the usual solution is to balance the inflow-green-duration so that it's shorter than the throughput/outflow-green-duration.
In your scenario, the inflow green is much longer than the throughput which is leading to deadlock.

**Comment by YunhaiGong** [comment]
Is there any good way to solve the above two bugs without modifying the signal timing scheme?

**Comment by namdre** [comment]
I'll have to fix both bugs on the sumo side but even then your scenario will still be in deadlock due to the overfull-roundabout-with-traffic-light problem (This reflects reality where a badly managed roundabout will also deadlock).
If you want to avoid deadlock for the cyclists, you have to modify the timings.

You improve bicycle flow and delay the deadlock somewhat by changing the 'keepClear' attribute of all bicycle connections to false. This lets bicycles enter the intersection even when the opposite side is still jammed.  However, you will still fill up the "roundabout" unless you change the timing.

**Comment by YunhaiGong** [comment]
Ok, get it. Many thanks!

**Comment by YunhaiGong** [comment]
Is there a way to remove a vehicle stuck in a deadlock?

**Comment by namdre** [comment]
You can ignore deadlock on intersections after a configurable time by setting option **--ignore-junction-blocker TIME**
There is also option **--time-to-teleport.highways" which teleports vehicles if they are stopped on the wrong lane for too long (which is different from just being stopped in a jam).
By default it only applies to roads with a speed above 19m/s.
However, in the latest dev version you may set option
**--time-to-teleport.highways.min-speed** to make it also apply to roads with a different minimum speed.

**Comment by YunhaiGong** [comment]
Hello! In my scenario, SUMO has 2 errors in the simulation process, as shown respectively attached in file “error1” and “error2”. 
Error1: When SUMO simulates 1000 seconds, The vehicle marked by the red box on the left stops and waits inside the intersection, instead of passing through the intersection smoothly like the vehicle on the right. Can you help to see what the problem is? How should I solve this problem?
Error2: In the same SUMO model, there is another error. In the simulation time of 3000 seconds, the blue bus from the south entrance stops inside the intersection and does not pass through the intersection. How should I handle this situation?
Thanks very much!
[new_error.zip](https://github.com/eclipse/sumo/files/8405297/new_error.zip)
SUMO-version:
sumo 1.11.0
operating system:
windows

**Comment by namdre** [comment]
please comment if you still have problems. The known problems are tracked in other issues.
