### ISSUE TITLE
Don't set SUMO_HOME variable with a tilde in linux

### ISSUE THREAD

**Issue by robertalms** [eclipse/sumo#10514]
Hi guys,
by accident and with the help of @behrisch I found out that SUMO doesn't accept a tilde (~) for setting the SUMO_HOME variable (at least not my ubuntu machine +  bash).
I don't know how relevant that issue actually is for others, but I ran into problems because of that, e.g. SUMO not being able to call the xml-validation.

If you think this might concern also others,, I suggest you either specify this issue in the wiki somewhere here [(link)](https://sumo.dlr.de/docs/Basics/Basic_Computer_Skills.html#linux) or actually add this "tilde" path definition to SUMO.

Also, thx for your help yesterday @namdre .
Robert

**Comment by schwamborn** [comment]
While assigning the absolute path is probably the safe bet, I cannot confirm that using '~' is a problem on my Ubuntu (18.04) machine with bash v4.4.20(1). For example:

```
$ export SUMO_HOME=~/sumo
$ echo $SUMO_HOME
/home/schwamborn/sumo
```

More details on how bash expands the tilde symbol can be found with:
<pre>$ man bash | less -p '   Tilde Expansion'</pre>

Having said that, I'm not entirely sure how SUMO itself handles/reads the value of the environment variable. So should we consider this issue a bug on SUMO's side @behrisch @namdre?

**Comment by behrisch** [comment]
The problem is it works if you write it at definition time because the shell expands the tilde directly when setting the variable so no further interpretation is needed when SUMO reads / interprets it. So yes the question is whether SUMO itself should do it as well or if it is not worth the effort (or even breaks things). It is a little bit more involved than regular environment variable because in my (very few) tests it only works a the beginning of a path and there are things like `~user` expanding to `/home/user`. It is definitely not high priority, I just encouraged Robert to open a ticket to gather opinions

**Comment by namdre** [comment]
at least this is something to add to the FAQ

**Comment by namdre** [comment]
Also, we could detect a `~` in path input and raise a Warning.

**Comment by behrisch** [comment]
I think the easy case of a path starting with `~/` should just be fixed and the rest ignored.

**Comment by behrisch** [comment]
The initial use case which had something like `SUMO_HOME=~/sumo` is probably not covered because this would need mulitple substitution rounds when being used in a config. But at least some support for using ~ is now there. Everything else needs a new ticket
