### ISSUE TITLE
traci.vehicle.getLanePosition giving inconsistent values

### ISSUE THREAD

**Issue by arpan-kusari** [eclipse/sumo#10543]
I am trying to get the longitudinal position of two vehicles along a lane and get the distance between them. The code I use is essentially:

`long_dist = traci.vehicle.getLanePosition(lead_vehicle) - traci.vehicle.getLanePosition(follow_vehicle)`

where `lead_vehicle` and `follow_vehicle` are the vehicle ids. Now the problem I am facing is that the distance is correct for some interval [-78, ... , -50] and then it switches to ~-4300 which seems like the lane position the other way round (instead of del_d, it is length of lane - del_d). 
I am not sure why it is switching and what could be done to make it consistent. 

**SUMO-version:**1.10.0

**operating system:**Microsoft Windows 10 Enterprise

**Comment by m-kro** [comment]
The lane position is given in [m] from the lane begin, so a leader vehicle should always return a higher value than its follower **as long they are on the same lane**. According to your equation, it should be a positive value then. 
Some things to check:
- follower won't overtake / cannot because it's a one lane carriageway
- distance is calculated only when both vehicles are on the same edge 
In case you can confirm this, feel free to attach a minimal working example to this issue.

**Comment by namdre** [comment]
Almost certainly, the abrupt change in distance occurs once the lead vehicle enters a new edge. To obtain the distance to the leader regardless of it's edge, use function `traci.vehicle.getLeader`
