### ISSUE TITLE
route2OD throws an error: 'list' object has no attribute 'push_back'

### ISSUE THREAD

**Issue by hagerradi** [eclipse/sumo#10586]
Was tools/route/route2OD.py tested? When using it, it throws this error: AttributeError: 'list' object has no attribute 'push_back'. I believe it should be "append" rather than a "push_back" for ambiguousSource and ambiguousSink lists. 

Is there any alternative for generating the OD matrix from the route file?

**SUMO-version:**
Eclipse SUMO sumo Version 1.12.0

**operating system:**
 Build features: Linux-4.15.0-167-generic x86_64 GNU 9.3.0 Release Proj GUI SWIG GDAL GL2PS
 Copyright (C) 2001-2022 German Aerospace Center (DLR) and others; https://sumo.dlr.de

**Comment by namdre** [comment]
> Was tools/route/route2OD.py tested?

Yes. Just not for the code path of edges appearing in multiple TAZ

> Is there any alternative for generating the OD matrix from the route file?

No. But it should work if you replace your old version of the tool with this: https://github.com/eclipse/sumo/blob/main/tools/route/route2OD.py  (or simply replace `push_back` by `append`)

**Comment by hagerradi** [comment]
I did replace push_back by append, I then tried to convert the OD to trips using OD2trips but I get broken routes for many vehicles. Can you advise how should the OD matrix be converted back to route/trips/flow so i can run it in simulation?

**Comment by namdre** [comment]
It depends on why the routes are broken:
- if it's due to different vClasses in use, you'll have to define vClass-specifiz TAZ and OD matrices
- if it's due to a disconnected network you have to redesign the TAZ so that the following property holds: "if there is traffic from TAZ *A* to  TAZ *B*, then each edge from *A* must admit a route to each edge of *B*". 

Alternatively you can filter out broken routes with the help of `duarouter --write-trips --ignore-errors` but this will lead to reduced traffic.

**Comment by hagerradi** [comment]
I believe it is due to the second reason:
```
Warning: No connection between edge '-653473569#5' and edge '201956811#0' found.
Warning: No route for vehicle '63' found.
Error: Vehicle '63' has no valid route.
Quitting (on error).
```

What is the best way to generate/design the TAZ if i only have the network file? I have tried to use [toolsgenerateBidiDisctricts.py](https://sumo.dlr.de/docs/Tools/District.html#generatebididistrictspy) and [tools/district/gridDistricts.py](https://github.com/eclipse/sumo/blob/main/tools/district/gridDistricts.py) but both appear to cause disconnected networks.

**Comment by namdre** [comment]
There is currently no tool that could automatically ensure the connectivty-property discussed above. 
It might help to pre-process your network with netconvert option **--keep-edges.components 1** to ensure there are no trivially disconnected parts.
You could also try a combination of manually fixing connectivity with netedit or removing badly connected source/sink edges from the TAZ. 

> I have tried to use toolsgenerateBidiDisctricts.py and tools/district/gridDistricts.py

since both tools have completely different goals, it don't quite see what you are trying to achieve with your processing chain "routes-> odmatrix -> trips"

**Comment by hagerradi** [comment]
With my processing chain, i had a network file, and a route file and i was trying to generate the OD matrix because i need to alter the traffic domain in different ways. My approach relied heavily on having the OD matrix, so i was trying to move from route->OD->apply changes->trips.

I think the main reason why this is failing is that generating the TAZ doesn't keep the edges in their correct orders. In other words, i can see trips using a very outer edge (going out of the network/ has no successor) as a source node. In this case, there is no way such a trip will be correct.

**Comment by namdre** [comment]
a potential solution for your problem is outline here: https://github.com/eclipse/sumo/issues/10618
