### ISSUE TITLE
Insert new flows to the saved state

### ISSUE THREAD

**Issue by wxinl** [eclipse/sumo#10619]
Is there a way to combine new flows and a save state and see how the new flows perform (in terms of travel time or speed etc)?

**Comment by namdre** [comment]
Yes. You can load additional or modified route-files along with a state file.

**Comment by wxinl** [comment]
I used the additional route file (starts at 10800 seconds) as input for route files in sumo.cfg and loaded a previous state (saved at 10800 seconds). But it gave an error of "Error: vector". Could you tell me what problem might cause that?

**Comment by wxinl** [comment]
I uploaded the attached zip file. Thank you!
[Archive.zip](https://github.com/eclipse/sumo/files/8617991/Archive.zip)

**Comment by namdre** [comment]
The attached archive does not contain a state file and the .sumocfg does not attempt to load one. Thus, I am unable to reproduce your problem. Can you send the missing files/options?
However, the `Error: vector` might be caused by using different sumo versions for saving and loading the state file: We do not guarantee compatibility of state files across sumo versions.

**Comment by behrisch** [comment]
Feel free to add another comment if you have more information
