### ISSUE TITLE
invalid memory re-use with departPos="random_free"

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#10647]
The Netedit CheckOutputTest demandelements/flow_junctions/inspect/selection/departpos/random_free generates different errors in Windows and Linux (See daily test)

```
< Error: Vehicle 'flowA.40' will not be able to depart using the given velocity (slow lane ahead)!
< Error: Vehicle 'flowA.90' will not be able to depart using the given velocity (slow lane ahead)!
< Error: Vehicle 'flowA.92' will not be able to depart using the given velocity (slow lane ahead)!
---
> Error: Vehicle 'flowA.57' will not be able to depart using the given velocity (slow lane ahead)!
> Error: Vehicle 'flowA.97' will not be able to depart using the given velocity (slow lane ahead)!
```

**Comment by namdre** [comment]
random_free performs multiple insertion attempts and the following sequence triggers the bug:
- first attempt in step t fails 
  - vehicle at adress X is schedule for deletion because it is assumed that this insertion will never succeed
- second attempt in step t succeeds (address is still kept as to-be-descheduled
- in step t2, another vehicle is assigned to address X, it is descheduled without warning
