### ISSUE TITLE
color mismatch "yellow minor" between phase tracker and trafficlight editor

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10651]
netedit shows dark yellow for minor and the phase tracker shows bright

**Comment by namdre** [comment]
I think this is somewhat intentional:
- the simulation treats both kinds of yellow indetically (see MSLink::haveYellow)
- netconvert always uses yellow-minor
- sumo-gui has been showing this as normal (bright) yellow since forever
- by default the minor-color is darker than the major color
- netedit want's to make sure that people notice the difference

Proposal: Let netedit show yellow-minor as yellow (like sumo-gui) and change the collor of yellow-major to a brighter shade (255,255,128)

**Comment by behrisch** [comment]
disabling yellow-major in the netedit dialog seems a good idea
