### ISSUE TITLE
sumo crashes unexpectedly 

### ISSUE THREAD

**Issue by muaid-ahmed** [eclipse/sumo#10706]
I am using cloud computing server for running the SUMO simulation. The simulation crashes during the training session within the first episode (run 1). I get the following error code.

'''
Ssumo: ./src/microsim/output/MSE2Collector.cpp:828: virtual bool MSE2Collector::notifyEnter(SUMOTrafficObject&, MSMoveReminder::Notification, const MSLane*): Assertion `myLanes[vi->second->currentOffsetIndex] == enteredLane->getID()' failed.
Traceback (most recent call last):
File "/home/muaidahmed/Network_non_dqna.py", line 24, in <module>
class SimulationRunInput:
File "/home/muaidahmed/Network_non_dqna.py", line 35, in SimulationRunInput
traci.simulationStep()
File "/usr/share/sumo/tools/traci/main.py", line 228, in simulationStep
return _connections[""].simulationStep(step)
File "/usr/share/sumo/tools/traci/connection.py", line 319, in simulationStep
result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
File "/usr/share/sumo/tools/traci/connection.py", line 181, in _sendCmd
return self._sendExact()
File "/usr/share/sumo/tools/traci/connection.py", line 91, in _sendExact
raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO
'''

SUMO-version: 1.12.0**

operating system: Ubuntu 22.04 LTS**

I kindly appreciate your help.

**Comment by namdre** [comment]
Please add option `traceFile` to your traci.start call (https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands) and provide the recorded traceFile along with all simulation input files.

I don't think the triggered assertion isn't critical so you should be able to complete your simulations by using the "release" build of sumo instead of the "debug"-build. (This is generally recommended due to achieving much higher simulation speed).

**Comment by muaid-ahmed** [comment]
Please find the log file "trace.log" and the simulation input files. 
 
[trace.log](https://github.com/eclipse/sumo/files/8675891/trace.log)
[simulation file.zip](https://github.com/eclipse/sumo/files/8675902/simulation.file.zip)

**Comment by namdre** [comment]
Some observations:
- it seems that your traci code does nothing but step through the simulation, it should therefore be possible to send just the simulation files without the log in order to reproduce the crash
- if you run your scenario with option --random, then I cannot reproduce it (every run will be different).  To obtain a reproducible crash I suggest the following: Please run your scenario on a range of different random seeds (option **--seed INT**) and provide a seed that shows the crash

Some more observations about your scenario:
- you have lots of collisions because the the sublanes are exactly as wide as your motorcycles. This is numerically quite unstable because each motorcycle is sometimes considered to overlap into the neighboring sublane even though driving in the center. I recommend changing the motorcycle width to something smaller (i.e. 0.7) or using wider sublanes (since there should be some lateral gap between adjacent motorcycles anyway).

**Comment by muaid-ahmed** [comment]
noted. thanks for the input and observation. somehow the issue is no more occuring after I updated the software

**Comment by namdre** [comment]
somehow the comment from @muaid-ahmed was missing:

> noted. thanks for the input and observation. somehow the issue is no more occuring after I updated the software

**Comment by muaid-ahmed** [comment]
noted. thanks for the input and observation. somehow the issue is no more occuring after I updated the software. 

> somehow the comment from @muaid-ahmed was missing:
> 
> > noted. thanks for the input and observation. somehow the issue is no more occuring after I updated the software
