### ISSUE TITLE
collisions on short lane with depart speed max

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10761]
```
Warning: Teleporting vehicle 'f_0.74'; collision with vehicle 'f_0.82', lane='25290438_3', gap=-0.69, time=192.00 stage=move.
Warning: Vehicle 'f_0.74' ends teleporting on edge '315425129#0', time=194.00.
Warning: Teleporting vehicle 'f_0.128'; collision with vehicle 'f_0.135', lane='25290438_2', gap=-0.02, time=354.00 stage=move.
Warning: Vehicle 'f_0.128' ends teleporting on edge '315425129#0', time=358.00.
Warning: Teleporting vehicle 'f_0.328'; collision with vehicle 'f_0.348', lane='25290438_3', gap=-2.18, time=877.00 stage=move.
Warning: Vehicle 'f_0.328' ends teleporting on edge '23208748#0', time=888.00.

```
Shows up in the test sumo\lc_model\bugs\ticket10512 if I increase the end time of the flow to 1000

**Comment by namdre** [comment]
the solution to #10512 is causing partial emergency braking (decel 7-8) because the early stopping required by the lcmodel isn't taken into account at insertion.
If vehicles are inserted at low speed without slack, they cannot compensate for this kind of braking because collision already happens in the next step.

**Comment by namdre** [comment]
part of the problem is that the speed advice from lane changing is only followed in the next step and this delay forces stronger braking. Could also be improved via #3665
