### ISSUE TITLE
How can I change the mode of queuing behaviour of drivers?

### ISSUE THREAD

**Issue by lightly-lyx** [eclipse/sumo#10813]
when one of the movement in the downstream segment has spill over, how the vehicles in the upstream behave? will they enter the available lanes in the next segment or waiting in the upstream intersection. 

*If possible, upload an example that shows your problem.*

**SUMO-version:**1.8

**operating system:**Python

**Comment by namdre** [comment]
The behavior depends on the "strategic" evaluation of the downstream lanes. If all lanes are equally useful for continuing the route, then cars will chose other lanes.
Otherwise they will queue upstream.
The thresholds for this strategic evaluation can be configured with the `lcStrategic'  vType-parameter
