### ISSUE TITLE
Side Collision Detection

### ISSUE THREAD

**Issue by RahelehSh** [eclipse/sumo#10977]
Hello,

When I simulate my osm network, I see that vehicles in parallel or opposite lanes are very close together and are stuck in that situation(I don't want to teleport them). It seems good to report this situation as a collision and handle them. Is there any other way to handle these situations?

for example:
![Capture](https://user-images.githubusercontent.com/94211436/174464873-90e00683-aadd-480f-aa8e-0e554eac2a5f.PNG)

**SUMO-version: SUMO-1.13.0**

**operating system: Windows 10**

**Comment by namdre** [comment]
Visually, the cars have not collided so this should not be reported as a collision. They are stuck due to their choice of routes. In the real-world, traffic authorities would likely prohibit the turn-around connections at these intersections and they might even prohibit turning left onto the western southbound edge. 
Alternatively, if there is much traffic from east to south, that western junction might be included into the traffic control scheme.
