### ISSUE TITLE
"getInternal" does not return all internal lanes.

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#11016]
"getInternal" does not return all internal lanes.

###################################
net = sumolib.net.readNet(
            'sumo.net.xml',
            withPrograms = True,
            withConnections = True,
            withFoes = True,
            withInternal = True
        )

node_id = 't0'
internal_edge_list = net.getNode(node_id).getInternal()

print(':t0_4_0' in internal_edge_list) # False
print(':t0_20_0' in internal_edge_list) # True
###################################

![image](https://user-images.githubusercontent.com/101240964/175195729-ccd570a5-57e7-40fa-981a-075c62e38e73.png)

**SUMO-version: 1.13.0
**operating system: window10
[sumo.net.zip](https://github.com/eclipse/sumo/files/8963183/sumo.net.zip)

**Comment by namdre** [comment]
This is by design. The `getInternal` function exposes a junction attribute from the `.net.xml` file directly. This attribute only holds an incomplete list and sumo derives the remaining elements as needed with internal code.
If you need the complete list of all internal edges for nodeID, you can retrieve all edges and check for the following property  

```
node = net.getNode("C")
for edge in net.getEdges():
    if edge.getFromNode() == node and edge.getToNode() == node:
        print(edge.getID())
```

**Comment by JamesPsh** [comment]
@namdre 

thank you!
That was what I wanted.
