### ISSUE TITLE
fcd-output filtering using loaded shapes

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#11055]
I would like to filter fcd-output for only vehicles that are "on top of" a E3 detector. My use case is to compare simulation trajectories to those recorded via a camera & radar in the same network. This is very similar to `--fcd-output.filter-edges`, which I am currently using. Being able to record just trajectories on top of E3 detectors would allow me to skip post-processing filtering of edge position and lane #. I would hope that it would be applicable to the broader community as well.

**Comment by behrisch** [comment]
The problem here is that "on top of E3" is not always well defined because there may be vehicles which start inside the area but will not get detected because they did not cross an entry. But if you are fine with that I think it boils down to switching on the fcd device whenever you cross an entry and switching it off when you cross an exit.

**Comment by namdre** [comment]
Not quite as simple: E3 detector-areas may overlap so you need to keep a stack of passed entries and only disable the device after clearing the stack.

**Comment by namdre** [comment]
As an alternative: might it be more convenient to define a filter in terms of loaded shapes? This would also provide an easy way for users to filter lanes and positions?

**Comment by namdre** [comment]
utils/geom/PositionVector provides the methods `around` and `overlapsWith` that might be suitable for this purpose. Checking the front and back vehicle positions for being within the shape (with `around`) should be the most efficient approach.

A new option **--fcd-output.filter-shapes**  that sets a list of shape ids (already loaded from additional files) might be appropriate.

**Comment by mschrader15** [comment]
@namdre before I proceed with test cases (outside of my own local tests) can you see if https://github.com/UnivOfAlabama-BittleResearchGroup/sumo/commit/f608426e7823247dcba8f6d734b877baaf897c3b is inline with what you were thinking?

Could be made more efficient by testing the polygon the vehicle was most recently in first instead of a simple loop, but I didn't want to add new variables to the vehicle class to track.

**Comment by namdre** [comment]
Basically, looks good.

- I would store the shapes by value rather than by pointer (since they might be deleted via TraCI)
- I would move the `dynamic_cast` int `shapeFilter` because the calling code doesn't make it obvious that a casting failure will be handled.
- If efficiency becomes a problem (with many loaded shapes) the proper technical solution is an RTree. However, I wouldn't worry about this as long as there is no practical need for filtering with a lot of shapes.
- Please also add a test case (-:
