### ISSUE TITLE
make tls switches accessible with keys in gaming mode

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#11056]

**Comment by namdre** [comment]
already possible even without gaming mode. See https://github.com/eclipse/sumo/blob/0d5036f1aa205e1bc6fcfa8ff694cdee54a8fe75/src/guisim/Command_Hotkey_InductionLoop.cpp#L47

It should only take a tiny piece of xml code configuration to turn the detector activation into a phase switch.

Yet, we may still want easier hotkeys (possible based on params in the `<tlLogic>` definition)
Also, since we added single-key hotkeys 'a', 's', 'd' ,`<space>` in version 1.13.0 we need to decided whether to disable them in gaming mode or possible to override them.

**Comment by behrisch** [comment]
we decided that deactivation of hotkeys in gaming mode is the best option

**Comment by namdre** [comment]
> we decided that deactivation of hotkeys in gaming mode is the best option

only single-letter hotkeys

**Comment by behrisch** [comment]
deactivation is not implemented yet

**Comment by namdre** [comment]
see also #11070
