### ISSUE TITLE
How to make the connection between different edges smooth?

### ISSUE THREAD

**Issue by hesuieins** [eclipse/sumo#11094]
Hi all,

I tried to build the model through osmWebWizard. When I corrected the built model in netedit, I found some connections between two edges are not smooth. Do you have any ideas how to make the connections smooth? Or if there exists any command that can join two edges into one? Thanks!
![image](https://user-images.githubusercontent.com/56532686/176792653-35770602-676b-43d7-9cb2-b271e53d0ff4.png)

**Comment by namdre** [comment]
The jump typically occurs if the edges have different values for their `spreadType` attribute (*center* vs *right*).
If setting them to the same value stll shows "jumps* (or you do not want to change the spreadType because doing so creates additional jumps) then continue reading here:
https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#specifying_the_complete_geometry_of_an_edge_including_endpoints
