### ISSUE TITLE
how to calibrate each lane capacity?

### ISSUE THREAD

**Issue by LilyLove0810** [eclipse/sumo#11188]
I know that the road capacity can be modified by changing the car following related parameters and speed limit, but this is a global change. In practice, the headway of different roads is heterogeneous and needs to be modified according to the road level. But the speed limit should not be changed, it is not in line with reality.Whether the interface can be opened to adjust the capacity in the future？

**Comment by namdre** [comment]
- in the micro model you can use type-calibrators to modify car following parameters upon entering a specific edge:  https://sumo.dlr.de/docs/Simulation/Calibrator.html#calibrating_vehicle_types
- in the meso model, you can set the capacity parameters for each road type: https://sumo.dlr.de/docs/Simulation/Meso.html#configuration_by_edge_type

Note, that the spatial headway changes automatically depending on road speed because the car following models typically configure a time-headway. 

If you could point out a publication / dataset that shows how the time headway changes consistently with road level that would be very helpful to furthering SUMO!
