### ISSUE TITLE
Missing vehicle type settings when using all vehicle types

### ISSUE THREAD

**Issue by simplaplatooner** [eclipse/sumo#11219]
Dear all,

I implemented a Bus Route in Dresden, Germany, where the buses are platooning when coming close enough to each other. For this I am using "Simpla". The Platooning itself is working, but as soon as I add normal passenger vehicles to the simulation and they interfere or block the buses during platooning, an error occurs and the simulation stops. Does anyone know about this and can help me solve the problem?
[Platooning_Buses.zip](https://github.com/eclipse/sumo/files/9131380/Platooning_Buses.zip)

Attached you find a zip-file.
If the file "pedestrian.rou.xml" is included in the sumocfg-file, the simulation ends at 98.50 simulation time. If you do not use pedestrians and vehicles, the simulation is running through.

**SUMO-version: 1.14**

**operating system: Windows 10**

**Comment by m-kro** [comment]
It happens because

1. you didn't restrict simpla to vehicles to certain type(s) by setting the `<vehicleSelectors value="<substring(s) of wanted vehicle types>"/>`
2. simpla does not check **yet** whether there are vehicle type mappings for all vehicle types which should be controlled

**Comment by m-kro** [comment]
@simplaplatooner Thank you for providing the example config. That really helps us checking and improving the code base. I noticed some more problems when running your simulation for long which will be documented in a separate issues.

If you want to try out quickly, you can download the current simpla files here from github. Otherwise they will be included in the developer version of SUMO of tomorrow.

**Comment by behrisch** [comment]
Looks fixed to me?

**Comment by m-kro** [comment]
Right
