### ISSUE TITLE
Unrealistic queue at intersection approach by LC speed request 

### ISSUE THREAD

**Issue by warm2018** [eclipse/sumo#11211]
Hello, I simulate an intersection traffic scenario and many vehicles are “locked”, the queue is not real I think. 
I want to know the specific reasons for this phenomenon, can anyone help me? 
Thanks in advance !
 Just like the below picture illustrated, all vehicles stopped, and two unrealistic longer gaps appeared.
**1) Why gap1 appear?**
       I guess that it is because the veh1 has a speedGain left LC motivation, and it let veh2 slow down to open the gap, is that right?
**2) Why gap2 appear?**
    I guess that the veh3 has urgency left LC motivation and it let veh4 slow down to open the gap, is that right?
Note that: veh1 has a straight turn; veh2,veh3, and veh4 have a left turn direction.![figure](https://user-images.githubusercontent.com/35907049/179240831-7a369476-c11f-4ea3-ba46-add59ae76794.jpg)

**Comment by namdre** [comment]
- yes: veh4 is keeping the gap open for veh3 and veh2
- veh2 urgently wants to change to the left lane and has decided not to overtake any further vehicles
- veh1 cannot change into the gap because it would violate the minGap of veh2

From the screenshot I'd guess that veh2 and veh3 entered the simulation on a lane that is too far right. In dense traffic the vehicles would move to their required lane sooner if there was any possibility of doing so further upstream. It might help to make the inbound edge longer to give the vehicles more time/space to move to the correct lane.

**Comment by warm2018** [comment]
Thank you !
But I think the gap2 is unrealistic in this scenario, because :
 1) the left blocking vehicle veh4 has no obligation to keep the gap for veh2 and veh3 in this scenario, because the veh2 and 
     veh3 are stopped . 
More general,  If I am the driver of veh4, I will response the speed adjustment only if the blocked veh3 and ve2 is moving, just for safety reason. But if the blokcked vehicle is stopped, the safety concern is eliminated, and I don't think I should slow down to keep the gap open.

**Comment by warm2018** [comment]
Thank you :)
But I think the gap2 is unrealistic in this scenario : 
  1) The left blocking vehicle veh4 has no obligation to keep the gap for veh2 and veh3 in this scenario, because the veh2 andveh3 are stopped .
   2) More general, if I am the driver of veh4, I will response the speed adjustment only if the blocked veh3 and ve2 is moving, just for safety reason. But if the blokcked vehicles are stopped, the safety concern is eliminated, and I don't think I should slow down to keep the gap open. Instead, I will continue approach my leader on my lane.

**Comment by namdre** [comment]
I agree that your driving behavior is a suitable reaction to this situation. 
However, the drivers in SUMO are configured to be highly cooperative by default.  
Basically, veh2 and veh3 are stuck in their placed and cannot continue until someone lets them in (or there are no more cars coming from upstream on the leftmost lane).  Arguably, their current behavior is closer to the system optimum because veh2 and veh3 are blocking the flow on their lane for all cars that want to go straight.

You can dial down the cooperation by setting vType attribute `lcCooperative` or `lcCooperativeSpeed` to something below their default of *1*.

**Comment by warm2018** [comment]
Yes, the SUMO driver is hihly cooperatetive, and the drivers always want to help others :). 
But in realistic life, most of drivers is less cooperative except that the traffic rules/laws forced them to do this. 
And I don't think the system optimum is necessary for the driver's concern.
And I think the cooperative desireness is related to my benefit or loss after my action:
    1) if my action will make me in danger (safety loss,speed loss, of course, safety is first), sorry, I don't want to cooperate
    2) instead, if my action has benefit(speed gain or safety gain), ok, I will cooperate.
So, a variable related to driving safety and speed benefits was introduced to determine the degree of cooperation in LC model, and I think this will result in more realistic vehicle behavior（may be exsit）

**Comment by namdre** [comment]
as mentioned above, this variable exists: `lcCooperative`

**Comment by warm2018** [comment]
Ok, thank you, sir, I find the details in documentation.
But something still confused me:
**In Step t:**  The veh1 and veh3 are blocked by their left blocking leaders because both of them decided not to overtake any further vehicles. 
 **In Step t + 1:** the  light change to green,  but the surrounding vehicles (their blocking vehicles and leaders) are still stopped and have no position change, but the veh3 suddenly move to its leader veh1.
 why the veh3 suddenly obtain the speed?  
![image](https://user-images.githubusercontent.com/35907049/179385459-9b3dca60-7353-40bb-b050-433da8f873cf.png)

**Comment by namdre** [comment]
The decision process takes into account the traffic density on the current and target lane. This density is different in the two situations shown. I'd guess that the change was enough to push veh3 over a behavioral threshold whereas the difference in behavior between veh1 and veh3 is due to veh1 being further downstream (which gives less distance to conduct the lane change).

**Comment by warm2018** [comment]
Thank for your guidance:)
You mean the veh3's ovetaking decision(decide whether to overtake the leader ) is related to downstream density?
I read the source code but I can't find the decision logic.
As far as I know, the downstream density is only related to the urgency strategic lane (remaining using distance to change lane).
Can you help me locate the overtaking decision logic which related  downstream density? Thank you in advance.

**Comment by namdre** [comment]
check for usage of `neighLeftPlace` and `usableDist` (https://github.com/eclipse/sumo/blob/9f2f3224cc7d3bcf1c3c693cf89d310c28499ab6/src/microsim/lcmodels/MSLCM_LC2013.cpp#L1299-L1302)

These determine whether the need for a strategic change is triggered (which eventually triggers the call to `informLeader` or not). Within the decision logic for merging before or after a leader, density is not used.

However, within `informLeader` there is a dependency on vehicle speed in the preceding steps via `myLookaheadSpeed` and `remainingSeconds` which might also be responsible for a change in behavior over time.
