### ISSUE TITLE
Creating a ring road 

### ISSUE THREAD

**Issue by Anishkulkarni9001** [eclipse/sumo#11229]
Hey, I had a question - how do I create a simple ring road? I managed to create a polygon with the grid and some online tutorials, but is there a simple way to define a perfect circular road? 

**SUMO-version:** 1.14.0

**operating system:** macOS Monterey

**Comment by m-kro** [comment]
All roads in SUMO consist of sequences of straight elements. So a ring road can only be approximated by short straight stretches. In order to define such an approximate ring road, you have to decide on a radius and calculate the intermediate geometry points.

You can transfer the geometry to SUMO possibly by either

- passing it in our [PlainXML format ](https://sumo.dlr.de/docs/Networks/PlainXML.html)using two edges (one for each half of the circle) and nodes to netconvert
- create the two edges in netedit, checking the diameter length and then set the shape attribute to the respective geometry points (using the same syntax as for the [PlainXML](https://sumo.dlr.de/docs/Networks/PlainXML.html#edge_descriptions) for the geometry)

**Comment by Anishkulkarni9001** [comment]
Sorry, but could you explain what you mean by 'intermediate geometry points'? I don't fully understand what I'm calculating - once I have my circle radius, do I need a certain length or midpoint or what?

**Comment by m-kro** [comment]
You want a geometry point every _n_ degrees. The closer you want to get to a perfect circle, the smaller _n_ has to be.
 Some random search result for the circle equation and how to calculate points on the circle is [here](https://www.bbc.co.uk/bitesize/guides/zqjqsrd/revision/1). Please refer to your favorite standard math resources if you need more help in this respect, as this is nothing SUMO-specific.

**Comment by behrisch** [comment]
you can also start with a spider network generated by `netgenerate --spider --spider.omit-center --spider.circle-number 1` which accepts `--spider.arm-number 10` to set the number of arms to 10
