### ISSUE TITLE
plot_net_trafficLights.py

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11248]
I tried to use the plot_net_trafficLights.py script on the site "https://sumo.dlr.de/docs/Tools/Visualization.html" to show the points where the Traffic Lights are. but I get the following warning,

The names of the files are shown in the screenshots below, I would be very grateful if you could tell me the code I need to write to cmd.

![F64E027B-F6A8-493F-AD6F-CF914007595B](https://user-images.githubusercontent.com/82845085/180647326-7e833818-19a5-4d78-b099-e8a59e4b1335.jpeg)

![7D699ABE-C8A4-4F09-88DF-69AD377D1884](https://user-images.githubusercontent.com/82845085/180646971-51037498-3b2b-48fb-9c75-7e66182c8721.jpeg)

![FF3A3A02-ADD6-4AB3-93D7-3C0A7EEF04F5](https://user-images.githubusercontent.com/82845085/180647271-80082da6-441e-4085-a4c3-3d21c5900d56.jpeg)

**Comment by m-kro** [comment]
You get this error because there isn't any net file called ""bs.net.xml" in your directory. The call in the docs is an example and as such references our Braunschweig network (find more about [ready scenarios](https://sumo.dlr.de/docs/Data/Scenarios.html) in our docs). I think you want to excute the script with your own network - then call it with `-n osm.net.xml`.

As a side note: When working with file names and file paths, it might be preferable to let the Windows Explorer [show the full file name ](https://www.howtogeek.com/205086/beginner-how-to-make-windows-show-file-extensions/)and not hide the extension.

**Comment by erev-84** [comment]
Hello @m-kro,

First of all thank you very much.

As seen in the screenshots below, the Plots are not full size. what is the reason for this? and what do I need to do to fix this problem?

![97A50947-4D08-4730-878F-BCE65A122E6D](https://user-images.githubusercontent.com/82845085/180871304-eb8b694a-464d-46c3-a744-0c8000b68e73.jpeg)

![DE619F79-3181-4E25-B4D4-87C15AA53253](https://user-images.githubusercontent.com/82845085/180871310-a9250f2f-28e9-4b7f-8229-7f271716b2ea.jpeg)

**Comment by m-kro** [comment]
You define the x and y ranges yourself with the `--xlim xmin,xmax` and `--ylim ymin,ymax` parameters. Call `python plot_net_speeds.py --help` to get an overview of the available parameters or read [here ](https://sumo.dlr.de/docs/Tools/Visualization.html#common_options)in our docs.
