### ISSUE TITLE
The next step vehicle speed is not equal to traci.vehicle.setSpeed(vehicle, speed)

### ISSUE THREAD

**Issue by zhubing1996** [eclipse/sumo#11249]
hello:
Add your issue description here. I want to control the speed of the vehicle in the next step through traci.setSpeed, but The next step vehicle speed is not equal to traci.vehicle.setSpeed(vehicle, speed) both at low speed, medium speed or high speed. Figure 1 is a Python file; Figure 2 is the rou.xml file; Figure 3 is the output at low speed; Figure 4 is the output at medium speed; Figure 5 is the output at high speed. I tried decel = 3 or 10, sigma = 0 or 0.5, tau = 0.5, 0.6 or 0.7 in the rou.xml file, but not solve the problem. Or does the built-in CACC model in SUMO affect setSpeed?  What's the solution?  Or something I didn't take into account? 
*
Figure1
![image](https://user-images.githubusercontent.com/89522717/180694845-17a9aca0-2419-4413-b50c-970a9ab57cc0.png)
Figure2
![image](https://user-images.githubusercontent.com/89522717/180694854-2a7bfc0e-b04c-461b-b5bf-9efa8a420565.png)
Figure3
![image](https://user-images.githubusercontent.com/89522717/180696616-cb6f0ab0-aec1-4050-b08b-1abd96919257.png)
Figure4
![image](https://user-images.githubusercontent.com/89522717/180696644-a92a3b5e-6dbe-45ae-8c32-78a1a6792053.png)
Figure5
![image](https://user-images.githubusercontent.com/89522717/180696668-f142e03f-56d5-4a42-a796-3a2c5d3264a4.png)

**SUMO-version:**1.14.1, 1.13and 1.10 all tested

**operating system:**win10

**Comment by m-kro** [comment]
Did you alter the [speed mode](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3), too? If not, there may be situations where SUMO considers your speed as unsafe and ignores it. In order to study your problem better, you could also attach a minimum working example here. Instead of providing your script, you can record the TraCI calls (see [docs](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands)).

**Comment by behrisch** [comment]
closing for lack of feedback, please add a comment if you need more help
