### ISSUE TITLE
Blurred Satellite Background

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11254]
Hello,

I added the Satellite Background to the simulation with the tileGet script, but as can be seen in the screenshot below, the resolution and the quality of the background are very bad. What is the reason for this and what should I do to get a better quality background?

![D55C743F-A4E6-4C10-B8AC-6620B15E6A31](https://user-images.githubusercontent.com/82845085/180964831-cc0d3462-4e75-4bdb-b33a-c10a1a7ae85f.jpeg)

Another problem is, as can be seen in the screenshot below, the satallite backgorund does not appear in some areas. What is the reason for this? and what do I need to do to fix this problem?

![BB96C05E-66AD-4AD1-AB6B-0EA0EDE063CA](https://user-images.githubusercontent.com/82845085/180964943-c651dee4-a54d-41e3-b38d-59170f1a5ff9.jpeg)

Thanks in advance

**Comment by m-kro** [comment]
The script queries external image providers like ArcGIS (default provider). Other supported providers are GoogleMaps and MapQuest. They probably don't deliver the same image quality / scale all over the world, so that is all you can get.

Regarding the second image: You have loaded some polygons (see [docs](https://sumo.dlr.de/docs/Simulation/Shapes.html)). The background image is just drawn behind it. Either remove the polygons entirely or define (semi-transparent) styles in the [gui settings](https://sumo.dlr.de/docs/sumo-gui.html#changing_the_appearancevisualisation_of_the_simulation).

**Comment by behrisch** [comment]
You can also try to fiddle with the layer attribute of the polygons and/or the image.

**Comment by erev-84** [comment]
Hello @behrisch @m-kro ,

The screenshot below is taken from Apple Map's app and as you can observe, resolution of the satellite image is better than the ArGıs. Is it possible to get satellite images from Apple Maps? if so how can I do that?

Apple Map ==>

![image](https://user-images.githubusercontent.com/82845085/186166296-3793db7c-6bde-4cb9-a793-0612bc1c80fe.png)

ArcGIS satellite image with -t 1000 ==>

![image](https://user-images.githubusercontent.com/82845085/186166406-614c5788-caf4-4d4b-a6cf-2d0c3193c33e.png)
