### ISSUE TITLE
why traci.busstop.getpersoncount(stopid) can not recognise persons waiting at the stop(person defined between startpos and endpos)

### ISSUE THREAD

**Issue by Ljiaooo** [eclipse/sumo#11267]
i wanna know how the traci api function getpersoncount identify the person number at the bus stop, by person's waiting stage or something else? after i add a person at the bus stop with waiting stage, i can't get the person count  at the stop with this function, and this function can't identify awaiting stage(not depart) either

**Comment by m-kro** [comment]
Please upload a minimal working example of your problem for further examination.

**Comment by Ljiaooo** [comment]
here is the test file
[Test.zip](https://github.com/eclipse/sumo/files/9233191/Test.zip)

**Comment by m-kro** [comment]
In order to make it work, you have to add an explicit walking stage to the pt stop like this after adding the person:
`traci.person.appendWalkingStage("testPerson", ['593486825#3'], 155.0, stopID='47_0')`
The position can remain the same as before, but then the person will actually enter the pt stop and person count will be 1.

**Comment by Ljiaooo** [comment]
it works! thaks a lot. One more question please, when I use traci.gui.track() to track a vehicle in sumo-gui, is there any way to stop tracking with traci?

**Comment by m-kro** [comment]
There is but it was not documented until now. Sorry for that. You have to call `traci.gui.track("")` to stop tracking.

_Please create new issues for question unrelated to the current issue next time!_
