### ISSUE TITLE
queuing problem on the highway

### ISSUE THREAD

**Issue by MarMar-s** [eclipse/sumo#11283]
Hello,
I am trying to simulate a highway in SUMO but there is a problem in the exit ramp. I want vehicles to queue in two lanes to exit the ramp (like in real life) and for this I gave access to the ramp from both lanes but the queue in both lanes does not grow at the same time and sometimes there is a gap in the middle of the second lane. I also changed the lane change parameters but I did not get better results. I tried to do the simulation with the IDM and EIDM car following model but the result is almost the same. I would be grateful if you could help me solve this problem. I have also attached a video that shows the problem.

https://user-images.githubusercontent.com/102868910/182841233-50e45b5d-9dc1-41c2-b86f-128dde1d195f.mp4

**Comment by m-kro** [comment]
Your issue relates mostly to the lane changing model in SUMO (see [docs ](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models)for settings), not much to the car-following model. The vehicles queuing on the second-rightmost lane actually want to change to the right and stop somewhere along the off ramp because there is no gap. The more strategic lane change is weighted (parameter lcStrategic), the more upstream this should happen.

Some options you can try (I can't promise they help because not tested them for this case):
- alter lane changing model parameters, especially lcStrategic (caution: applies to all vehicles of a vehicle type in the network, not only those at the off ramp)
- add a small two lane stretch at the diverging point then merge to one lane using `zipper` junction type
- use [waypoints ](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#waypoints) for a share of the vehicles leaving the highway.

**Comment by MarMar-s** [comment]
Thank you very much for your quick response.

**Comment by namdre** [comment]
It may already suffice to set the off-ramp junction to 'zipper' type since you already added the extra connection there.
