### ISSUE TITLE
How to force a vehicle not to change lanes within a certain range of an intersection

### ISSUE THREAD

**Issue by SuirongYi** [eclipse/sumo#11304]
Hello, I want the vehicle to not change lanes when it is about to enter the intersection within a certain range. Referring to https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models, I modified parameters such as lcStrategic in the rou file, but the vehicle still changed lanes. So I would like to ask you how I can achieve this function through the Traci method or modify the parameters in the rou file. 
Thank you for your help!

**Comment by namdre** [comment]
You can configure lane change restrictions on the infrastructure level by using lane attributes 'changeLeft' and 'changeright' (https://sumo.dlr.de/docs/Networks/PlainXML.html#lane-specific_definitions) tough it may be necessary to split an edge to in order to set the correct restriction range.

via TraCI you can prohibit changing using `traci.vehicle.setLaneChangeMode` but would need to set this dynamically based on the distance to the intersection.
