### ISSUE TITLE
EIDM: apply startupDelay after stopping

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11374]
currently doesn't happen because startupDelay is triggered by waitingTime which (for good reason) doesn't get incremented while stopping.

**Comment by behrisch** [comment]
our common gut feeling was that the difference is the "surprise effect" which does not apply to planned stops, so startupDelay does not apply here

**Comment by Domsall** [comment]
I understand where you are coming from. Nevertheless, the EIDM needs some kind of "DriveOff"-recognition for its internal ActionStep calculation and slowToStartTerm. With the new StartupDelay I changed the recognition to rely on myTimeSinceStartup.

Could myTimeSinceStartup still be reset? Not to 0 then, but rather to myStartupDelay (+DELTA_T)?!
I think that should do the trick.

**Comment by namdre** [comment]
@Domsall 
- can you confirm that it currently makes a difference whether the car is stopped with attribute 'parking' or not?
- Can you point to an existing test that shows the problem or provide a simple test that highlights the faulty behavior?

**Comment by Domsall** [comment]
The test of #11361 shows this bug. Everytime the vehicle stops and starts driving again, the internal ActionStep and slowToStart gets ignored (the vehicle starts driving immediately). When ActionStep reaches 0 again, slowToStart takes effect.
The test is probably a bit misleading, because of the "double stop".

**Comment by Domsall** [comment]
thanks!!!
