### ISSUE TITLE
Randomtrips.py

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11401]
Hello,

Is there a way to determine the probability of vehicles that will pass through the road marked with the arrows by using randomtrips.py. In other words, I want more vehicles to pass through the arrow marked road/path than other roads, and can I do this with the randomtrips.py script?

![image](https://user-images.githubusercontent.com/82845085/186138003-5cf2d22c-41ca-47e0-a719-4ea929544cf9.png)

If something like this is possible, could you please show me an example to see how I could do it?

Thanks

**Comment by erev-84** [comment]
Hello @m-kro ,

Could you please explain in more detail how I can create a generic edge parameter and show me an example?  Also, Do I need to create an xml file Which include edge parameters named PARA  and call it with —random-trips.py --edge-param PARAM?  I'm so sorry, but I don't qet the point well and I would be glad if you can Show me an example.

Thanks in advance

**Comment by m-kro** [comment]
There was a dead link on one of the doc pages I linked (has been corrected). Here is [some explanation](https://sumo.dlr.de/docs/Netedit/editModesCommon.html#generic_parameters) how to edit the paramater in netedit. You don't need additional files because the data is stored inside the net file.
That's how it looks like in netedit:
![grafik](https://user-images.githubusercontent.com/33294728/186147071-506d2f50-8e70-40eb-9ee9-4ba0977741ca.png)
Inspect an edge, click "Edit parameters" and enter a key-value pair in the table which appears. You can choose how to name it (PARAM or other!), but have to reference the key in the randomTrips call like explained above.
Repeat for other edges of the network (you can select more edges to do it all in once).

**Comment by erev-84** [comment]
@m-kro 

It's worked, thank you very much
