### ISSUE TITLE
setting 'show domes around TLS models' takes no effect

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11434]
apologies if this is a duplicate and I missed it.

**Comment by m-kro** [comment]
Probably a problem of semantics.

- The option refers to the bubbles/domes created for the signals positioned via decals settings and is there (see e.g. tools/game/bs3Dosm.sumocfg). 
- Then there are the "link marker" bubbles which can be switched on/off by another setting. As their name indicates, they are positioned above the stop lines
- I added the automatically generated 3D signals which are positioned with some offset and ped signals across the road like in reality. There are no bubbles added currently because it would change little to the option before (just some position offset). But I might look again whether OSG has better features regarding light effects.

**Comment by namdre** [comment]
Some sort of high-visibility coloring for the auto-generated signals that looks more realistic that the bubble markers would be nice. 

If that proves to be too hard, we need at least add some description to the 'show domes' checkbox to indicate that it doesn't apply to auto-generated signals.
