### ISSUE TITLE
SUMO

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11566]
①Are there driverless vehicle of  in SUMO？
②The last time we asked about the same intersection, different types and sizes of vehicles in the same direction have the same turning trajectory，How do I prove it?
**SUMO-version:**

**Comment by behrisch** [comment]
1. yes if you consider the car following model equivalent to a controller essentially every vehicle is driverless by default since perception errors need to be modeled explicitly in SUMO.
2. (without the sublane model) every vehicle follows the same centerline of the internal lane. So in a sense the trajectories are always identical although the observed points may differ due to time discretization and different speeds.
