### ISSUE TITLE
Vehicle Context Subscription is broken

### ISSUE THREAD

**Issue by DFazekas** [eclipse/sumo#11597]
I'm trying to capture all vehicles that are within a range to the _reference vehicle_, then halting them until the _reference vehicle_ passes and they're out of range.
![image](https://user-images.githubusercontent.com/22490250/190224405-a6869b26-ca79-4f5c-b35a-3c9c2482b435.png)

The **context subscription** feature seems the best option for achieving this behaviour, as it captures all vehicles on "neighbor and ego-lanes". However, it appears to break in two situations:
1. when the _reference vehicle_ is between lanes, such as during lane changing or with `lateral resolution` set equal to 1.
2. when vehicles get "too close" to the _reference vehicle_.

As you can see in the screen recording, at simulation time 15-seconds, the context subscription captures all nearby vehicles perfectly (IDs 5, 7, 8, 9, and 10). But the very next second, it no longer captures the two closest vehicles (IDs 9 and 10). From there on, it falls apart.
https://user-images.githubusercontent.com/22490250/190234187-e6b0035a-4a7c-4359-97b9-d8f19fd35841.mp4

The source code is available here: https://gist.github.com/DFazekas/cfc606ef966b75aa6d25717f4526523c

I presume this bug is in relation to another issue: https://github.com/eclipse/sumo/issues/11540#issue-1362647326

**SUMO-version:**
Version v1_14_1+1008-de138fee043

**operating system:**
Windows 10

**Comment by namdre** [comment]
Here is what happens:
- the bluelight device has it's own code to change the behavior of surrounding vehicles
- this is accomplished by overriding some of the vType attributes of those vehicles
- to avoid changing the behavior of other vehicles in the simulation, the affected vehicles are assigned a new type (i.e. from `Civilian` to `Civilian@10` where `10` is the id of an affected vehicle
- this makes the subscriptionFilter based on vTypes reject these vehicles

Proposed solution: use a vClass filter instead of a vType filter
