### ISSUE TITLE
Jumping vehicles during/after lane change

### ISSUE THREAD

**Issue by repa1030** [eclipse/sumo#11719]
Hello,

I am facing problems with Sumo especially during lane change to avoid stopped vehicles. I provided the Sumo project and a short video of the problem. In some cases the vehicles even jump into the stopped vehicle (not captured on the video). To reproduce the situation, just start the Sumo simulation and force one vehicle to stop. 

Thank you for any help!

*If possible, upload an example that shows your problem.*
[sumo_circuit.zip](https://github.com/eclipse/sumo/files/9662737/sumo_circuit.zip)

**SUMO-version: 1.12.0**

**operating system: Windows 11**

**Comment by m-kro** [comment]
Was able to repoduce it. Happens also with SUMO 1.11 and current dev version. A simplified scenario for debug purpose is available at S:\Bugreports\11719 (jump at t=100.240).

**Comment by namdre** [comment]
The problem is purely visual and somewhat related to #11643 
The different lanes of the edge are treated as if they had the same length and also as if all cross-sections along their length had the same offset along their geometry (which is obviously not the case on curves).
In the given network the effect of multiple curves "adds up" so that the move between lanes (without changing the driven distance/offset) corresponds to a different point when measured along the geometrical length of the lane.

This is not fixable with the current architecture. The best workaround is to split the edge into multiple edges to avoid the additive affect of multiple curves.

**Comment by repa1030** [comment]
When I use the workaround with the netconvert options I get back the problems from #6867 as shown in the attached video.
I recognized --geometry.max-segment-length 200 --geometry.split converts all geometry points to edges (see attached net file).
How can I avoid this?
[Flickering.zip](https://github.com/eclipse/sumo/files/9672222/Flickering.zip)

**Comment by namdre** [comment]
Ah yes. I didn't consider of the dense geometry in the curves. 
The only thing I can think of is to start with the original long-edge network and adding a few intermediate junctions manually in netedit by using function 'split edge here' .  It's best to add them in sections with low curvature.  This should give the best compromise between flickering on many small junctions and jumping on long curved edges.
