### ISSUE TITLE
vehroute file includes person-trips unable to be carried out

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#11730]
When a person cannot make his/her ride, a warning ".... aborted waiting for .... " will be recorded in the simulation log file. His/her trip will be saved in the output file vehroute. 

Currently, such trips can be found out only if --vehroute-output.exit-times is on. In this case, such trip can be reconized by checking if the attributes "started" and "ended" exist and/or if their values are -1. 

So, some questions are raised:

1. Should such trips still be included in a vehroute file?
2. If so, 
    - is a warning for such trip needed?
    - is a new attribute needed for identifying such trip? 
3.  if not, how to deal with it?
4. Should the respetive reason for "aborting to wait..." also be provided in the simulation log file?

**Comment by yunpangfloetteroed** [comment]
- yes, every arrived person/vehicle has the arrival attribute in my case.
- No, no vehroutes.write-unfinished was set.

**Comment by yunpangfloetteroed** [comment]
Currently, if exit-time is not set and aborting occurs, ride's routeLength = -1. But the route length of the following walk will still be indicated. It can also be set to -1 for consistency and this implies that this trip is not finished.

**Comment by behrisch** [comment]
Unfinished persons should not be there, so there is still a bug. routeLength also needs to be enabled explicitly so this is not a good solution either

**Comment by namdre** [comment]
In my mind, the "philosophy" of vehroute output is not to indicate whether routes /trips were finished but rather to give as much information as possible (i.e. if the simulation ends early, the full route of the vehicle is still printed rather than being cut off).

However, I realized that for unfinished vehicles, the 'routeLength' attribute also gives the length that was actually driven rather than the full length. Thus it is inconsistent to provide the full length for walks. 

With regard to unfinished persons:
Currently all stages are written when the person is erased. Would you instead prefer to have unfinished stages excluded from the output (unless write-unfinished is set) or even exclude the whole person if it has at least one unfinished stage?

**Comment by behrisch** [comment]
I think the person should be left out completely. Maybe we can have another suboption "unfinished-partly" which writes only the part of the route / plan which actually has been traveled.

**Comment by yunpangfloetteroed** [comment]
Actually, it is nice/efficient to have all in one file, since they are all trips, but with different transport means. By the way, perhaps the name triproute is more representative than vehroute afterwards?  

The option vehroutes.write-unfinished exists. So, it is normal to expect that there are only completed trips (vehicles, persons) in the vehroute file if this option is set to false. 

Unfinished-partly is a nice idea. Then, an attribute would be needed to help to know which trip is incompleted.  Otherwise, incompleted trips will look like completed trips. 

Intuitively, I would prefer to have one new attribute for trip status: something like 0 (incompleted) or 1 (completed), especially for the file including unfinished trips.

**Comment by yunpangfloetteroed** [comment]
Without the options --vehroute-output.exit-times and --vehroute-output.route-length unfinished trips cannot be identifed in the file. Is it intended? So, users should find out it from log. right?

**Comment by namdre** [comment]
yes. Though unfinished trips are no longer included by default now.

**Comment by yunpangfloetteroed** [comment]
ok, I have already added some explanations about this part in doc
