### ISSUE TITLE
Drawing of SUMO intersection

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11818]
What drawing software (such as VISIO) can be used to make the drawing of SUMO intersection and vehicles? Because there is an arc buffer at the turning point of SUMO intersection, I have a question. Do you know whether SUMO has a drawing template control or what drawing software supports SUMO?
![微信图片_20221012202807](https://user-images.githubusercontent.com/54823725/195342628-3c45b6eb-cf64-40e3-a823-0a142cac28ca.jpg)

**SUMO-version:**

**Comment by m-kro** [comment]
I am not sure what you ask for... The appearance of SUMO networks can be changed through a set of [GUI settings](https://sumo.dlr.de/docs/sumo-gui.html#changing_the_appearancevisualisation_of_the_simulation) (which can be also be ex/imported to be reused). This mainly concerns colours and item sizes.

The geometry is either computed internally by netconvert or given by the user in netedit. If you want to have more geometry points at the turning, there is the netconvert option **--junctions.corner-detail INT** (give a number instead of INT).

**Comment by namdre** [comment]
right click on a junction and select "Set custom junction shape" if you want to draw the shape manually in netedit.
