### ISSUE TITLE
Let cars choose 2 lanes with a given ratio

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [eclipse/sumo#11851]
Hello, this is my model. In my model 2-lane Edge connects to 3-lane Edge.
![image](https://user-images.githubusercontent.com/82990411/196317846-d1d1be58-3def-4ec8-b098-6834e72043db.png)
According to the instructions, I changed the type of junction to zipper and  lcStrategic="0.5" lcKeepRight="0.5".
But vehicles often choose the rightmost lane, there are no vehicles in the middle lane.
![image](https://user-images.githubusercontent.com/82990411/196318584-eeeb03f2-ef42-4acd-bc93-af31a7ee2474.png)
So is there any way to let vehicles choose 2 lanes with a given ratio?
Thanks and best regards
*If possible, upload an example that shows your problem.*
**SUMO-version:** 1.14.1
**operating system:** windows

**Comment by TrinhTuanHung2021** [comment]
![image](https://user-images.githubusercontent.com/82990411/196373051-ae804ba7-274e-412b-9e5b-f92df21000e1.png)
And I do not know why the length of cars changed at the stop line

**Comment by m-kro** [comment]
**Please don't mix completely unconnected topics in the same issue!** Regarding the first one:

- See similar question #8725 : make use of flow attributes departlane and arrivalLane
- Afterwards, it depends on how your actual network looks like in comparison to the shown dummy one: lane change parameters may become useful for longer stretches and bigger speed differences between neighbour vehicles

Regarding the second topic: Usually this is due to a custom edge length greater than the computed one. Then the vehicles are scaled accordingly to the custom edge length. Remove the custom edge length value in Netedit if this is the case.
