### ISSUE TITLE
invalid lateral rendering postion of vehicles with (potential) carriages

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#11901]
- Shultte and pedestrian are in the middle of the shared space, but on different edges (shuttle: 116295294; pedestrian: -116295294).

- There is no braking and no position changing when they are approching to each other. 

- And, they cross each other as they cannot see each other. 

- There is no sumo warning.

*If possible, upload an example that shows your problem.*
The scenario was provided.

**SUMO-version:**
v1_14_1+1872-d955e9abd09
**operating system:**
Windows

**Comment by yunpangfloetteroed** [comment]
This ticket is different from Ticket #11483 . In #11483, it seems that the pedestrian runs to the bike due to the limited free space. In this ticket, the pedetrian has enough space and time to avoid the shuttle. But he/she does not do it.  The shuttle has the setting lcStrategic="-1". So he will not make any strategic lane changing.

**Comment by namdre** [comment]
the shuttle is configured with guiShape=rail. When rendering with high vehicle detail (simple shapes) this causes the railway-carriage rendering code to be used and so far this code ignores lateral positioning because trains generally do not move laterally within their track bed.
A simple work-around is to disable carriage rendering by adding this to the vType: `<param key="carriageLength" value="0"/>`.
With #11919 fixed, this gives the same look as the original rail carriage rendering.

**Comment by namdre** [comment]
the problem also applies to non-rail shapes such as `truck/trailer`

**Comment by yunpangfloetteroed** [comment]
I added carriageLength ="0" under the vType for the shuttle, which uses the IDM model.  The problem still exists. Could it be that the parameter carriageLength is ignored when this shuttle is defined as vehicle, although it guiShape is set to a rail?

**Comment by yunpangfloetteroed** [comment]
it works after rebuliding sumo!
