### ISSUE TITLE
Why do vehicles jam when using CACC as car-following model？

### ISSUE THREAD

**Issue by Zhaoyou-Lu** [eclipse/sumo#11946]
I wanted to use CACC to simulate CAV, but the traffic became a jam. The lane-changing model I used is SL2015. When I used the IDM model, this phenomenon was gone.
[example.zip](https://github.com/eclipse/sumo/files/9918837/example.zip)

**SUMO-version:**
1.14.1
**operating system:**
win 11
![image](https://user-images.githubusercontent.com/79387513/199446677-a26117e2-e08d-491b-bf34-9e176d4dd0aa.png)

**Comment by robertalms** [comment]
Hello there. The traffic jam in your scenario apparently derives from the insufficient utilization of all lanes ahead of the intersection since you use the sublane model SL2015. Note, that the ACC/CACC models are not fully tested in combination with the sublane model. When I tested your scenario using the standard LC2013 model, this phenomenon seems to dissipate. 

Also note, that the ACC/CACC models are developed for lower step-lengths of 0.1seconds, which you should be aware of in terms of speed and gap behaviour. (see Wiki : [ACC](https://sumo.dlr.de/docs/Car-Following-Models/ACC.html) + [CACC](https://sumo.dlr.de/docs/Car-Following-Models/CACC.html))

**Comment by Zhaoyou-Lu** [comment]
Thanks for your clear answer. I will conduct a further test.
