### ISSUE TITLE
vehicle setColor has wrong doc

### ISSUE THREAD

**Issue by LilyLove0810** [eclipse/sumo#11943]
I find a wrong documentation in https://sumo.dlr.de/pydoc/traci._vehicle.html, the function like setColor(self, typeID, color)
[setColor](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setColor), the doc means Sets the color of this vehicle type,but actually set the color of a certain car,so I suggest changing the variable name to VehID.

**Comment by m-kro** [comment]
The vehicle part of the Python TraCI interface is in fact derived from the vehicle type part. That's why the automatically generated documentation takes the function signature from the vehicle type. IMO it seems a bit over the top to overwrite the function just for the mater of a parameter name.

**Comment by namdre** [comment]
I don't like `objectID` as the general name either because a vType isn't really an object (I'd reserve talk of objects to vehicles and persons) and I also don't think overriding a method just to have the vType methods use `typeID` and the derived methods use `objectID` is worth it (in terms of extra code for the already difficult-to-read macros).

Furthermore, people have been known to actually call methods with named parameters so 'consistency' gain here must be balanced with the risk of breaking other peoples code.  

The simplest fix could be to extend the pydoc so it clearly describes the semantics of the parameter name depending on it's usage context.

**Comment by behrisch** [comment]
I didn't mean overriding just changing the name everywhere. But yes adapting the docstring is less intrusive. There also seems to be some inconsistencies already at least with the `get*Lat` functions which name the parameter vehID
