### ISSUE TITLE
OSM ID changed after convertion

### ISSUE THREAD

**Issue by curtis18** [eclipse/sumo#11947]
After converting an osm file to any other format, it is found that some OSM IDs are changed with additional numbers.

e.g. OSM link id 85320819 becomes 85320819#0, 85320819#1, 85320819#2 as in the image below.

Is there any option to merge them to become a single link with id 85320819 which is the same as the OSM id? Thank you.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/6743839/199477699-4768dfbc-9422-482b-8c38-cbd7f266c104.png">

**Comment by namdre** [comment]
Generally, this is not possible because the edge ids in sumo must be unique between "real" intersections (so there are not enough `way` ids in the OSM database).
See https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html#relationship_between_osm_ids_and_sumo-ids for more details.

If you use the recommended options for importing (**--geometry.remove**) some of those extra edges will be merged and you can always use param origID to retrieve the original way id.
