### ISSUE TITLE
About modifying param using netconvert.

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#11958]
hello.

I am going to use netconvert to modify only the edge params.

~~~
netconvert -s sumo1.net.xml -e for_update.edg.xml -o sumo2.net.xml
~~~

The format of "for_update.edg.xml" is as follows.
I only add param.
~~~
<?xml version="1.0" encoding="EUC-KR"?>
<edges>

    <edge id="edge1">
        <param key="key1" value="value1"/>
        <param key="key2" value="value2"/>
    </edge>
   
   [other edges]

</edges>
~~~

I wonder if other parts of the network other than param will not change.
The reason I have this question is because "sumo1.net.xml" and "sumo2.net.xml" are sometimes different when creating a network as shown below.

~~~
netconvert -s sumo1.net.xml -p sumo2
netconvert -n sumo2.nod.xml -e sumo2.edg.xml ...(etc) -o sumo2.net.xml
~~~

**SUMO-version:** 1.14.1

**operating system:** windows10

**Comment by namdre** [comment]
If the .net.xml came directly from an external import (i.e. OSM) than you may see slight geometry changes due to numerical precision effects. The inputs (OSM data comes with lon,lat data at a spatial precision ~1mm whereas the default precision of .net.xml is 1cm.  However, this should generally not lead to relevant simulation differences. (you may also increase the precision of .net.xml geometries by setting option **--precision 3**).

**Comment by JamesPsh** [comment]
Similar question.

Even if I read the network with netedit and save it with [save network as] without making modifications, some shapes of the two networks are not the same.

Is there any way to solve this?

**Comment by namdre** [comment]
Can you attach a minimal network example (zip the .net.xml) and an description of how to replicate the unrelated-parts-changed behavior?
