### ISSUE TITLE
Turning signal and lane change direction

### ISSUE THREAD

**Issue by hesuieins** [eclipse/sumo#11956]
When I run the simulation, I found that a vehicle changes to the right lane with left turning is on. Based on its lateral position, it seems like it tries to change to the left lane, but if failed. Would this be a bug or is there any reason for this abnormal maneuver?
![image](https://user-images.githubusercontent.com/56532686/200075999-4ea2dfdf-6319-450c-a07f-b73962e664e2.png)
(left turning signal is on but it goes to right)

**Comment by namdre** [comment]
please provide minimal example files to replicate this behavior (zip archive with .sumocfg and all files referenced therein).

**Comment by hesuieins** [comment]
[SUMO Abnormal Behaviour.zip](https://github.com/eclipse/sumo/files/9946792/SUMO.Abnormal.Behaviour.zip)
I upload a zip file here. It has SUMO config relevant files and a fcd output. The abnormal behavior is for vehicle with id `flo2.8` beginning at simulation time 535 seconds.

**Comment by namdre** [comment]
![Bildschirmfoto von 2022-11-07 08-07-49](https://user-images.githubusercontent.com/6240630/200246360-1e454fa6-86df-4271-ac9f-7cff51658690.png)

According to the connection layout at that junction, the car can only continue on the rightmost lane (but no lateral change of lane takes place). The lane change to left does indeed fail and whether this is due to a bug warrants further investigation.

**Comment by namdre** [comment]
note to self: relevant situation is between t=[550, 560]

**Comment by namdre** [comment]
scenario shows #12283 but this will be tracked as a distinct issue.
