### ISSUE TITLE
plot_tripinfo_distributions: Add a note to axis ticks if the minimum/maximum values have been adapted

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#11973]
The script allows for a minimum and a maximum value which replace all data below/above these thresholds. Currently, it can not be understood from the generated histogram whether the first/last bin actually includes values below/above the actual tick value.

Maybe a custom tick note could be added reading "<=" or ">=".

**Comment by namdre** [comment]
I'm considering to fold the functionality into the more general `plotXMLAttribute.py` (or even into `plotXMLAttributes.py`) and retire the specialized script (or to keep it as a thin wrapper around the general tool).

**Comment by namdre** [comment]
I propose to retire `plot_tripinfo_distributions` to purgatory since it is no longer needed.

old:  `plot_tripinfo_distributions.py -i tripinfos.xml,tripinfos2.xml -m timeLoss --bins 20 --maxV 300` 
![old](https://user-images.githubusercontent.com/6240630/218734771-7bcfe239-d4fa-4ce4-98d7-6ab77d3bff6b.png)


new: `plotXMLAttributes.py tripinfos.xml tripinfos2.xml -x timeLoss -y @COUNT -i @NONE -s --legend  --barplot --xbin 20 --xclamp :300`
![new](https://user-images.githubusercontent.com/6240630/218734422-4d92cb52-a9b4-4894-96c0-e0a28f167078.png)

**Comment by namdre** [comment]
note, that the difference in the bars is due to rounding down rather than towards the bin center.

**Comment by m-kro** [comment]
Can be closed...
