### ISSUE TITLE
LC2013 lane change model for a freeway merging area

### ISSUE THREAD

**Issue by 2847662024** [eclipse/sumo#12120]
Add your issue description here.
I want to simulate a highway merge zone scenario with SUMO. However, I found that under the default lane change model LC2013 cars are only blocking the middle lane, while the innermost lane remains unobstructed. The cars in the middle lane did not seem to have any desire to change lanes to the inside, even though this would allow them to gain speed. I have tried adjusting the parameters of LC2013 but to no good effect, what can I do to solve this problem.
![image](https://user-images.githubusercontent.com/34417999/203319235-e581c621-62f6-4a99-bdd5-1ec23e7a9e42.png)

Translated with www.DeepL.com/Translator (free version)
*If possible, upload an example that shows your problem.*
[新建文件夹.zip](https://github.com/eclipse/sumo/files/10067508/default.zip)

**SUMO-version:**
1.14.1
**operating system:**
windows 11

**Comment by m-kro** [comment]
I do not get how you would like the merging to work. The vehicle density is high on both the on-ramp and the motorway which leads to congestion on the right through lane. Vehicles intend to change to the left lane but cannot due to the difference in speed given the small gap. Not sure whether adapting [lane change model parameters ](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models) would help given this vehicle density...

**Comment by 2847662024** [comment]
Thank you for your reply, my intention was to go ahead and simulate the congestion in the merge zone of the highway. Would adjusting the traffic density help improve this phenomenon?

**Comment by m-kro** [comment]
You can try to reduce the traffic density and lift the parameters regarding cooperative dribing (lcCooperative, lcCooperativeSpeed).

**Comment by namdre** [comment]
As you can see on the plot, the inner lane (red) has occasional break-downs in speed. The main reason why the jam doesn't often spill over onto the inner lane is that vehicles can no longer change into a lane that has high density *and* much higher speed.

The main thing is to have some heterogeneity in the traffic (occasional gaps). With your model parameters only 75% of the vehicles are even inserted and the rest is discarded due to being above capacity and the traffic is at it's maximum density.

If you configure some of the drivers to be agressive (lcAssertive > 1) you will see more lane changes into the inner lane.

![Bildschirmfoto von 2022-11-22 15-06-01](https://user-images.githubusercontent.com/6240630/203334790-ced47afa-f7a7-4dda-b53a-0290428b93d8.png)

**Comment by 2847662024** [comment]
Sorry for taking so long to reply, and thank you for the valuable advice. I tried various traffic demands as well as speed limits of roads. The lower traffic demand and speed limit as well as giving random time intervals when vehicles are generated really helped alleviate this. But does this mean that it is difficult to simulate congestion like the one in the figure below under high traffic demand, e.g. 1800veh/h/lane, and higher road speed limit, e.g. 27.78m/s. Again, I apologize for the delay in responding and look forward to your precious suggestions!
![image](https://user-images.githubusercontent.com/34417999/203891985-c52983e4-4ebf-495b-bc5d-06b520fb5e96.png)

**Comment by namdre** [comment]
some observations w.r.t. https://traffic-simulation.de/ vs your simulation
- setting the slider to 5400 doesn't give you 1800veh/h/lane.  With the listed settings,  even if you turn ramp flow to 0
   - slowly ramping up traffic on the inflow from 0 to 5400 will give you at most 4000 veh/h actual flow (1333 veh/ lane /h)
   - if you don't ramp up the flow it's easy to have the main flow stuck in a jam-on-insertion state (corresponding to what you can get with departSpeed="max" in sumo) this drops the actual flow to 850 v/h/l. If you want to avoid this in sumo, use departSpeed="last" or departSpeed="avg". See https://sumo.dlr.de/docs/Simulation/RoadCapacity.html

- the drivers in that sim are quite aggressive. They don't mind changing lanes with high speed differences and consequently forcing high decelerations after lane changing. If you want to see such things in sumo, than setting `lcAssertive` (and maybe ignoring collisions) is what you need to do.  Also setting a lower step length would help to avoid some collisions by lowering the effective reaction time

**Comment by 2847662024** [comment]
I appreciate your thoughtful response, and I learnt a lot. I'll experiment more in SUMO.
