### ISSUE TITLE
junction tls removed when joining junction and tls.discard-simple true

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#12163]
tls.discard-simple false

<img width="627" alt="image" src="https://user-images.githubusercontent.com/48930860/204028180-42c4e6e9-6157-4282-8e36-b13056c5a20b.png">

tls.discard-simple true -> completely removes all tls

<img width="627" alt="image" src="https://user-images.githubusercontent.com/48930860/204027478-df6dadcc-7c19-4ea2-83ed-391b3ffc523e.png">

[files](https://drive.google.com/drive/folders/1nnPI6ldA5i_29R_CBMcGotQuUv0gaT5w?usp=share_link)

**SUMO-version:** latest

**operating system:** win

**Comment by namdre** [comment]
![raw](https://user-images.githubusercontent.com/6240630/204103212-c0fce6e0-9fe6-4891-8e55-200fe296af13.png)

Looking at the raw osm data I think this intersection is beyond the scope of the current heuristics:
- tls.guess-signals only works if all entries to a junction have a signal. Here it fails because the eastern entry to the western junction has no signal (presumably the control is joined with the eastern junction)
- when not interpreting the individual signals at the western junction with **--gls.guess-signals** they are removed as intended.

Also, the case with **--tls.discard-simple** is wrong because there really is no signal at the eastern entry to the western junction (going by google street view). This would have to be modeled by setting the connections to 'uncontrolled' or at least by putting an always-green signal there.
(The rule that this case was based on was: if you join junctions and any of them have a traffic light, then the cluster shall get a traffic light).

If you can up with
- a) a simple, yet general rule that would handle this case
- b) additional cases where such a rule would usefully apply
- c) nothing breaks in a bad way because that rule produces false positives

I'll be happy to re-open this issue and integrate such a rule.

**Comment by ambuehll** [comment]
thanks! I'll think about a simple rule, if it exists. 
for now running netconvert twice works:
- first run it with tls.discard-simple false
- then use sumo net from the above and re-run netconvert with tls.discard-simple true.

<img width="309" alt="image" src="https://user-images.githubusercontent.com/48930860/204342373-616e1c88-1e8c-481e-a37b-0b3e5feac78f.png">
