### ISSUE TITLE
Jtrrouter generate unexpected routes in output file

### ISSUE THREAD

**Issue by yeyingwuyue** [eclipse/sumo#12164]
Hello，
I'm trying to generate routes from flows and turndefs using jtrrouter.
There only one intersection in the net file and one flow in the flow file.
In turn-ratio file the straight probability is 1. 
`<edgeRelations>
     <interval begin="0" end="3900">
          <edgeRelation from="-gneE0" to="-gneE2" probability="1"/>
     </interval>
</edgeRelations>`
Firstly running cmd as:
`jtrrouter -n test.net.xml -r test.flow.xml -t test.turn.xml -o test.rou.xml -b 0 -e 3900`
there are some error messages like "Error: The route starting at edge '*' could not be closed".
Then I'm add some options and running cmd as:
`jtrrouter -n test.net.xml -r test.flow.xml -t test.turn.xml -o test.rou.xml -b 0 -e 3900 --no-warnings true --ignore-errors true`
I got the routes file Successfully.
Unexpectedly, in routes file (always on the last few lines),there are not all routes is `<route edges="-gneE0 -gneE2"/>` .
Is this expected behaviour?

And, another doubt, it seems that when definitions of the flow not set the 'to' attribute , the jtrrouter command return the error messages inevitably.

SUMO-version: 1.9.0 and 1.14.1 both version used.
operating system: windows 10
The all files are:
[jtrrouter_cmd_test.zip](https://github.com/eclipse/sumo/files/10095618/jtrrouter_cmd_test.zip)

Thank you.

**Comment by namdre** [comment]
The turning rations are applied based on the estimated time when a vehicle reaches a particular intersection rather than it's departure time. Vehicles that depart after time 3864 reach time intersection after time 3900 (based on the speed limit and length  of the travelled edges) and then the default turn ratios apply instead of the loaded probabilities.

Jtrrouter does not support fixed destinations. If you need this feature, use routeSampler instead  which also supports turning probabilities in the latest development (#9995).

**Comment by yeyingwuyue** [comment]
> The turning rations are applied based on the estimated time when a vehicle reaches a particular intersection rather than it's departure time. Vehicles that depart after time 3864 reach time intersection after time 3900 (based on the speed limit and length of the travelled edges) and then the default turn ratios apply instead of the loaded probabilities.
> 
> Jtrrouter does not support fixed destinations. If you need this feature, use routeSampler instead which also supports turning probabilities in the latest development (#9995).

Thans for your warm reply, it's very useful to solve my confusion.
