### ISSUE TITLE
Is there a method or other way to check for connections that intersect or conflict with each other?

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#12339]
Is there a method or other way to check for connections that intersect or conflict with each other?

![image](https://user-images.githubusercontent.com/101240964/208836828-bfa49893-8493-4cda-8733-e0f3324da887.png)

**Comment by m-kro** [comment]
You can iterate through the connections of the node and query whether there is a conflict between two of them using [sumolib](https://sumo.dlr.de/pydoc/sumolib.net.node.html): `sumolib.net.node.areFoes(self, link1, link2)` - where link1|link2 are the respective indices of the connections to be tested. See the [docs ](https://sumo.dlr.de/docs/Tools/Sumolib.html)how to use sumolib.net in general.

**Comment by JamesPsh** [comment]
However, the two links in the picture below do not seem to conflict, but the code do conflict.

~~~
node.areFoes(0, 13)  # True
~~~

![image](https://user-images.githubusercontent.com/101240964/208858656-156bea7c-6eef-4eac-8372-571071160a7e.png)

**Comment by namdre** [comment]
- in netedit, you can switch to prohibition-mode (H) to check conflicts
- by default, all lanes from a minor road are in conflict with the major road (since major road vehicles are free to change lanes at any time).  An exception is for roundabouts. Fine-grained control over this interpretation of conflicts is provided via netconvert options:
  - **--check-lane-foes.all** (default *false*)
  - **--check-lane-foes.roundabout** (default *true*)
