### ISSUE TITLE
Group save elements buttons in a popup

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#12360]
In the toolbar will appear only three buttons:

- Save NETEDIT Config
- Save SUMO Config
- Save -> Popup

![Sin título](https://user-images.githubusercontent.com/8238561/210223808-e156b8ec-8df0-4a78-a692-a9916f4d288a.png)

**Comment by palvarezlopez** [comment]
@namdre what do you think?

**Comment by namdre** [comment]
this would mean you always need two clicks, for saving, right? Could be annoying for users that mainly edit networks who don't use shortcuts, Also, the always-visible save buttons currently serve the function of visual remindersof unsaved changes. This would be lost if the buttons move into a submenu. 
I'd rather keep the buttons as they are. If you are worried about having a extra "save meandata" button I'd rather try to find a way for "smart" grouping (i.e. only having a single button for saving data/meanData) since in most cases only one of them will be needed anyway.

**Comment by palvarezlopez** [comment]
My objetive with this ticket is to accustom the user to use the "Save neteditcfg". We will have three buttons:

- Save neteditconfig
- Save sumoconfig
- Save archive individually

Is more easy to save the netedit config (one click) instead of saving every file individually (two clicks). Saving the netedit config will save all files (works like "Save all")
