### ISSUE TITLE
glitched terrain when camera is close to the ground

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12412]
![grafik](https://user-images.githubusercontent.com/6240630/211332276-ffe9e5ea-7780-4768-a62a-48721b6db8f0.png)

**Comment by m-kro** [comment]
The problem is with the rendered area (near/far plane), or in other words: Which is the closest object to the camera to be rendered and which is the one most far from it?
A [proposed solution](https://osg-users.openscenegraph.narkive.com/TRKnVo9H/computing-near-and-far-problem-when-viewing-large-terrain-and-small-object#) is to render the terrain in a separate subscene before the rest...

**Comment by namdre** [comment]
the problem is pretty serious when trying to use the ego camera to "walk" along the ground so it's probably work fixing somehow.

**Comment by m-kro** [comment]
@namdre Should be better by now. The ground plane has been excluded from the near / far plane computation to keep the settings from #10773 . These have proven to avoid Z fighting at ped crossings. Other approaches like using OSG DepthPartition (multiple cameras with separate but constant near /far ranges) produced Z fighting issues.

**Comment by namdre** [comment]
the glitch is gone but now I can see the roads from below the ground plane. Is this avoidable?

**Comment by m-kro** [comment]
It was an artefact of some ground plane optimisation and has been removed.
