### ISSUE TITLE
PT-routes: Provide edgelist and exit times

### ISSUE THREAD

**Issue by MHeinrichs** [eclipse/sumo#12520]
In walk trips the xml-file vehroutes_oneshot_xyz.rou.xml contains a list of visited edges and a list of relating exit times.

Please provide the same for pt-routes

**Comment by namdre** [comment]
- if option **--vehroute-output.skip-ptlines** is not set, then the public transport vehicles are included in the vehroutes output
- in case you are more interesting in public transport related times rather than the raw network times, consider using --stop-output (https://sumo.dlr.de/docs/Simulation/Output/StopOutput.html#public_transport_schedule)

**Comment by behrisch** [comment]
Sorry, I did not think of this obvious solution when discussing this with Matthias. One minor problem here is that the vehroutes output only prints the intended vehicle which may not be the one the person used (this is only visible in the tripinfo). But this should be easier to add (and add less to the overall file size).
