### ISSUE TITLE
How to download Plexe under Window System

### ISSUE THREAD

**Issue by xhy12345x** [eclipse/sumo#12555]
**operating system:**

Hello! I want to ask you about how Plexe can be downloaded and used under the window system. I plan to use Python to use Plexe under the window system. I am very lucky to see your explanation on github, but I feel that you write it in C++. So I want to ask how to download if I want to write in python.
I hope to receive your reply soon! I wish you a good day. Thank you again!

**Comment by m-kro** [comment]
Plexe extends SUMO with additional models so that it suits the Car2X/platooning use case better and uses Veins/Omnet++ also. You should be able to download and compile the SUMO fork Plexe in the same way as for the original SUMO (see Windows build process in the [docs](https://sumo.dlr.de/docs/Installing/Windows_Build.html)): Download the archive / clone it from git and follow the instructions. 
Please refer to [https://plexe.car2x.org/](https://plexe.car2x.org/) if you have questions like how to use Python with Plexe-specific functions or want to make use of precompiled packages.
