### ISSUE TITLE
'delay_based' traffic controller max. duration issue.

### ISSUE THREAD

**Issue by salperenceltek** [eclipse/sumo#12553]
Hı there, 

I had apply the delay based traffic controller  like this;

<tlLogic id="0" programID="my_program" offset="0" type="delay_based">
  <param key="detectorRange" value="100" />
  <param key="minTimeLoss" value="1" />
  <param key="file" value="NULL"/>
  <param key="freq" value="300"/>
  <param key="show-detectors" value="false"/>

  <phase duration="31" minDur="5" maxDur="45" state="GGggrrrrGGggrrrr"/>
  ...
</tlLogic> 

But ı realize that the maxDur= 45 is not working, I calculate the each phase and cyle duration. Sometimes ı see the bigger phase value over 45.  Is it normal or is the maxdur parameter not working? 

thank you for help.
**SUMO-version:** 1.15

**operating system:** Win 10

**Comment by namdre** [comment]
Currently, a phase is prolonged beyond `maxDur` if there is no traffic in the other arms of the intersection.
This often leads to better traffic flow and should thus be kept as an optional operating mode.
Nevertheless, hard constraints on maxDur should also be supported.

Awaiting feedback from @robertalms and his group.

**Comment by robertalms** [comment]
Well, we'd recommend that if `maxDur` is set that it should pose as a hard constraint, because intuitively as a user that's what you'd expect anyways. The other case you described with an automated prolongation of the phase is interesting for efficiency purposes, but should be optional, as you already suggested.
(Btw, this hard constraint for `maxDur` should also apply in the actuated control for coherency in SUMO, just in case the prolongation is enabled there too. )

**Comment by namdre** [comment]
- maxDur is now kept by default
- automatic prolongation can be activated via `<param key="extendMaxDur" value="true"/>`
- tlType `actuated` is not affected because it already keps maxDur as a hard constraint
