### ISSUE TITLE
Improve the availability of the SUMO documentation online

### ISSUE THREAD

**Issue by woodwm** [eclipse/sumo#12732]
Add your issue description here.

*If possible, upload an example that shows your problem.*

When the CI is running and even only small changes in the document, some webpages in the SUMO documentation website is unavailable. Could you consider adding a develop branch for document? Or other way to improve the availability of the documentation website.

![image](https://user-images.githubusercontent.com/13971199/222354552-4c3a8f43-63be-4d72-a243-e5ef266bef13.png)

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
This isn't due to *current* CI operations but rather to a failure in the CI pipeline that left the documentation in a broken state. The problem goes away the next time the pipeline runs (due to a documentation change or being triggered manually).

The documentation should be back up again. If you ever encounter this problem again, feel free to let us know.
For increased availability, all documentation packages are also available 
- as static html pages included in each release of sumo
- at https://sumo.sourceforge.net/docs/

**Comment by woodwm** [comment]
Then probably add https://sumo.sourceforge.net/docs/ to the readme file.
