### ISSUE TITLE
iteration times of dynamic user assignment

### ISSUE THREAD

**Issue by ZJ726** [eclipse/sumo#12745]
With dynamic user assignment, I want to achieve a scene that has as few empty edges (no vehicle pass by) as possible (less than a quarter of the edges) and no vehicle waiting on each edge. The scale of my road network is 1002 edges, with 7200 pairs of OD. My current iteration times are 50. I find that there are still many empty edges, and some individual edges have a small number of vehicles waiting (I want 0). How many iteration times does it take to achieve convergence?

OD pairs：
![image](https://user-images.githubusercontent.com/76982408/222614706-d2e4601d-dc1e-4bf6-b767-7a9be075a37b.png)

**SUMO-version:**1.8.0

**Comment by namdre** [comment]
The desired situation you describe is unlikely to be achieved with any number of iterations of "normal" dynamic user assignment.
1. Generally, there are many edges in a city that are not part of most shortest (or even shorter) paths. You will only see use of these roads if someone starts or arrives there. 
2. User equilibrium is reached when nobody can improve their travel time. Since travel time is made up of driving time and also time spent waiting, there will likely be cases where it's optimal for some drivers to spend a bit of time waiting in traffic instead of driving a big detour. Hence you will not get the waitingTime down to 0.

**Comment by namdre** [comment]
Yes. Though its an egoistic optimum: every vehicle keeps changing until there are no better alternatives.  For a global optimum it could be better to make many vehicles travel faster at the price of making a few vehicles travel longer .
