### ISSUE TITLE
Vehicle reaction to light traffic signal

### ISSUE THREAD

**Issue by hesuieins** [eclipse/sumo#12754]
Hi all,

I'm a little bit confusing that how vehicles react to the yellow traffic signal? I see the SUMO description on Traffic Lights [[link](https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html)], ``vehicles will start to decelerate if far away from the junction, otherwise they pass`` . Can I change the values of this range manually?

**Comment by namdre** [comment]
It's not really about range but rather about braking distance. If the cars can still brake, then they do so. Otherwise they pass.

The vType attribute `jmDriveAfterYellowTime` (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#junction_model_parameters)
can be used to make vehicles drive more aggressively at yellow.
