### ISSUE TITLE
crash when merging networks

### ISSUE THREAD

**Issue by fschnepf** [eclipse/sumo#12824]
Hello, 

I need to merge networks. To do so, I wrote a netccfg file. Now I don't get an output file. It seems to be an netconvert crash. 
I uploaded the files in a zip.

**SUMO-version: 1.16.0**

**operating system: Windows**
[netconvert_crash.zip](https://github.com/eclipse/sumo/files/10980043/netconvert_crash.zip)

**Comment by namdre** [comment]
notably both input networks are invalid:
- motorway_trunk_primary_secondary_tertiary.net.xml crashes sumo when trying to load it
- net15_03_simpl.net.xml has duplicate lane ids

Could it be that you did some sort of post-processing on the networks after they were initially generated by netconvert? If so, see https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why

**Comment by fschnepf** [comment]
Thank you very much for your answer. Strange, I can open both files in sumo. 
Yes, I manually changed the edges in the XML file because I didn't know better how to handle the errors like:

'Error:Invalid lane index '3' for connection from ':1175495853_0'. 

What is the correct way to handle this error? 

I hope that now my whole network is not broken.

**Comment by fschnepf** [comment]
I'm sorry that I have to ask again. My net is quite large, so I have divided it and put the different parts together. I have adjusted the offset for all pieces.  Now when I execute the command as given by you, I get the following errors:

![error](https://user-images.githubusercontent.com/127488659/225647666-af811b5f-1b75-47c4-80b3-8568beefb0f7.JPG)

Same when i merge two networks, synchronize the offset and then add a third to the merged network.

What should I do to merge multiple networks?

**Comment by namdre** [comment]
when loading without .con.xml files you also must leave out the .tll.xml files.

**Comment by fschnepf** [comment]
Sorry, uploaded the wrong screenshot. Tried it with just edges and nodes as you wrote.

here are my files 
[merge.zip](https://github.com/eclipse/sumo/files/10992233/merge.zip)
 
and the netconvert command
`netconvert -e Augs_sec_ter_res/Augs.edg.xml,Ges_mot_tru_prim/Ges.edg.xml,Herb_sec_ter_res/Herb.edg.xml,Kirch_Reich_sec_ter_res/Kirch.edg.xml,Reich_Herb_prim_sec_ter/Reich.edg.xml -n Augs_sec_ter_res/Augs.nod.xml,Ges_mot_tru_prim/Ges.nod.xml,Herb_sec_ter_res/Herb.nod.xml,Kirch_Reich_sec_ter_res/Kirch.nod.xml,Reich_Herb_prim_sec_ter/Reich.edg.xml  --output.street-names --edges.join --junctions.join-same -o merged3.net.xml --ignore-errors.edge-type`

**Comment by namdre** [comment]
the crash should be fixable but even then merging probably won't work as intended.
There is always the problem of merging networks where they overlap geographically and have diverging contents. The best practice is currently to go over the overlapping area manually and fix any problems.
This is feasible if the networks only overlap in a thin border area.
 However, in your case the networks overlap in a large area and so the whole area must be fixed manually.

An alternative approach (that we have practiced with success) is to load difference pieces of raw OSM data together. If if that data has different filtering levels it will still merge well due to not having any diverging contents in the same area.

The .net.xml files however do diverge because they are already the product of heavy processing and interpretation by netconvert.
