### ISSUE TITLE
Propagate numerical id's of edges and junctions to all other components

### ISSUE THREAD

**Issue by Matyxus** [eclipse/sumo#12886]
When using nectonvert with options: 
"--numerical-ids.node-start 0",
"--numerical-ids.edge-start 0"
Edges and Junctions are correctly changed, but this does not propagate further, for example
<tlLogic> (traffic lights) keep the same id's. 

Plus when using scenarios from real world data
in https://sumo.dlr.de/docs/Data/Scenarios.html, most (if not all) have very long id's, which
only increases file size and makes it complicated to create matrices of objects, because
instead of using matrix index as id of object it is necessary to always keep such mapping.

**SUMO-version: 1.16.0**

**operating system: Any**

**Comment by namdre** [comment]
By default, netconvert preserves ids from the input (i.e. OSM) because it is often useful to compare the generated network with the raw data. However, as you already learned, you can simply renumber the objects with **--numerical-ids.node-start 0 --numerical-ids.edge-start 0**.  This renaming now extends to traffic lights as well.
