### ISSUE TITLE
question for lane change model

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#13050]
Add your issue description here.
Hello, sir. I use lane change model of "SL2015". But I find that many vehicles traveling in a queue as follows and they don't attempt to change lane, this is not consistent with the actual situation.  do I need to set some parameters ? I'm looking forward to your early reply.

![32bb22ab261bc7e7d244f8b05a9f9ae](https://user-images.githubusercontent.com/97946646/232507125-a1cd64ac-46c1-434e-ab1a-787ca9a88550.png)

![aad183e9227c49571e75e61055cebfe](https://user-images.githubusercontent.com/97946646/232507131-441f4347-92f1-469f-9741-66798ce32773.png)

**SUMO-version:1.16**

**operating system:windows**

**Comment by SongKun2023** [comment]
Thank you sir, if I only set different desired speeds, does this situation I said above still exists ?

**Comment by SongKun2023** [comment]
If I want to increase the risk behavior of vehicles traveling from the ramp onto the main road, what parameters should I set or adjust?

**Comment by SongKun2023** [comment]
When I use LC2013,  The traffic congestion will happen on ramp as follows. And I set lcCooperative with 0.1 ，but it is useless.

![1681742571723](https://user-images.githubusercontent.com/97946646/232521933-fbfddd6f-c827-4834-9243-141998394918.png)

**Comment by SongKun2023** [comment]
Dr. namdre. Can you give me some suggestions?

**Comment by namdre** [comment]
> If I want to increase the risk behavior of vehicles traveling from the ramp onto the main road, what parameters should I set or adjust?

lcAssertive (see https://sumo.dlr.de/docs/Simulation/Safety.html#lane-changing_model)


> When I use LC2013, The traffic congestion will happen on ramp as follows.

It looks as if the connection to the acceleration lane doesn't have the correct priority (cars are still waiting on the ramp instead of moving onto the acceleration lane). In this case their behavior is governed by the junction model (rather than the lane change model as should be the case in on-ramp merging). It's hard to tell the exact problem from your screenshot though.

**Comment by SongKun2023** [comment]
OK, thank you, sir. In my simulation, the priority of ramp is 9, the priority of acceleration lane is 14. and I set the value of jmIgnoreKeepClearTime with 20, but the congestion is still severe. 

![1681804238696](https://user-images.githubusercontent.com/97946646/232709164-b3d75e9b-bc7a-40d1-acd8-8f532673ee00.png)

**Comment by SongKun2023** [comment]
At the same time,  the value of  lcAssertive is 2.

**Comment by namdre** [comment]
please attache your (zipped) network file. The part in the screenshot is sufficient (https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#reducing_the_extent_of_the_network)

**Comment by SongKun2023** [comment]
[simulation.zip](https://github.com/eclipse/sumo/files/11260418/simulation.zip)

**Comment by SongKun2023** [comment]
Thanks for your help

**Comment by namdre** [comment]
the on ramp is badly modelled (as a junction where traffic must before entering). You can tell from the grey connection indicates (or gray bars in sumo-gui).

![Bildschirmfoto von 2023-04-18 12-02-29](https://user-images.githubusercontent.com/6240630/232744721-c0fc79e5-2be5-43a0-863f-cdcce5ceda09.png)

Instead, multi lane on-ramps should have staggered lane drops as shown in the second picture
![Bildschirmfoto von 2023-04-18 12-05-02](https://user-images.githubusercontent.com/6240630/232744742-ce129a38-b104-4f02-9e59-f40814cec1d6.png)

As a side note, OSM and satellite imagery suggest that the main motorway has only 3 lanes instead of 4.

**Comment by SongKun2023** [comment]
OK, please accept my sincere thanks.
