### ISSUE TITLE
let vehicles selectively ignore a pedestrian

### ISSUE THREAD

**Issue by Y-AMDIAZ** [eclipse/sumo#13057]
I want to simulate an accident (collision) between vehicule and a man , so I created a scinario but when the vehicule approaches the man , it stops until the man passes , so I dont know how can I creat a collision , so someone please can give just what can I do , thanks 
![image](https://user-images.githubusercontent.com/129278941/232783413-954847b5-6acd-43ec-b1ad-ebcb8e4af4dc.png)

**Comment by namdre** [comment]
use `junctionModel.ignoreIDs` (see https://sumo.dlr.de/docs/Simulation/Safety.html#collisions_at_intersections)

**Comment by Y-AMDIAZ** [comment]
--->I have a question : 1. why should I download this version of sumo
                                     2. should I use traci or just edit my fils.rou.xml 
                                     3. https://github.com/eclipse/sumo/commit/8b899afe77c95a4efd2fc9c0bf701345e69849fc can you explain this step , so should I use Traci .py for result my problem

**Comment by Y-AMDIAZ** [comment]
I uninstalled my old version and I installed the new version but I have the same probleme , 
![image](https://user-images.githubusercontent.com/129278941/233029256-cdbe9024-8a16-491d-bdb6-f59d68b2ce46.png)
it stops ;

**Comment by Y-AMDIAZ** [comment]
so , Now must I  use traci.vehicle.setSpeed for my probleme ?

**Comment by namdre** [comment]
please post a screenshot that includes the window title (and hence the exact sumo version specifier)

**Comment by Y-AMDIAZ** [comment]
![image](https://user-images.githubusercontent.com/129278941/233077075-3a206daa-3b02-4084-9b47-fc5858cbc2e9.png)
![image](https://user-images.githubusercontent.com/129278941/233077240-ff5bc544-0b8f-418c-bf84-127649ec9fa1.png)

**Comment by namdre** [comment]
please zip and attach all scenario files (.sumocfg + every file mentioned therein)

**Comment by namdre** [comment]
Thank you for the example files. Your use case is also covered now. The download at https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots will take until tomorrow to reflect the updated state.

**Comment by Y-AMDIAZ** [comment]
I did what you say , I downloaded the last version but I have the same probleme ?
<img width="960" alt="image" src="https://user-images.githubusercontent.com/129278941/233926811-312b49b9-52e2-4b9a-b061-50c8421e177d.png">

**Comment by Y-AMDIAZ** [comment]
I didnt know how can I fix it , I m bloked here

**Comment by namdre** [comment]
it works with the files that you attached originally. If you have changed the files, please attach your new version.

**Comment by namdre** [comment]
I mean: send me your new scenario files. The files that are attached to this ticket do not contain any long vehicles (`<vehicle id="Car2" type="car" depart="31.50" route="r_0">`) whereas your screenshot shows a long vehicle. This means you are using some modified files.

**Comment by Y-AMDIAZ** [comment]
okey 
[projet You.zip](https://github.com/eclipse/sumo/files/11319649/projet.You.zip)

**Comment by namdre** [comment]
the two pedestrians are quite close so you have to ignore both to see the effect:
```
     <vehicle id="v_4" type="Car2" depart="45.00" route="r_0">
         <param key="junctionModel.ignoreIDs" value="p_1 p_0"/>
     </vehicle>
```

**Comment by Y-AMDIAZ** [comment]
I want to make an accident that s why I make the pedestrians close , that what i want to make an accident , not to ignore the cars !!!

**Comment by Y-AMDIAZ** [comment]
my probleme its not ignore a pedestrians  , its make an accident i want ti see a pedestrians and cars do an accident

**Comment by namdre** [comment]
to see the accident an accident you can let v_4 start one second later and it will run over the pedestrians (because it ignores them). There is currently no way to let pedestrians ignore the car and "bump" into it.
Though you can let them ignore right of way and walk onto a road where there is a pedestrian crossing. Your network is configured as shared space (gray junction) so the pedestrians don't even check right of way.

**Comment by Y-AMDIAZ** [comment]
So what is the solution ? what can I do ?

**Comment by namdre** [comment]
if you let v_4 start at time 46 you will see a collision in the gui.

**Comment by Y-AMDIAZ** [comment]
I did what you say , its not working ? car stoped ,  I did all things what didnt work , I dont know where the problem
<img width="574" alt="image" src="https://user-images.githubusercontent.com/129278941/234210233-4973da4b-95a7-4448-8efa-d7acbd419838.png">

**Comment by namdre** [comment]
This is how is the changed part of the route file:
```
<vehicle id="v_4" type="Car2" depart="46.00" route="r_0">
        <param key="junctionModel.ignoreIDs" value="p_1 p_0"/>
    </vehicle>
```
and this is how it looks:
![Bildschirmfoto von 2023-04-25 10-13-40](https://user-images.githubusercontent.com/6240630/234216145-44de4459-f1e7-4937-9e73-b2b948b47a15.png)

**Comment by Y-AMDIAZ** [comment]
but that is not an accident , the cars ignore a pedestrian , where is it the accident here in your picture , !

**Comment by namdre** [comment]
there are multiple levels of what constitutes and accident:
1. two things are in the same place when they shouldn't  -> this is what the simulation shows and it's a clear deviation from it's normal behavior of avoiding this situation
2. the simulation reports than an accident has occurred. It does this on "normal" junctions and pedestrian crossings but there is a bug where a singe walkingarea that crosses the road doesn't trigger collision checks (#13132, it's fixed in tomorrows download). With the fix it looks like in the picture
3. the objects in the simulation change their behavior. This is currently only implemented for vehicle-on-vehicle collisions See See https://sumo.dlr.de/docs/Simulation/Safety.html#collisions  (think of the current behavior as drivers always fleeing the scene after hitting a pedestrian) If you want something else to happen, you need to use tomorrows version (#13133) and set --intermodal-collision.stoptime 

![Bildschirmfoto von 2023-04-25 10-40-33](https://user-images.githubusercontent.com/6240630/234222619-d5e3fd61-0236-4e7d-82d9-3bf1438a855d.png)

**Comment by Y-AMDIAZ** [comment]
what did you change on the fils , you gave you that you have  anaccident between p_0 and v_4 but for me No,  they didnt give me that , they didn't give any collision ? 
<img width="776" alt="image" src="https://user-images.githubusercontent.com/129278941/234282851-9e18e8ce-8423-43f5-918d-ceaafc1f090e.png">

**Comment by namdre** [comment]
See again my previous point Nr 2. You need the next build for this particular collision to register.

**Comment by Y-AMDIAZ** [comment]
so , I will wait  untel tomorrrow to fix it just like you , okey
