### ISSUE TITLE
Why the tlsCycleAdaptation.py so poor?

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#13102]
I try to use the webster formula to generate timing strategies for traffic lights by the tlsCycleAdaptation.py tool. However, the performance was so poor and queue length on some lanes are very long. Could you help me? 

The attachment is the archives. Thank you!
[archives.zip](https://github.com/eclipse/sumo/files/11301573/archives.zip)

**Comment by robertalms** [comment]
From what I can tell, the cycle times in your additional file, that your got from the script output, seem to be way to small given the demand you have. You can use e.g. the option `--min-cycle` to experiment with larger cycle times, or set a different start time option `-b` the evaluation of the demand. (Note, that the script only optimizes the cycle times based on one hour long traffic flows, expecting a somewhat even distribution of the vehicle flow. )

The question at hand of course is, why the webster approach computes those seemingly small cycle times in this specific case. @yunpangfloetteroed might have a comment on this.

**Comment by yunpangfloetteroed** [comment]
Hi, thanks for reporting this issue! I checked the example you sent, especially at the intersection B2. The calculation in the script is correct. There are however several things needed to be taken into consideration when using the basic Webster's equation and this script. Accordingly, I have added some notes in the script. 

In the case you sent, the reasons for the poor result are following: 
1. Currently, this script only considers flows for one hour corresponding to the basic Webster's equation. So, a begin time needs to be given for getting the correct flows from the route file. Otherwise, the begin time = 0 is used as default. So, in your case, only the vehicles with a departure time < 3600 s are considered when using the script without defining the begin time. You can firstly find out the peak-hour time and use it in the script accordingly.

2. The through and right-turn movements share the same green time phase at all intersections. But, they can only respectively use one lane in the microscopic simulation, i.e. there is no shared lane for both through and right-turn movements. In the basic Webster's equation, critical flows are calculated according to the given signal groups. So, generally speaking, flows with the same direction and in the same green time phase are summed up. The capacity is then calculated according to the number of lanes, which the respective flows are allowed to use. Accordingly, the critical flow group for each signal phase can be identified. This script does the same thing. So, the respective capacity is over-estimated for the through-movement in your case, A lane-based critical flow group is not implemented in this script yet. Currently, you could adjust the rightmost lane to a shared lane for the right-turn and through movements. The result should be improved.

3. The lane capacity could be also an issue here. In this script, the capacity is controlled by the option saturation-headway. As default, saturation-headway is set to 2 s. So, the default capacity is 1800 veh/lane/hour, which is for a longer road section normally. In your grid network, the distance between any two intersections is around 470 m, quite short. It is expected that the capacity is lower than the default capacity. You could consider to increase the saturation-headway for adjusting the lane capacity.

4. This script only deal with one intersection at a time and does not synchronize the traffic signals at all intersections. So, poor results could happen if there is any conflict between signal plans. There is another script, called tlsCoordinator.py, to coordinate traffic signals. 

I hope that my comments are helpful for you.

**Comment by behrisch** [comment]
Feel free to add a comment if you have further questions
