### ISSUE TITLE
Question on simpla code

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#13230]
Hello, I'm confused on the code in the screenshot, there is inconsistency between 'leaderInfo is not None' and 'noleader=True', 'leaderInfo is not None' indicate that there exist a leader vehicle infront of ego vehicle, but the code below this line doisplayed 'noleader=True', is it means there is no leader vehicle infront of ego vehicle?
 
![image](https://github.com/eclipse/sumo/assets/62609436/d09a4bf3-d4cc-4339-8e11-a3d1452dbf04)

**Comment by m-kro** [comment]
Do not mix two conditions:

- having a vehicle somewhere in front = leader info is present
- whether it would be preferable to join this vehicle to form a platoon (because it travels along the same route)

If you read a bit further in the code, you see that `noLeader = True` is where the variable is initialised and updated under certain conditions.
