### ISSUE TITLE
[Help] Some questions about sumo and traci

### ISSUE THREAD

**Issue by zhangm269** [eclipse/sumo#13284]
Hello, I have three questions about sumo and it's very kind of you to help me. 
1. Is there a Python file in sumo that can **merge multiple route files into a file with a specified name**? For example, I have car route files, bicycle route files, and pedestrian route files named _car. rou. xml_, _bicycle. rou. xml_, and _peds. rou. xml_. Then, I want to join the above three route files into a single file named _all. rou. xml_.
2. **How to obtain a list of edges at an intersection through traci**, just like the method for obtaining a list of lanes at an intersection: _traci. trafficlight. getControlledLanes( )_?
3. For vehicles, we have traci. edge. getWaitingTime( ) to obtain the waiting time of all vehicles on the edge, but **for pedestrians, it does not seem to have such a convenient function**. Currently, it is still necessary to calculate the waiting time of pedestrians in the walkingarea one by one. Perhaps some improvements can be made in this area.
 
**SUMO-version:**
1.17.0
**operating system:**
Windows

**Comment by namdre** [comment]
1. you can do this with `duarouter -r car.rou.xml,bike.rou.xml,peds.rou.xml --skip-new-routes -o combined.rou.xml` (though you can just load 3 files at the same time into sumo and this often more useful than working a with a single file).
2. you can call lane.getEdgeID() and keep the unique ids (i.e. by putting them into a `set()`)
3. can you elaborate on the exact use case? I.e. for signal control it is often not enough to know the waitingTime on a walkingArea since the pedestrian could target different crossings. The function `traci.trafficlight.getServedPersonCount(tlsID, phaseIndex)` exists for this reason.

**Comment by zhangm269** [comment]
Okay, I understand. Thank you very much. Regarding the third question, I was previously confused about why pedestrians cannot count their waiting time like cars. Your explanation made me understand the reason for doing so.

**Comment by namdre** [comment]
the idea of 3 is now tracked at #13286
