### ISSUE TITLE
Segmentation fault netconvert 

### ISSUE THREAD

**Issue by gladysmcgan** [eclipse/sumo#13413]
I have a segmentation fault error when I use netconvert on a particular OSM file, but it works when I use the same command for other OSM files. The only difference I can see is perhaps the size of the file (~40MB).. 

`netconvert -c osm0T.netccfg --osm-files MUN_mod99.osm --output-file MUN_sumo_raw0.net.xml --plain-output-prefix MUN --log log.log `
`67165 segmentation fault  netconvert -c osm0T.netccfg --osm-files MUN_mod99.osm --output-file   MUN`

I put all input files here: [google drive folder](https://drive.google.com/file/d/1XhCrBc2pACcKRBo-Q173kpytKTThg7eb/view?usp=sharing)

Thanks in advance!

SUMO version 1.17.0, MacOS

**Comment by m-kro** [comment]
Vector out of range at 
https://github.com/eclipse/sumo/blob/f9e1375fe523a82490d7a21537208b0f702ae9de/src/netbuild/NBEdge.cpp#L2770

**Comment by namdre** [comment]
there seem to be 2 distinct bugs here:
- invalid initialization of toLane in line 2754. Instead, this should iterate over the contents of toLaneMap rather than over the raw lane indices
- if the check in line 2757 fails, then the connections were already erased but the calling code in recheckLanes assumes unmodified connections
