### ISSUE TITLE
How to retrieve ids of vehicles finishing their routes on every time step.

### ISSUE THREAD

**Issue by Metro1998** [eclipse/sumo#13515]
First，thank for your execellent work！It helps a lot to my research.
And my ultimate goal is to calculate the waiting time or delay for each vehicle when they finish their routes. I know that through `traci` I can subscribe to `VAR_WAITING_TIME` or `ACCUMULATED_VAR_WAITING_TIME`, but they require specific vehicle_ids as inputs. So, I am wondering if it is possible to obtain the ids of vehicles which finish their routes at each time step, and then I can calculate their delay or waiting time throughout the route.

Thanks a lot.
**SUMO-version: 1.16.0**

**operating system: win10**

**Comment by m-kro** [comment]
If you just want to use the waiting time values after completing the simulation, you could use [TripInfo ](https://sumo.dlr.de/docs/Simulation/Output/TripInfo.html) output as well. In order to get the IDs of arrived vehicles at the current time step, there is [traci.simulation.getArrivedIDList()](https://sumo.dlr.de/pydoc/traci._simulation.html#SimulationDomain-getArrivedIDList).

**Comment by namdre** [comment]
You cannot currently retrieve any data (such as waiting time) for vehicles via TraCI once they have arrived. However, starting with version 1.17.0 you can call `traci.simulation.getParameter` to retrieve aggregated trip statistics for arrived vehicles (which had a tripinfo device equipped): https://sumo.dlr.de/docs/TraCI/Simulation_Value_Retrieval.html#device_parameter_retrieval

**Comment by Metro1998** [comment]
Now I got it， thanks a lot.
