### ISSUE TITLE
Junction cluster

### ISSUE THREAD

**Issue by Swayam069** [eclipse/sumo#13568]
For a junction cluster, we have 3-4 ids in a cluster depending on the road map, soo can we sort out the junction cluster into individual ids to get the latitude and longitude of this separate ids. 
One more question, so this junction id are = cluster_1_3 or we also have junction id = :cluster_1_3, what does this ":" means in a junction id. does this ":" means that the junction is a internal junction that start with the ":"

-Thanks 
-Swayam

**Comment by namdre** [comment]
- you can keep the ids separate rather than joining them into a cluster but this is not recommended:
  - https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html#junctions- 
  - https://sumo.dlr.de/docs/Networks/PlainXML.html#reasons_for_joining_node_clusters
 - there are many other ways to get lat/lon out of sumo: https://sumo.dlr.de/docs/Geo-Coordinates.html
 - yes, the ":" denotes internal junctions: https://sumo.dlr.de/docs/Networks/SUMO_Road_Networks.html#internal_junctions

**Comment by Swayam069** [comment]
thanks for the answers, 
one confusion in the cluster, taking a live example of the map that i have cluster_6206018894_7859985245_7860122001_7860122013_#1more
this is one cluster, can i reduce this into more of the junction.

what does the "-" sign implies in the edgeid of a simulation data, is it the negative index for the edgeid or some thind else, i searched the "-" sign in the sumo document but was not able to do so.


-Thanks for the help
swayam

**Comment by namdre** [comment]
- you can prevent joining specific junctions by setting netconvert option **--junctions.join-exclude JUNCTION_ID** during initial network import
- see https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html#relationship_between_osm_ids_and_sumo-ids
