### ISSUE TITLE
Deadlock(turn left and right, same future route)

### ISSUE THREAD

**Issue by RahelehSh** [eclipse/sumo#13592]
Hello,

When I simulate my real world network, I see deadlock in some situations.
for example:

![Deadlock_1](https://github.com/eclipse/sumo/assets/94211436/f1140e4d-6b87-436f-8b4a-9985b2df9a12)

![image](https://github.com/eclipse/sumo/assets/94211436/b6fff7ca-77b8-4ead-9a86-e34095e8e160)

what can i do to never see this situations?

Thanks in advance for possible solutions!

SUMO-version: SUMO-1.18.0

operating system: Windows 10

**Comment by namdre** [comment]
Deadlock in heavy-traffic and for specific network/troute geometries cannot be entirely avoided (neither in reality). 
You can overrule any kind of deadlock on junctions that lasts longer than **X** seconds by setting sumo option **--ignore-junction-blocker X** .

However, these deadlocks may also point to potential modelling errors in your scenario:

- in the first image, having lots of vehicles that perform a turn-around (coming from the western side, turning left twice and going back west) may reflect an unrealistic origin-destination matrix (in a small scenario) or a lack of systematic traffic assignment (in a larger scenario)
- in the second image, the jam on the intersection might either be due to an error in the network (potentially fixed by loading and saving then network with the latest version of netedit) or it might be due to signal plans that give insufficient time to leave the intersection after a phase ends (this requires looking at the development of the jam in sumo-gui).

**Comment by RahelehSh** [comment]
Thank you for your reply.

With your giudes i used --ignore-junction-blocker option to overrule first situation but my question is how simulator distiguish between these junction blocks and other traffic jams (for example because of traffic light plan)?

for second situation, i disable sub-lane model and it's ok.

**Comment by namdre** [comment]
**--ignore-junction-blocker** only concerns vehicles that are within an intersection and thereby blocking cross traffic. In contrast, "normal" jamming by cars queued at a traffic light is happening unchanged.
