### ISSUE TITLE
'@' appears in the vehicle type

### ISSUE THREAD

**Issue by woodwm** [eclipse/sumo#13604]
Add your issue description here.

I defined a custom vehicle type named `"av"` in the route file `*.rou.xml`. In the simulation, I found that sometimes there is a '@' appears in the vehicle type by `traci.vehicle.getTypeID()`, e.g. `"av@30.3"`. some vehicles type are `"av"`. I am not sure whether this is expected as it seems make things complicated.

*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.18.0
**operating system:**
Windows x64

**Comment by m-kro** [comment]
This happens when vehicle-specific attributes are changed during the simulation run on vehicles which didn't have their singular vehicle type before. It is used in the [blue light](https://sumo.dlr.de/docs/Simulation/Emergency.html#blue_light_device) and the [ToC](https://sumo.dlr.de/docs/ToC_Device.html) device.

**Comment by woodwm** [comment]
Hi, @m-kro You are correct. I changed the vehicle type of some vehicles during the simulation by `traci.vehicle.setType()`. How can I turn this feature off?
