### ISSUE TITLE
Draw lefthand driving networks in netedit

### ISSUE THREAD

**Issue by HRYEJJKUK** [eclipse/sumo#13631]
Netedit draws the road network in the net.xml file exported by OSM, with the direction of road travel being to the left. However, when drawing the road network in the newly created empty file, the road traveling direction is traveling on the right.
![image](https://github.com/eclipse/sumo/assets/121792232/34927190-c88f-49b9-8a0c-58e3e8158fe9)
    The image above shows the road network drawn in the newly created net.xml for driving on the right.
![image](https://github.com/eclipse/sumo/assets/121792232/3a56300f-226b-47b6-ad31-a8d05a530629)
    The image above shows the road network plotted in the OSM exported net.xml for driving on the left.

**SUMO-version:1.18.0**

**operating system:win-64**

**Comment by m-kro** [comment]
In order to create a new lefthand-driving network in netedit, do the following:

- start netedit and create a new network: `File > New Network`
- go to `Processing > Options`
- from the tree menu, choose the `Processing` section and set lefthand=true
- draw an edge
- press F5 or go to `Processing > Compute Junctions` to recompute the network
