### ISSUE TITLE
Why Energy Consumption in EVehicles is Zero sometimes?

### ISSUE THREAD

**Issue by Nitinyerra** [eclipse/sumo#13654]
Hi
I have couple of queries regarding actual battery capacity and Energy Consumed 
I'm using these API's to get the values 
```
energy_consumed = traci.vehicle.getParameter(i, "device.battery.energyConsumed")
energy_actualBatteryCapacity = traci.vehicle.getParameter(i, "device.battery.actualBatteryCapacity")
```
I want to know why at times the Energy Consumed is zero & how the actual Battery capacity will go up.

Can you let me know what are the reasons for this behaviour.

**SUMO-version:** 
1.18.0

**operating system:**
Windows

**Comment by m-kro** [comment]
Electric vehicles - depending on their configuration - can recuperate energy through braking. The corresponding setting is called **recuperationEfficiency** (see [docs](https://sumo.dlr.de/docs/Models/Electric.html#defining_electric_vehicles)). Is that what you mean? Otherwise, vehicles won't consume energy when parked and the battery can get charged at charging stations.
