### ISSUE TITLE
Different speeds for different lanes in sumo

### ISSUE THREAD

**Issue by preesent** [eclipse/sumo#13700]
I want to use sumo to simulate a highway congestion scenario, but I found that in the congested area the speed of the left lane is significantly faster than the right lane, how can I solve this problem?

![image](https://github.com/eclipse/sumo/assets/37241282/96b84526-279c-428e-b65a-2bcdd155eb79)

**SUMO-version:1.14.1**

**operating system:Windows10**

**Comment by m-kro** [comment]
You mean the vehicles on the ramp only have a short stretch to accelerate? If the ramp edges are not limited by a low speed limit, then there is just not enough space to accelerate enough. Another point is that they have to merge at a zipper before reaching the motorway. You'd have to think about a better way to move/eliminate that point such that vehicles do not have to brake there.

**Comment by preesent** [comment]
I mean due to vehicles merging onto the highway from an on-ramp, congestion occurs on the highway. In the simulation, only the rightmost lane on the main road experiences a significant speed reduction, while vehicles in the left lanes can still pass through quickly. In a real-world scenario, all three lanes of the main road should be congested. How can this be simulated in SUMO?

**Comment by m-kro** [comment]
In order to change the lane usage and the impact of merging vehicles, you'll have to play with the [lane change model](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models) parameters. The default lane change model is LC2013. Some options:

- higher lcAssertive value (at least for the vehicles entering the motorway)
- lcKeepRight (to adjust the lane usage)

Overall this is difficult to adjust and the given hints may work or not be sufficient.

**Comment by preesent** [comment]
By fine-tuning these two parameters, the above problem was greatly improved, thank you!
