### ISSUE TITLE
incorrect emission output values for perVeh with 100% BEV

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#13792]
When BEV is 100% in a network, SUMO still delivers values for emissions with the unit perVeh. 

Example:
traveltime="9.719222e-03" CO_perVeh="2.030695" CO2_perVeh="128.674886" HC_perVeh="0.012461" PMx_perVeh="0.002997" NOx_perVeh="0.053950" fuel_perVeh="41.040848" electricity_perVeh="0"/>

**SUMO-version:**
V1_18_0+0508-22637e2f52c
**operating system:**
Linux

**Comment by behrisch** [comment]
@yunpangfloetteroed Can you please refer to the simulation being run (and maybe save it to some folder) even if it is on the huainan machine?

**Comment by yunpangfloetteroed** [comment]
The cfg file sumo_test_vtypes_cold_100.sumocfg is under ~/huainan/huainan/routes/ . The resultant emission file emission_cold100_900.xml.gz is under ~/huainan/huainan/adds

**Comment by behrisch** [comment]
You have printing defaults enabled which will result in empty edges printing the values for the default vehicle type that is the type associated with "DEFAULT_VEHTYPE". So this is expected behavior. Maybe you should change the name of your main vehicle type distribution to "DEFAULT_VEHTYPE" although this will also have the strange side effect, that the printed values can be different in each interval because it is a vTypeDistribution. Probably the code should check here whether it is a distribution and then do a weighted average. This may be quite costly though

**Comment by yunpangfloetteroed** [comment]
Yes, it makes sense to get an overview how much emission would produced and how much energy would consumed if a vehicle would run on empty edges.

**Comment by yunpangfloetteroed** [comment]
another related ticket is open. #13800
