### ISSUE TITLE
import OSM attribute turn:lanes (trac #1446)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1446]
According to some conventions [http://wiki.openstreetmap.org/wiki/DE:Key:lanes] turning lanes on minor roads are not included in the 'lanes' count. They are instead included in the turn:lanes key [http://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane].
Failure to import them causes bottlenecks in imported urban networks.

Migrated from http://sumo.dlr.de/ticket/1446
```json
{
    "status": "new", 
    "changetime": "2014-11-04T14:22:04Z", 
    "description": "According to some conventions [http://wiki.openstreetmap.org/wiki/DE:Key:lanes] turning lanes on minor roads are not included in the 'lanes' count. They are instead included in the turn:lanes key [http://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane].\nFailure to import them causes bottlenecks in imported urban networks.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1415110924132762", 
    "component": "net building (NETGEN, NETCONVERT)", 
    "summary": "import OSM attribute turn:lanes", 
    "priority": "major", 
    "keywords": "", 
    "time": "2014-09-19T14:48:18Z", 
    "milestone": "1.1.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
I agree

**Comment by namdre** [comment]
Some heuristics are used because OSM only describes arrows painted on the road surface without actually mapping them to destination edges.  This leaves some ambiguities in particular when interpreting missing arrows ('none').
Right now they are interpreted as straight connectivity but I've seen at least one place (52.434551640936526, 13.538672881242963) where this is wrong (connectivity is straight+right)
