### ISSUE TITLE
Adapt opposite-direction driving for emergency vehicles (trac #1996)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1996]
* different reasons for using the opposite direction lane
* different checks (may assume foe cooperation)
* may use arbitrary lanes in the opposite direction

Migrated from http://sumo.dlr.de/ticket/1996
```json
{
    "status": "new", 
    "changetime": "2015-11-13T08:53:19Z", 
    "description": "* different reasons for using the opposite direction lane\n* different checks (may assume foe cooperation)\n* may use arbitrary lanes in the opposite direction\n", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1447404799623637", 
    "component": "voduges", 
    "summary": "Adapt opposite-direction driving for emergency vehicles", 
    "priority": "major", 
    "keywords": "", 
    "time": "2015-11-13T08:53:19Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "task"
}
```

**Comment by namdre** [comment]
Emergency vehicles may take a long time to change to the opposite direction lane due to strategic concerns. In the context of rescue lane formation this is already remedied by setting 
`ego.getLaneChangeModel().setParameter(toString(SUMO_ATTR_LCA_STRATEGIC_PARAM), "-1");` if the vehicle has been waiting for some time.
A similar feature should be part of the lanechange model when considering opposite-direction changes

**Comment by behrisch** [comment]
work continues in #9310
