### ISSUE TITLE
Crash on reloading

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2090]
ocassionally when a cpu-intensive simulation is reloaded before stopping it first.

**Comment by namdre** [comment]
another way to trigger crash: select reachable, color by reachability, reload

**Comment by namdre** [comment]
sumo-gui crashes frequently on reloading (large networks), regardless of prior coloring. Stack traces are confusing and suggest memory corruption.

**Comment by palvarezlopez** [comment]
@namdre Try to build SUMO with FOX Debug library, and then reproduce the error.

**Comment by namdre** [comment]
I have one reproducible crash (on linux) that is caused by the lane context menu: The new 'select reachable' submenu is destroyed when the popup is destroyed yet its menu items somehow still receive a SEL_UDPATE message when reloading the simulation.
The only differences between the new menu items and the old ones are that old ones are directly added to the popup and the new ones are added in a new FXMenuCascada/FXMenuPane

**Comment by namdre** [comment]
Crash appears to be gone.
