### ISSUE TITLE
routers do not consider delays due to intersections (trac #2202)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2202]
even when weight files are loaded or current travel times are used (in simulation routing), the travel time along a route with seldom used intersections is underestimated.

see #752, #2566

Migrated from http://sumo.dlr.de/ticket/2202
```json
{
    "status": "new", 
    "changetime": "2017-04-28T13:07:07Z", 
    "description": "even when weight files are loaded or current travel times are used (in simulation routing), the travel time along a route with seldom used intersections is underestimated.\n\nsee #752, #2566", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1493384827142505", 
    "component": "routing (DUAROUTER)", 
    "summary": "routers do not consider delays due to intersections", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2016-03-15T14:35:38Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
Now that #752 is basically implemented, it would be possible to apply a penalty to the internal edges. However, this  is somewhat difficult since delays will become noticeable on the incoming edge once vehicles start to use it and thus a flat penalty would overestimate delays.
For edges where all connections have minor priority, the empty-network traveltime could take the required deceleration into account.
This still would not solve the problem for left-turns from 1-lane priority roads.

**Comment by behrisch** [comment]
A test exhibiting the behavior is sumo/extended/simulation_routing/assignment/taz_astar where the shortest route 5/5to5/6 5/6to6/6 6/6to6/7 6/7to7/7 7/7to7/8 7/8to8/8 8/8to8/9 8/9to9/9 9/9to8/9 is slower than 5/5to5/6 5/6to5/7 5/7to5/8 5/8to5/9 5/9to6/9 6/9to7/9 7/9to8/9 8/9to9/9 9/9to8/9 due to losses at the priority junctions.
