### ISSUE TITLE
scenario with demand loaded from vehroute-output behaves different from the original run (trac #3024)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3024]
observed in the berlin_mitte scenario which uses oneshot assignment

Suggested solution:
- add option to rerouting device to load vehroute output that includes all routes and the time of rerouting
- add event based commands to replay the rerouting at the respective times

Migrated from http://sumo.dlr.de/ticket/3024
```json
{
    "status": "new", 
    "changetime": "2017-10-06T07:05:50Z", 
    "description": "observed in the berlin_mitte scenario which uses oneshot assignment\n\nSuggested solution:\n- add option to rerouting device to load vehroute output that includes all routes and the time of rerouting\n- add event based commands to replay the rerouting at the respective times", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1507273550978405", 
    "component": "simulation data output", 
    "summary": "scenario with demand loaded from vehroute-output behaves different from the original run", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-04-20T10:38:46Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by aminissn** [comment]
I just wanted to confirm the original comment of @behrisch that the --device.rerouting.period has a significant impact. 
![image](https://user-images.githubusercontent.com/30176885/136065400-388132e4-f61d-4421-a287-e23060bf106f.png)
![image](https://user-images.githubusercontent.com/30176885/136065429-a2683ef2-72ac-4f6e-b916-457603db28db.png)
I am also adding my experiment for future reference. 
[grid_vehroute_output.zip](https://github.com/eclipse/sumo/files/7287574/grid_vehroute_output.zip)

**Comment by namdre** [comment]
#9199 should also have an impact on this issue

**Comment by namdre** [comment]
@aminissn did you try to reproduce this in even smaller networks? 140 junctions is still pretty big.

**Comment by namdre** [comment]
In a smaller grid network, the first deviation was caused by the same issue already mentioned in the top post: vehicles that perform rerouting may have to wait at an intersection (because their target edge is full) and then change their route, whereas the rerun-vehicles skip the waiting because they start with the final route. Small deviations can blow up to large ones in a congested/chaotic situation.

**Comment by aminissn** [comment]
I agree with the impact of rerouting decisions and I'm afraid that there is no real solution to resolve the issue.

**Comment by namdre** [comment]
A solution is offered in this ticket: replay the route choice decisions so they come at the same time as in the original run.

While this should achieve the goal of having a repeatable run without all the computational effort of route-search, it does strike me as a bit ugly. I think the ugliness mainly comes from the observation that seemingly tiny (and arguably beneficial changes) - *waiting less due to using a good route earlier*, can degrade the whole system so that it achieves less throughput.
To me, this suggests that the "solution" found by one-shot routing is over-adapted to a particular traffic situation and isn't robust with regard to small changes.  
One the one hand, this is just how chaotic systems work: *small changes, large effects*. But on the other hand, route choices might conceivably be smarter and offer more margin of error from drifting into chaos/congestion.

**Comment by namdre** [comment]
Another thing that is causing deviations: output-precision of vehroute-output when writing departSpeed, speedFactor, etc...

**Comment by namdre** [comment]
Option **--vehroute-output.intended-depart** creates a problem: In the original simulation, departure may be delayed because of failed insertion attempts on the same edge (when not running with option **--eager-insert**). In the rerun, only the successful departLane is recorded and thus the failed insertion attempt does not occur. Ultimately, this may cause earlier insertion.

**Comment by namdre** [comment]
when not using option --vehroute-output.intended-depart, the vehicles may still be written in an order that is different from the original loading order. This makes causes them to get different speedFactors, unless the speedFactors are already set in the vehroute output with sufficient precision (#10091)

**Comment by namdre** [comment]
The current implementation uses a fail-hard approach if the simulation deviates in any way that makes one of the rerouting events unrepeatable. This should help with finding left-over corner cases and make it more obvious that prefect reproduction failed.

As a downside, this makes such vehroute input unsuitable for running scenario variations (when using the new option **--replay-rerouting). Instead the use case of building somewhat-robust oneshot scenarios should be handled via #9312
