### ISSUE TITLE
allow access to cfmodel functions (trac #3361)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3361]
- traci.vehicle.followSpeed(vehID, speed, gap, leaderSpeed, leaderMaxDecel, leaderID)
- traci.vehicle.stopSpeed(vehID, speed, gap)
- traci.vehicle.getSecureGap(vehID, leaderID, speed, leaderSpeed, leaderMaxDecel)

**Comment by wmustafaAwad** [comment]
Note:
In the current Python API, the first two functions are exposed as:
traci.vehicle.**get**FollowSpeed(vehID, speed, gap, leaderSpeed, leaderMaxDecel, leaderID)
traci.vehicle.**get**StopSpeed(vehID, speed, gap)

(i.e. the **get** part in the names was missing in the comment above.) 
Thought of leaving a comment, since this is yet to be added to the documentation. I found it out by following the formatting pattern (i.e. guessing).


> * traci.vehicle.followSpeed(vehID, speed, gap, leaderSpeed, leaderMaxDecel, leaderID)
> * traci.vehicle.stopSpeed(vehID, speed, gap)
> * traci.vehicle.getSecureGap(vehID, leaderID, speed, leaderSpeed, leaderMaxDecel)

**Comment by namdre** [comment]
at least the python documentation is now updated: https://sumo.dlr.de/pydoc/traci._vehicle.html
