### ISSUE TITLE
when loading a network without internal links, the option no-internal-links in the options dialog is not activated

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#3575]

**Comment by palvarezlopez** [comment]
@namdre Given a net with only two junctions and one egde, in NBNetBuilder::compute(...) the next fragment of code should change the option "no-internal-link"

```
if (oc.isDefault("no-internal-links") && !myNetworkHaveCrossings && myHaveLoadedNetworkWithoutInternalEdges) {
        oc.set("no-internal-links", "true");
    } else if (!mayAddOrRemove && myNetworkHaveCrossings) {
        // crossings added via netedit
        oc.resetWritable();
        oc.set("no-internal-links", "false");
    }
```

The problem is that **oc.isDefault("no-internal-links")** returns **false**. A possible solution can be set a default value of **true** or **false** at the beginning of loading in netedit.

**Comment by namdre** [comment]
oc.isDefault returns the value of Option::myHaveTheDefaultValue which is initialized to True in the option constructor. The value is only set to false if someone calls oc.set("no-internal-links", someValue)

I think more debugging is needed.
