### ISSUE TITLE
poiLane positions are not correct in sumo-gui

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#4002]
poiLane positions can be shown correctly in netedit, but not in sumo-gui given that the input shape file is correct.

**Comment by namdre** [comment]
there was an inconsistency in the interpretation of lanePosLat between sumo-gui and netedit:
sumo-gui uses the same coordinate system as the lanes: lower numbers indicate movement to the right, higher numbers movement to the left in driving direction.

Netedit was using it the other way around so I made it consistent with the sumo-gui interpretation (because it is older and thus expected by more people).

@yunpangfloetteroed You will have to negate all the offsets in your file.
