### ISSUE TITLE
Project import error

### ISSUE THREAD

**Issue by ycx667214** [eclipse/sumo#4123]
Hello, I am learning sumo this new software, I use VS2017 import project, suggesting that a lot of source files can not be opened, as well as the error does not identify the definer, I would like to know your build environment and how to run this project, thank you very much

**Comment by palvarezlopez** [comment]
Hi,

What errors are you receiving from Visual Studio?

Regards

Von: ycx667214 [mailto:notifications@github.com]
Gesendet: Dienstag, 29. Mai 2018 11:03
An: eclipse/sumo
Cc: Subscribed
Betreff: [eclipse/sumo] Project import error (#4123)


Hello, I am learning sumo this new software, I use VS2017 import project, suggesting that a lot of source files can not be opened, as well as the error does not identify the definer, I would like to know your build environment and how to run this project, thank you very much

**Comment by namdre** [comment]
If you just want to try out the software you do not need to build it.
The releases can be downloaded at https://sourceforge.net/projects/sumo/files/sumo/
We also have a nightly build which can usually be found at http://sumo.dlr.de/wiki/Downloads#SUMO_-_Latest_Development_Version

However, this wiki is down temporarily so you cannot access the nightly build just now.
If you must build sumo yourself: (quoting from the wiki because it is down)

Prerequisites
     installed Visual Studio Community, Professional or Enterprise 2013 or later.
    installed cmake for windows
    fresh sumo sources (either an unpacked src zip or a git clone, see Installing/Linux_Build#Getting_the_source_code)
    installed libraries (Xerces-C, Proj, Fox) preferrably by cloning https://github.com/DLR-TS/SUMOLibraries/.
        Make sure that the SUMO_LIBRARIES environment variable points to your cloned directory
    Place all relevant dll dirs in the PATH

Build using cmake-gui
     start cmake gui
    select source path (e.g. D:\projects\sumo)
    select build path (e.g. D:\projects\sumo\cmake-build)
        can be identical to source path but it is advised to separate
        Build dir will be created if necessary
    Start configuration pressing "Configure" button
        select compiler (default should do)
    Create the Visual Studio solution pressing "Generate" button
    Open D:\projects\sumo\cmake-build\SUMO.sln (from the explorer or by clicking on open project)
    Build the configurations you want
        Binaries appear in D:\projects\sumo\bin


For further usage questions, please use the mailing lists: http://sumo.sourceforge.net/userdoc/Contact.html
