### ISSUE TITLE
TraCI-Controlled Vehcle's Speed Reset to 0 when Entering Junction

### ISSUE THREAD

**Issue by dbuse** [eclipse/sumo#4245]
I'm experiencing the following issue with SUMO 0.32.0 on Linux:
A vehicle in the simulation is controlled entirely remotely via TraCI from a python script (new position via moveToXY and speed via setSpeed). SpeedMode and LaneChangeMode are set to 0.
Still, when the vehicle enters any junction in a simulation step, SUMO sets the vehicle's speed to 0 for one step and prints the following:

>  Warning: Vehicle 'ego-vehicle' performs emergency stop at the end of lane '-283921463#0_0' for unknown reasons (decel=-20.40, offset=2.43), time=60.00.
![screenshot-sumo-speed-to-0](https://user-images.githubusercontent.com/456146/41583524-5635a046-7394-11e8-8a67-1a92f8e79952.png)

Is there any way to avoid this breaking? Or might this be a bug?

**Comment by namdre** [comment]
It is expected behavior whenever the the vehicle route does not extend past the current edge (because there is then no information regarding which internal lane to use).
By default, a moveToXY-controlled vehicle stays on its current route but when it reaches an edge that is not on its route, the new route will consist only of that single edge (hence the problem at the next intersection).

I suppose one could try to guess the continuation (preferentially straight) based on the current speed but to cover all cases this might have to extend the route across multiple junctions. 

For now, the only remedy is to set the vehicle route via TraCI so the vehicle will know where to go when reaching the intersection.

**Comment by namdre** [comment]
The braking is not due to safety constraints but rather because the position of the vehicle is undefined after the end of its route (it treats the end of the route like a dead-end).
The only automatable remedy would be heuristic that guesses the next edge.

**Comment by dbuse** [comment]
Alright, then we can close this.
