### ISSUE TITLE
is it possible to use vehicles for oneshot-assignment? 

### ISSUE THREAD

**Issue by pistpost** [eclipse/sumo#4275]
We used vehicles for oneshot-assignment. but the first car was without a route.

**Comment by namdre** [comment]
The issue tracker is for bug reports and not for usage questions. Post your question on the mailing list: http://sumo.dlr.de/wiki/Contact
I advise to add more details to your question as well since It is unclear what problem you encountered. Maybe it helps to read this: http://sumo.dlr.de/wiki/Demand/Automatic_Routing
