### ISSUE TITLE
retrieve emergency stopped vehicles

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4312]
traci.simulation.getEmergencyStoppingVehicleNumber
traci.simulation.getEmergencyStoppingVehicleIDList

**Comment by namdre** [comment]
structurally similar to the implementation of  getCollidingVehiclesNumber() and getCollidingVehiclesIDList()

**Comment by HZQ950419** [comment]
Hi Jakob,
I use emergency_stops = traci.simulation.getCollidingVehiclesNumber() to get the emergency stops,but it returns 0 as below.I would like to know why the simulation outputs can count the emergency stops but the python interface can't.I suggest to add it to the  latest development version of SUMO.


Loading configuration... done.
Loading net-file from 'data/cross.net.xml'... done (3ms).
Loading additional-files from 'data/cross.det.xml'... done (1ms).
Loading done.
Simulation started with time: 0.00
0
0
0
0
0
0
Warning: Vehicle 'down_left_3' performs emergency stop at the end of lane '4i_1' because of a red traffic light (decel=-7.65, offset=2.98), time=57.00.
0
0
0
0
0
0
Warning: Vehicle 'right_30' performs emergency stop at the end of lane '1i_0' because of a red traffic light (decel=-12.06, offset=5.51), time=110.00.
0
0
0
0
0
0
0
0
0
0
0
0
Simulation ended at time: 218.00
Reason: TraCI issued load command.
Performance: 
 Duration: 157ms
 Real time factor: 1388.54
 UPS: 28598.726115
Vehicles: 
 Inserted: 43
 Running: 0
 Waiting: 0
Emergency Stops: 2

**Comment by HZQ950419** [comment]
So,how can I get the number of emergency stops?

**Comment by namdre** [comment]
@HZQ950419 You have to download the latest development version. (traci.simulation.getEmergencyStoppingIDList())  It appears that our nightly build process is currently out of order. You can try to download http://sumo.dlr.de/daily/sumo-msvc12x64-git.zip tomorrow or build sumo yourself on the operating system of your choice: http://sumo.dlr.de/wiki/Developer/Main#Build_instructions

**Comment by namdre** [comment]
Please attach a failing example scenario.

**Comment by namdre** [comment]
user reported as "invalid" via mailign list
