### ISSUE TITLE
Boolean attributes cannot be edited during inspect selections

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#4521]

**Comment by namdre** [comment]
@palvarezlopez I think this is a misunderstanding. 

If all objects in the selection have 'true' or 'false' then it's ok to show a checkbox and edit it.
If some objects have true and some have false then a string input with "0 1" should be shown so that the user knows the selection is heterogeneous. Setting this value to the string "0" or "1" should then be allowed.

If its simpler to implement, it would also be ok to always show the string input for booleans when inspecting multiple objects.
