### ISSUE TITLE
problems running TraCITestClient

### ISSUE THREAD

**Issue by yoannzh** [eclipse/sumo#4607]
Hej,
I am trying to run TraCITestCLient project to check how C++ TraCI lib works. 
When running this testAPI() function, the program gets to line 672 of TraCITestCLient.cpp 'edge.adaptTraveltime(edgeID,42,0,10);' I got this error message in SUMO-gui : 
Error: Answered with error to command 0xaa: The first variable must be the begin time given as int.
if I skip these lines with edge and jump to line 684, I get this error: 
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown

Please help with this . Am I using TraCITestCLient correctly? thanks!

Full message in SUMO-gui:
Loading configuration... done.
***Starting server on port 1337 ***
Loading net-file from 'SUMO/ROAD_1.net.xml'... done (3ms).
Loading done.
Simulation started with time: 0.000
Error: Answered with error to command 0xaa: The first variable must be the begin time given as int.

**Comment by namdre** [comment]
This sounds as if your are using mismatching versions of sumo and the testclient (1.0.0 and 0.32.0 are incompatible due to protocol changes).

Also, the testclient carries a lot of baggage because it performs low-level tests of the protocol. You are better off, copying the method from testAPI() into a client derived from here: http://sumo.dlr.de/wiki/TraCI/C%2B%2BTraCIAPI#Example_Code
