### ISSUE TITLE
1.0.0 and 1.0.1 downloads are provided without gdal support

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4626]
0.32.0 came with GDAL

**Comment by behrisch** [comment]
This is not a bug. It is a consequence of the license change. We do not have the permission to distribute GDAL under EPL since it contains GPL code. GDAL is such a complex thing with lots of parts and dependencies that I do not expect this issue to be cleared, so it gets an optional addition just like OSG and ffmpeg. We could release an "all bells and whistles, use at your own risk" version and just declare the different licenses but I cannot assess the legal status of such a construct. Shall we try?

**Comment by namdre** [comment]
Yes. I think it would be better than telling people they need to compile on windows or download an outdated version if they need to import a shapefile.

**Comment by paul-harambee** [comment]
What is the implication of building using 0.32.0? Is anything fundamentally different that I should be aware of?

I am on a Windows machine and need to create the network for my study from a shapefile.

**Comment by behrisch** [comment]
I would rather recommend to use a nightly build http://sumo.dlr.de/daily/sumo-msvc12extrax64-git.zip.

**Comment by paul-harambee** [comment]
It would see that not all of the parameters are available:

```
Error: On processing option '--shapefile.laneNumber':
 No option with the name 'shapefile.laneNumber' exists.
Error: The parameter 'NOLANES' is not allowed in this context.
 Switch or parameter name expected.
Error: On processing option '--shapefile.speed':
 No option with the name 'shapefile.speed' exists.
Error: The parameter 'SPEED' is not allowed in this context.
 Switch or parameter name expected.
Error: On processing option '--shapefile.name':
 No option with the name 'shapefile.name' exists.
Error: The parameter 'ST_NAME' is not allowed in this context.
 Switch or parameter name expected.
Error: On processing option '--shapefile.node-join-dist':
 No option with the name 'shapefile.node-join-dist' exists.
Error: The parameter '0' is not allowed in this context.
 Switch or parameter name expected.
Error: Could not parse commandline options.
Quitting (on error).
```

**Comment by paul-harambee** [comment]
> I would rather recommend to use a nightly build http://sumo.dlr.de/daily/sumo-msvc12extrax64-git.zip.

I will give this a go. Thanks.
