### ISSUE TITLE
Vehicles stop at minor junction till junction is free with IDM, but not with Krauss

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#4678]
We had an issue before, because vehicles stopped at longer junctions before minor links, although it was free. The workaround was to set the visibility parameter to a higher value. This solved the problem in case of Krauss till 1.0.1. Now we see the problem again even the higher visibility value does not solve the problem.
Used SUMO version: 1.0.1 + 0176-65b48fbf1c

**Comment by namdre** [comment]
please provide a minimal sample scenario

**Comment by namdre** [comment]
The braking is caused as follows:
- when committing to drive across a minor link, the vehicle should not slow down too much. Otherwise a prioritized vehicle could appear and both vehicles might be unable to avoid a collision.
- To avoid this, vehicles detect when they have to slow down for some reason while passing the minor link. In this case, they brake if they are still able to stop before the junction.
- in the sample scenario, the ego vehicle slows down a little bit due to the presence of a leader vehicle downstream. This minor slowdown is sufficient to trigger the braking logic. 

This heuristic should probably be smarter when deciding whether the slowdown is dangerous and braking must be triggered. In the example, the slowdown is less than 0.1m/s which should simply be ignored.

**Comment by levente-s** [comment]
I have a scenario showing a similar (or the same) issue, i.e. looks like a difference in behaviour at a minor link between Krauss and IDM.
I have checked the scenario for IDM and Krauss (both with default parameters) for 2 test cases:
* minor link, visibility = 100m
* major link
[idm_krauss.zip](https://github.com/eclipse/sumo/files/2900681/idm_krauss.zip)


I have chosen the simulation time as a measure, it shows the total amount of time needed by all the 500 vehicles to leave the simulation

|            | Krauss | IDM    |
|------------|--------|--------|
| major link | 1702.9 | 1609.4 |
| minor link | 1701.9 | 3239.4 |

**Comment by namdre** [comment]
Thank you. This example makes the problem very obvious.  I'll try to fix this asap.
