### ISSUE TITLE
getFollowersOnConsecutive() fails if ego laps back into previous lane

### ISSUE THREAD

**Issue by leoluecken** [eclipse/sumo#4727]
MSLane::getFollowersOnConsecutive() returns null if the ego vehicle's back laps into the previous edge allthough there is a follower on the lane previous to the previous (The same issue was present for the previous lane before the quick-fix in 042ebd99a9fed85d2a57b08372b725df99d291bf).
I don't know how to solve this in general without breaking other parts.
See failing test `complex/traci/ContextSubscriptionFilters/leadFollow/laneChangeRight`

**Comment by odajani** [comment]
Hi
We have similar issue regarding getting follower vehicle information using the getFollower() function whenever ego “host”  vehicle is crossing road junction, the getFollower() function returns (“”,-1.0) even though there is follower vehicle in sumo-gui   
But when using getLeader() the leader vehicle is always identified.  Are getFollower() and getLeader()  similar implementation?     

It would be great if this issue is fixed in next release and if it is possible to provide timing when this issue is solved ? 
Thank you for great tool
