### ISSUE TITLE
clear the conflict and make a new connection with two lanes

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#4888]
Just like the picture,
How could one clear the conflictation between the source lane and another and make a new connection with each other.
![image](https://user-images.githubusercontent.com/39317241/49688822-89b72e00-fadd-11e8-8c17-ba7256b3e746.png)
Best regards!

**Comment by namdre** [comment]
the conflict appears because the left lane already targets both lanes to the north. You can resolve this by firstremoving the connection from the left lane to right northbound lane.
If you want to keep it, do as it says in the screenshot: " hold <CTRL> while clicking to create conflicting connections.
