### ISSUE TITLE
How can I improve the simulation speed when scenario is large?

### ISSUE THREAD

**Issue by GoingMyWay** [eclipse/sumo#4979]
Hi, thank you for developing such awesome simulator. I use the whole road of a city as my scenario, however, I found the simulation is very low under such scenario in SumoGui. How can I speed up the speed? 

And also for the [OSMWebWizard](http://sumo.dlr.de/userdoc/Tutorials/OSMWebWizard.html), when the scenario is large, it takes over 1 hour to generate the data. Is there any way to improve it.

**Comment by namdre** [comment]
- webwizard speed cannot be increased at the moment. If you have already downloaded the osm file, you can speed up network import by removing unnecessary roads (e.g. road types 'track' and 'path').  
- depending on the required model accuracy you may be able to simulate at a coarser level:
  - use the default simulation step length of 1s (--step-length)
  - build network with the option --no-internal-links (reduced junction model precision)
  - run the simulation with the option --mesosim (uses a simple queuing model instead of car-folloing and lane-changing models)

 - **the most important reason for slow simulation is unrealistic traffic congestion. If the whole network is filled with mostly standing cars, the simulation will run much slower.** Observe the simulation in sumo-gui and try to determine where the jam develops and whether it is intended or unintended. See http://sumo.dlr.de/wiki/FAQ#The_simulation_has_lots_of_jams.2Fdeadlocks._What_can_I_do.3F

**Comment by GoingMyWay** [comment]
@namdre  thank you. I will try your tips.
