### ISSUE TITLE
netconvert opendrive lanes lengths mismatch

### ISSUE THREAD

**Issue by sapirbm** [eclipse/sumo#5078]
please help
when converting from opendrive to net.xml there is a mismatch in lanes lengths. probably due to junction shapes or something like that. 
i looked at issues #4331 #4913 #4812 but nothing helped.

**my goal is to have identical roads length in both opendrive and sumo.**

conversion syntax:
netconvert --opendrive-files hooder.xodr -o hooder.net.xml --opendrive.advance-stopline 0 --opendrive.internal-shapes true

for example-
length of road number 23: **opendrive**: 130.25m **net.xml**: 122.33m

i played a bit with the junctions radius and other parameters, but it helped some of the edges but hurt others.

[maps.zip](https://github.com/eclipse/sumo/files/2778844/maps.zip)

**Comment by namdre** [comment]
if you set the options
```
   --opendrive.advance-stopline 0
   --default.junctions.radius 0
   --junctions.small-radius 0
```
you will get the correct shapes. Note, that the length given in OpenDRIVE is the length of the centerline whereas Netconvert computes the edge length for each direction from the average lane centerline length. In the case of road 23 the edges will have a length of 129m and 131m.

I'm marking this as a bug because the option defaults might have to be changed for OpenDRIVE import.

**Comment by sapirbm** [comment]
@namdre thank you very much!
in addition, during the conversion from opendrive, netconvert calculates new max-speeds for junction sublanes. can you please share how these max speeds are determined?

thanks a lot!

**Comment by namdre** [comment]
The speeds are explained at http://sumo.dlr.de/wiki/Simulation/Intersections#Speed_while_passing_the_Intersection
Most likely, you will see the original OpenDRIVE lane speeds by setting --junctions.limit-turn-speed 0
