### ISSUE TITLE
vehicle  type

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5202]
I understand that the SUMO's vehicle is a point or a shape, I want to know if SUMO is a cellular automaton model. Is there any relevant literature to explain it? For the type of vehicle, I want to build a vehicle dynamics model through matlab, and then interact with traci4matlab. Can  achieve it?

**Comment by behrisch** [comment]
SUMO is not a cellular automaton, it has a space continuous model. For a documentation of the default (Krauss) model see https://sumo.dlr.de/wiki/Definition_of_Vehicles,_Vehicle_Types,_and_Routes#Default_Krauss_Model_Description

For your second question: Yes you can remote control your vehicles completely using the TraCI interface and as long as the traci4matlab client has implemented all the required functions correctly (which I cannot tell because I am neither maintaining nor using it) you approach will work. You should especially look at the function vehicle.moveToXY https://github.com/pipeacosta/traci4matlab/blob/master/%2Btraci/%2Bvehicle/moveToXY.m.
