### ISSUE TITLE
NETEDIT: splitting junction creates new edges

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#5245]
Using the current Netedit developer version, the "split junction" operation does not work anymore as expected. New edges get created instead of just retaining the points of the incoming and outgoing edges. Below the result of the operation for a simple four-leg intersection is shown. The edges in black have been added through the "split junction" operation: Every incoming edge has been linked to outgoing straight ahead.
![grafik](https://user-images.githubusercontent.com/33294728/53476233-2997ae80-3a72-11e9-9238-884c9756fd62.png)

**Comment by namdre** [comment]
This is due to #4998 and it is working as expected for all clusters I had considered so far (the idea is to undo invalid joins created by --junctions.join and save some work on reconnecting the original nodes).

I can see two ways out of this:
- add a second function 'split junction, add edges' to do this
- improve the heuristic to detect cases where new edges make no sense (because they still lead to a disconnect or some such criterion)

How was the junction with its custom edge end points created?

**Comment by m-kro** [comment]
The junction was created in Netedit in a few clicks. Honestly, I have used and appreciated the split function in the past to redo complex intersections. Before that, I had to split the incoming and outgoing edges because otherwise they would have been deleted together with the junction. Now it has become useless from my point of view.
In my opinion, this originates from two different ways of how networks are generated: Automatically create a large network without caring too much about local details vs. working on specific road geometry and topology. I would see NETEDIT as the main tool to edit networks for the second case and expect to have control over any useful net element. 

 **If you want to keep this heuristic, please make it accessable separately from the simple junction split!**

**Comment by namdre** [comment]
The typical scenario where I use split is to undo a prior join like this:
![grafik](https://user-images.githubusercontent.com/6240630/53490847-092d1b80-3a95-11e9-87df-f8f9bccd0c0b.png)
For me, this is a regular part of re-working imported OSM networks. However, I'm all in favour of preserving used functionality so I've restored the old behavior and added a new menu option.
