### ISSUE TITLE
Duarouter routing problem

### ISSUE THREAD

**Issue by aliirmak** [eclipse/sumo#5392]
New versions of duarouter are causing traffic jams in the long run.

Here is the set of steps I took to create the problem:
1) I have a flow demand file for vehicles. this is only for road traffic simulation. I generated the route file using duarouter from this demand file.
2) When I use duarouter v0.32 to generate the traffic, sumo simulator works fine with 0.32 and subsequent versions.
3) When I use duarouter v1.01, v1.10 and one of the nightly builds, after 10-20 days sumo simulator reports traffic jams, vehicles piling up. I used sumo simulator v0.32, v1.10 and one nightly build.
4) For either set of simulations, parameters are same.

So, I came to the conclusion that this is not a sumo simulator issue. duarouter is generating faulty routes that cause jams after some time.

I only tested this issue only for a particular street layout from openstreet map.

**Comment by namdre** [comment]
Please provide all input files to duarouter and sumo along with the configuration files so I can reproduce this.

**Comment by aliirmak** [comment]
i need to talk to my supervisor if i can share my files since it is an on-going research.
if that is okay, i will send the files to your email account once i get the permission.
ty!

**Comment by namdre** [comment]
If it's easier, maybe you can send me only your network and a pair of (fromEdge,toEdge) that gets a different route with the different duarouter versions

**Comment by aliirmak** [comment]
I have sent wetransfer link to your email with the subject _Duarouter routing problem #5392_. The issues start to arise when I run the simulation for +10 days.

**Comment by namdre** [comment]
After looking at your scenario, I think that it's not a matter of bad routing by the updated duarouter but rather a matter of luck that made the scenario work with the old duarouter output. I have the following recommendations.
1)  compute a traffic assignment instead of just the shortest paths which tend to cause congestion. See https://sumo.dlr.de/wiki/Demand/Dynamic_User_Assignment. I tested one-shot assignment and it worked well with your scenario
2) Recheck the layout of major intersections. As an example, consider junctions 1443088096 and 202514074. In real life (at least according to google maps) there are dedicated turning lanes which greatly improve flow. These intersections serve as a nucleus of jamming which could probably by prevented by adding these turning lanes. 
3) Recheck your traffic-to-network mapping. There are plenty of vehicles that starts at edges which are closed to passenger traffic (mostly of type "highway.service"). Either let that traffic start on other edges or change the edge permissions.
