### ISSUE TITLE
I could not open any sumocfg file, Could you help me?

### ISSUE THREAD

**Issue by fengbaozhiling1** [eclipse/sumo#5485]
When I used sumo-gui.exe to open the file of hello.sumocfg which is originally contained in tutorial/hello, It appeared an error.

Warning: Environment variable SUMO_HOME is not set, schema resolution will use slow website lookups.
Error: unable to open file 'https://sumo.dlr.de/xsd/routes_file.xsd'
 In file 'C:\Users\LM\DDDD\sumo\sumo-1.2.0\docs\tutorial\hello\data\hello.rou.xml'
 At line/column 1/0.

Quitting (on error).

I could not open any sumocfg file, Could you help me?

**Comment by m-kro** [comment]
The message already says what your problem is about: SUMO wants to do validate your sumocfg using the XML scheme contained in its installation. You have two options:

- Run SUMO with XML validation disabled, see https://sumo.dlr.de/wiki/XMLValidation how to do this
- Set the environment variable SUMO_HOME to the SUMO base path (the parent of the bin directory)

**Comment by behrisch** [comment]
Seems to be resolved. Thanks to @m-kro for answering.

**Comment by hello-hm** [comment]
> Seems to be resolved. Thanks to @m-kro for answering.

Could you tell me how you solved it
