### ISSUE TITLE
netconvert: success; sumo-gui: error invalid linkindex

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5513]
I implemented many OSM networks just fine using netconvert. However, the one uploaded below gives me problems.
The problem seems to be <junctions.join value="true"/>. 
If I set <junctions.join value="true"/> (with the corresponding distance), netconvert ends with "Success", however opening it in the Sumo-gui, gives me: Error: Invalid linkIndex '22' in connection controlled by 'joinedS_358' (Quitting on error)

If I set <junctions.join value="false"/>, netconvert ends with "Success" and the sumo-gui can load the network.
I have run the same config netconvert with many other osm-based networks, and it doesn't throw this error.
Please find the attached config files and type files to reproduce the error (large file!):
[Google drive link](https://drive.google.com/file/d/1q4fT2dw30W28aNI7-N3BhDtOaCM6N9_X/view?usp=sharing)

(I also included the osm.net.xml which fails to load in sumo-gui)

Sumo version: v1_2_0+0007-fd0ab73f27 run on Window 10.

As always, many thanks!

Lukas

**Comment by namdre** [comment]
I think the problem is caused by option `tls.uncontrolled-within`  (which is only kept to reproduce legacy networks and isn't recommended anway). 
When leaving out this option, the network is loadable.

Also, I recommend to set the value of tls.guess.threshold to a higher values because with a value of 30 almost every intersection will get a traffic light.

**Comment by ambuehll** [comment]
OK! Thanks! About the tls uncontrolled within, I disabled it because, I had weird tls with signals in the middle of the intersection, so I thought that might be caused due to this. But, I’ll enable it again.
On the treshold, agree it’s low, but I do set new (much lower and probably realistic) speeds in the type file. I am running validations against Google and Bing travel times, and if of interest, I can provide a more sophisticated type file for osm data, than is implemented by default.

Thanks for the help again!

**Comment by namdre** [comment]
The edge speeds in a net.xml file are not meant to represent travel speeds but rather speed limits.
The travel speeds are supposed to emerge from the traffic dynamics. Of course there are limits to this approach (e.g. when people systemtatically violate the speed limit in some places) but it wouldn't expect this to be necessary for lowering speeds.  One reason that speeds may be too high in the simulation could be due to mismodelled junctions (vehicles driving straight through a priority junction whereas they have to stop at an allway_stop in reality). 
If you find that speeds are too high overall you could also set a lower speedFactor in the vType definition.

I understand that adapting speed limits may be a sensible work-around if the network is so large that it cannot be fixed manually but I don't think this is a general solution when importing osm data and you may want to consider switching to the mesoscopic model if you cannot rely on microscopic dynamics for speeds anway.

If you can make a tool for validating travel times with Google/Bing public, that would be an awesome contribution.

**Comment by namdre** [comment]
Your network is also affected by #5524 so I recommend building again with an updated netconvert version.

**Comment by ambuehll** [comment]
Great answers! thanks, will do that right away. 
On the speed limit discussion. Agree very much on the micro level. On the meso level, which I successfully use, I thought vehicles will travel at max speed as long as there is no congestion. That's what I saw on a simple link level example.

**Comment by namdre** [comment]
The mesoscopic simulation also allows for other congestion effects besides jammed/free: https://sumo.dlr.de/wiki/Simulation/Meso#Further_Congestion_Effects
In addition you can model slowdown caused by intersections with different levels of detail: https://sumo.dlr.de/wiki/Simulation/Meso#Junction_Model  which helps to bring speeds on lower road classes closer to reality.
