### ISSUE TITLE
xml2csv encoding issues

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5538]
Add:
```
import sys
reload(sys)
sys.setdefaultencoding('utf8')
```
to xml2csv in order to not throw error for weird encodings.
(probably this is related to https://github.com/eclipse/sumo/issues/4004)
Should be reproducible with Python >3, and xml [here](https://drive.google.com/file/d/1K_9FeTLp7GMvQ0hcA5v40GjPfmizOuFa/view?usp=sharing).
One more detail: If applying xml2csv on this file, there are some fails for special characters, it adds a ";" which makes adds an unnecessary field (see edge id="-102173890#0", row 211 in csv).

Cheers, 
Lukas

**Comment by behrisch** [comment]
The file works here (Python 3.6.5 on Linux) but I suppose it occurs on windows only because Linux already has utf8 as default encoding. I don't think we are going to implement your solution which seems like a hack to activate a hidden function which deliberately got deleted by the python developers.

**Comment by behrisch** [comment]
An error shows up with Python 2.7.14 on Linux as well.
