### ISSUE TITLE
right-turning cars cross illegally the straight-riding bicycles at intersections

### ISSUE THREAD

**Issue by abed1856** [eclipse/sumo#5545]
The right-turning cars do not wait for cyclists who ride straight at intersections even by defing control Position and setting priority of green at trffic lights. This bug has been defined before by: 

https://github.com/eclipse/sumo/issues/4071

However, it still persists.
[SUMO_issue.zip](https://github.com/eclipse/sumo/files/3137163/SUMO_issue.zip)

**Comment by abed1856** [comment]
Simulationsschritt: 614
Verkehrsteilnehmer: NW.passenger_4
![grafik](https://user-images.githubusercontent.com/38154839/57063340-31b6d900-6cc3-11e9-9b8b-7fa9835b5fb1.png)
![grafik](https://user-images.githubusercontent.com/38154839/57063353-3b404100-6cc3-11e9-9e0b-24cf5d941a27.png)

**Comment by namdre** [comment]
The recommended work-around is to add an an incoming bicycle lane ahead of the intersection.

**Comment by abed1856** [comment]
Do you mean the stop line of bicycle lane to be ahead of the intersection?

**Comment by namdre** [comment]
No. I mean: the bug will not show up if  bicycles enter the intersection from a dedicated lane instead of a shared lane. 
Of course, the bug should still be fixed. It just might take some time until I get around to it.

**Comment by abed1856** [comment]
Hi Jakob,
Thank you very much for the response. I will try to change it to dedicated bike lane and give you my feedback too.
Best Regards

**Comment by namdre** [comment]
Invalid behavior is due to invalid custom internal junction position (contPos=7) for connection from North to West.
Semantics of internal junction are: no need to check for conflicts up to the internal junction.
If contPos is reset to -1, then turning vehicles yield to straight-going bicycles as expected.

**Comment by abed1856** [comment]
Hi Jakob,
Thank you for the answer. I tried it: when the edges are separated, it is fine; about your solution: What if you wanna define a control position at intersection in internal junction? This happens more in reality that cars come forward more near to bike lane and then stop till cyclists pass. Do you have any suggestion?

**Comment by namdre** [comment]
The problem comes from the fact that straight-going bicycles use the whole width of the lane and then their paths may intersect with the waiting position of vehicles. If you put the waiting position on a point where the cars are still going straight this can probably be avoided.
However there is still some code missing in the junction model to check for sublane-conflicts while on the intersection when vehicles are coming from the same edge and are moving to different destination edges (related to #4967)
