### ISSUE TITLE
initial pseudo route should not be written by vehroute output

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#5639]
SUMO does not select the right route in the given route set of the route file when using the meso mode.

**Comment by yunpangfloetteroed** [comment]
the files are under Bugreports\5639_route_not_correctly_selected_with_meso

**Comment by behrisch** [comment]
@yunpangfloetteroed I cannot reproduce it here. Can you please add the sumocfg.

**Comment by yunpangfloetteroed** [comment]
I added the required files in the directory "20190523" under Bugreports\5639_route_not_correctly_selected_with_meso.

**Comment by behrisch** [comment]
The problem is not sumo but the duarouter. It considers every route in the input and even a route with 0 probability in the input can be chosen in the output if the cost are low enough (which they are for such a short route). Unfortunately it does not check whether the route is valid at all. Maybe adding --repair already fixes that, I'll check. furtheremore we should modify vehroute output such that it does not include the invalid first "route" consisting of two edges only.

**Comment by yunpangfloetteroed** [comment]
I think/suggest that sumo should not write out the set of the start and end links as a route under the routeDistribution when running one-shot. It is logical that all routes in the routeDistribution should be vaild as prerequisite. Under this condition, what the current duarouter does ist right.

**Comment by behrisch** [comment]
We should still add an option to get the old behavior back.
