### ISSUE TITLE
setting viewing angle via the OSG attributes in the viewport dialog is not working

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5663]
even opening and closing the dialog changes osg zoom behavior for the worse (only resettable via the default-zoom button)

**Comment by m-kro** [comment]
I'm currently working on the view rotation. It works partially already, but the OSG camera manipulator impedes some things:
- I can use mouse drag to rotate if I set `setVerticalAxisFixed(false);`, but setting the angle directly does have no effect
- The opposite happens if I use the standard value `setVerticalAxisFixed(true);`

**Comment by namdre** [comment]
Could this be made to work by changing the properties of the manipulator temporarily (i.e. while having the dialog open)?
