### ISSUE TITLE
Meso minor tls penalty

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5751]
Is the minor tls penalty in meso also applied to nodes/junctions with degree two (e.g. where only a reduction in lane takes place)? If yes: wouldn’t it make more sense to only apply it when degree > 2? 
Thanks

**Comment by namdre** [comment]
the option --meso-minor-penalty is only applied when the vehicle travels across a 'minor' link (an lane-to-connection that has to yield to some other connection).
In a typical sumo network, a lane-drop node is not modelled with a minor connection but rather with a dead-end lane (forcing lane-change in the microscopic simulation). 
This means, there is no penalty in meso because all vehicles just use the single existing (major) connection. See also https://sumo.dlr.de/wiki/SUMO-GUI#Right_of_way
