### ISSUE TITLE
xodr2net.xml xml2xodr

### ISSUE THREAD

**Issue by xiaoyang666** [eclipse/sumo#5868]
When I use the sumo simulator, I use the xodir file to convert to a net.xml file, and then use the net.xml file to convert to xodr. The two xodr files are different. Why is this?

**Comment by namdre** [comment]
this has to do with the fact that the xodr network must be re-interpreted to match the .net.xml data format. Among other things:
* geometry is converted from a functional description (polyonmials, arcs) to a polygonal chain
* roads are split whenever lane numbers change because sumo requires constant lane numbers for each edge 

When converting back to xodr these interpretations are not reverted but re-interpreted again causing differences.

**Comment by yujiayong123** [comment]
How to use the net.xml file to convert to xodr? have script?

**Comment by xiaoyang666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by namdre** [comment]
`netconvert -s net.net.xml --opendrive-output net.xodr`

**Comment by yujiayong123** [comment]
> `netconvert -s net.net.xml --opendrive-output net.xodr`

Thank you！！！
