### ISSUE TITLE
Inconsistent handling of errors in departLane - arrivalLane and departSpeed - ArrivalSpeed

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#5874]
An invalid departLane/departSpeed generates an error in SUMO, but an invalid arrivalLane/arrivalSpeed only warnings.

**Comment by behrisch** [comment]
I do in fact consider errors in the depart attributes more severe but I am open to both variants.

**Comment by palvarezlopez** [comment]
@behrisch I think in the following possibility: An extra processing option --threat-lane-speed-configuration-as-errors (true/false). What do you mean?

**Comment by namdre** [comment]
I thought about it for a while and there is actually a reason to treat them differently:
Vehicles may reroute to a different destination after departure and setting arrivalLane=100 effectly lets them arrive on the leftmost lane regardless of how many lanes the final destination edge has (because MIN(arrivalLane, leftmostLane) is used). 
In contrast, the departure edge for a vehicle cannot be changed and thus it makes more sense to expect a correct value.

A similar argument can be made for arrivalSpeed though I'm less sure about a potential use case here. Nevertheless, I would opt for keeping things the way they are now.
