### ISSUE TITLE
traci.vehicle.rerouteTraveltime behaves differently in libsumo and traci

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#5943]
The second parameter (currentTravelTimes) did not exist in libsumo up to now and probably the behavior of updating travel times should move to the server side (for reasons of performance and easier client side implementation)

**Comment by Trashcleaner** [comment]
Do I understand correctly that `rerouteTravelTime` in libsumo does not consider current travel times on edges?

I observed that `rerouteTravelTime('veh_id', currentTravelTimes=False)` generates the same output in both traci and libsumo.

How can I make libsumo consider current travel times currently?  

Thank you, I'm trying to understand the differences in the outputs of libsumo and TraCI and make it behave exactly the same.

**Comment by namdre** [comment]
the difference between traci and libsumo is in the linked code which you can replicate with additional function calls in libsumo: 
https://github.com/eclipse/sumo/blob/31152f40ca7b8206aae717b4f8f81bdcf541a753/tools/traci/_vehicle.py#L1328-L1330

instead of doing this, consider calling 
`traci.vehicle.setRoutingMode(vehID, traci.constants.ROUTING_MODE_AGGREGATED)`
when using this, traci and libsumo will behave the same.
(see https://sumo.dlr.de/docs/Simulation/Routing.html#travel-time_values_for_routing)

**Comment by behrisch** [comment]
I propose to change the behavior of vehicle.rerouteTravelTime and basically remove the option to use current travel times

- it is slow for large networks
- it has intransparent side effects for all vehicles and further routing queries for the same vehicle

To keep at least a bit of downward compatibility we could keep the parameter and just issue a warning that it is ignored or maybe swithc the routing mode if it is set to true (this is again intransparent but at least it only affects the current vehicle).
If we really want to force some kind of update we could make MSRoutingDevice::adaptEdgeEfforts available via traci.
@namdre comments?

**Comment by namdre** [comment]
I generally agree with removing the updating side-effect.
Switching the routingMode (temporarily) seems like a good replacement for the intended effect (We would have likely done it this way, had the feature been available at the time).

The only downside is that doing routing with ROUTING_MODE_AGGREGATED for the first time, also has the potential side effect of switching on `MSRoutingEngine::initWeightUpdate` which incurs updating costs for the rest of the simulation (unless the RoutingEngine was already running anyway, i.e. due to loading a trip).

**Comment by namdre** [comment]
@behrisch The current solution brings a potential regression! In previous versions, `rerouteTraveltime` made use of the personal weight storage (`vehicle.setEffort`) to override currentTraveltimes. This is no longer the case.

I think a reasonable solution would be to apply the personal weight storage for all routing modes. What do you think?

**Comment by behrisch** [comment]
We invent a new routing mode aggregated_personal which respects the personal travel times in additon to the aggregated and is the default for reroutetraveltime
