### ISSUE TITLE
Need to create a sumo model for Regulatory Speed Advisory

### ISSUE THREAD

**Issue by shalinits** [eclipse/sumo#5972]
Scenario:I need to create a  scenario of regulatory speed advisory using sumo model. I need to add a regulatory speed of some 60km/hr for a certain distance(say for 2km) in a particular lane (lane may be one,two,three)using netedit. The vehicles need to change the speed when it comes out of the regulatory speed zone.

In the netedit application I used the variable speed sign instead of regulatory speed and given time steps.I didn't get how to add regulatory speed advisory in my scenario.
[RegulatorySpeed3.net.xml.zip](https://github.com/eclipse/sumo/files/3529555/RegulatorySpeed3.net.xml.zip)

Can I use variable speed sign inplace of regulatory speed?or how can we add regulatory speed advisory for a particular lane for a certain distance.

**Comment by namdre** [comment]
You can use variableSpeedSign by saving it to an additional file (Netedit "File->Additionals and Shapes->save") and then loading it in sumo with option -a
The variableSpeedSign always applies to the whole lane so you may need to split your network edge in order to achieve the correct start and end location.
