### ISSUE TITLE
Issue about continuous lane-change model

### ISSUE THREAD

**Issue by waterhorse1** [eclipse/sumo#5989]
I am wondering if SUMO is able to change the target lane when performing a continuous lane-change because I find that the vehicles in SUMO tend to firstly complete the lane-change when I want to test some random continuous lane-changes using sublane model. Thank you so much!

**Comment by namdre** [comment]
You can override the intenal lane-changing logic by using setLaneChangeMode: https://sumo.dlr.de/wiki/TraCI/Change_Vehicle_State#lane_change_mode_.280xb6.29

**Comment by gyq18** [comment]
It seems that SUMO complete lane change in almost a step-1s, however, we kown that in reality, it may take 4-5s to achieve lane change, so are there some methods to change this?
Besides, I have some questions about "changeLane(string, int, double)":
1. whether other cars on the target lane will slow down to make the lane-changing car complete its target successfully?
2, I don't understand that "the lane will be chosen for the given amount of time (in s)." It is my understanding that the SUMO implementation is completed in 1 second, but due to internal lane-changing logic, it may be followed by other lane changes. So we need it to stay on the target road for a period of time. I don't know whether this understanding is right.
Look forward to your reply.
