### ISSUE TITLE
How can I get the real-time flow rate passing a detector

### ISSUE THREAD

**Issue by fengbaozhiling1** [eclipse/sumo#6044]
I want to get the real-time flow rate of a setting point. How can I achieve this by traci? Should I use e1 detector?

**Comment by namdre** [comment]
If you have an e1detector at the location, you can get raw time headways by calling 
traci.inductionloop.getTimeSinceDetection (some discretization issues)
or traci.inductionloop.getVehicleData
However, computing flow is better done by averaging counts over some time period rather than using the headways.
