### ISSUE TITLE
netconvert problem from osm file to net file

### ISSUE THREAD

**Issue by riesakrisna** [eclipse/sumo#6045]
I am using sumo 1.3.1 and python 3.7 on windows. After I want to convert osm file to net file through netconvert, I get an error as follows,

C:\Users\Riesa\Documents\traf>netconvert --osm-files map.osm.xml -o test.net.xml
Warning: Please note that using ';' as list separator is deprecated.
 From 1.0 onwards, only ',' will be accepted.

I don't get any solution to solve this problem. Please help me! Thank you.

**Comment by namdre** [comment]
This is a warning not an error. What happens when you load test.net.xml in sumo-gui?

**Comment by riesakrisna** [comment]
Thank you namdre for replaying me. The problem is the test.net.xml did not create. Then, I can not run it in sumo-gui.

**Comment by namdre** [comment]
The problem may be specific to your input file. Please attach the osm file to this ticket or upload it somewhere and share the download link

**Comment by riesakrisna** [comment]
This is the link of osm file: https://drive.google.com/open?id=1UzwlA7n5glUXi_g8o23cMARkO1HdRXiI

**Comment by namdre** [comment]
I cannot reproduce this issue. When I run the command with that sumo version, the network is built as expected. Since there is no warning, the only reason why the test.net.xml is not created could be a crash of netconvert.
You could try one of the following things
- try importing other osm files to check whether problem is specifc to this input
- try performing the network import on another computer to check whether the issue is specific to your environment
- run the debug version of netconvert: https://sumo.dlr.de/daily/sumo-msvc12x64Debug-git.zip
- build sumo from source and trap the crash in a debugger: http://sumo.sourceforge.net/userdoc/Installing/Windows_Build.html#Recommended_Windows_setup

**Comment by behrisch** [comment]
No reaction, so seems to be resolved. Please reopen if problems persist,

**Comment by samirch96** [comment]
i found  the problem location , its in variables path  , i fixed it by just deleting path of netconvert which contains " ; "  u must have 2 paths at the same time , so just leave only the right one .

**Comment by juansuarezlopez** [comment]
Hi I would like to know how to build or read network files using python TRACI? or how to call netconverter with python

**Comment by behrisch** [comment]
@juansuarezlopez Please do not post questions in unrelated tickets. Either open a new one or even better use the mailing list, see https://www.eclipse.org/sumo/contact/
Regarding your question: netconvert has no TraCI interface but it can be called from inside Python using subprocess.call (like any other program).
