### ISSUE TITLE
Does duaIterate find dynamic shortest path for all loaded vehicles in the network? 

### ISSUE THREAD

**Issue by zhouhao0605** [eclipse/sumo#6064]
Dear contributors, I looked into the duaIterate code. It seems to me, it is using the input demand from trip file every time step. But strictly, the dynamic user assignment is supposed to update the route of all vehicles (loaded vehicles plus those to be inserted), right? 
I am not sure whether my research about the duaIterate is correct. Sorry if I am wrong. I think if we want to achieve the real dynamic user assignment, we need to update vehicles's origins with their real-time position. And use the updated O-D matrix to compute DUA routes for all loaded vehicles and those to be inserted in trip files.

**Comment by namdre** [comment]
duaIterate reruns the same scenario repeatedly from start to finish, updating routes and edge weights in every iteration.  Thus, the origin for each trip is always the same edge and the OD-Matrix remains unchanged.

**Comment by zhouhao0605** [comment]
Thanks Jakob. But my concern is, duaIterate only assigns routes to new vehicles from the trip file, not for all vehicles that already loaded in the network. If so, the loaded vehicles won't have shortest routes any more, tit will lead to grid lock because they might stick to their past route, instead of choosing edges that have lalrger space at at intersections.

**Comment by zhouhao0605** [comment]
![299c8da2-f692-4b2f-bb5a-02a577efc0b7](https://user-images.githubusercontent.com/46762282/64697608-33618c00-d46f-11e9-93b0-c9a72972ce50.png)
Ideally, the input_demand for each iteration should be all loaded vehicles plus demand from trip files. The above code seems to be only from the demand trip file.

**Comment by zhouhao0605** [comment]
Thank you for your prompt response Jacob.
My question is, the duaIterate seems to only consider new vehicles from trip file for each iteration. I’m expecting it to consider all vehicles, including those already running on the network, and update every vehicle’s routes in each iteration according to the dynamic traffic condition. So I suggest we should first retrieve all vehicles on the network, plus new vehicles from the trip file. And then we use duaRouter to assign shortest paths for all of them.
Do I understand it correctly? And is it feasible to do so?

Thanks,
Hao
_________________________________________

Hao Zhou, PhD Student
Department of Civil & Environmental Engineering
Georgia Insitute of Technology
Phone: (404) 345 5845 Email: zhouhao@gatech.edu<mailto:zhouhao@gatech.edu>


________________________________

**Comment by zhouhao0605** [comment]
@behrisch @namdre

**Comment by namdre** [comment]
I'm not sure what you mean by 'vehicles already loaded in the network'. What arguments are you using for your duaIterate call?

**Comment by zhouhao0605** [comment]
@namdre Hey Jacob, thanks for your comments. I want to point out: 1) there is no guarantee when you say ' the final simulation is mostly jam-free', because as the figure shows, the grid-lock will make the whole simulation get stuck. 2) I think a more serious problem is the confusion among traffic researchers. I saw multiple papers using SUMO and claim they are using dynamic traffic assignment. In fact, the strict definition of dynamic traffic assignment will require the update of every vehicle's routes at every time-step. But what duaIterate did is certainly not the same, it only assigns shortest routes for new vehicles into the network with a default 50 times. This is a common misunderstanding in multiple research reports or papers related to SUMO. I suggest you guys can declare the difference between DUA and DTA. It would help the research community.

**Comment by namdre** [comment]
Note, that the route assignment takes into account time-varying traffic conditions. This means, even though the routes are recomputed only once per vehicle for every iteration. The algorithm still reacts to jams that occur or clear later in the day and vehicle departing at different times may have different equilibrium routes. Thus I think the description in our documentation is correct.

Regarding the guarantees of a jam free resolution: In short, there is no guarantee and in practice even prolonged iterations may fail to reach equilibrium because a full gridlock does not convey useful information for the next iteration.

There are various heuristical techniques to improve convergence
- only use a fraction of the vehicles the first few iterations and scale up traffic to 100% slowly
- only run the simulation for a fraction of the full day and scale up slowly

Also, if the traffic is just too much (or the network has low throughput due to mismodelled infrastructure), there will always be a gridlock.
