### ISSUE TITLE
Simulation: invalid right-of-way in tl controlled crossing

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#6068]
Hi,
I have a test scenario with a 4 arm junction with same priority roads, where there are only one lane streets. The opposite directions are green in the same time, so it happens that there are vehicles that want to turn left from N -> E and the same greentime another vehicle right from S -> E.
In the simulation the problem occurs in such cases, when before the right turning vehicle there is a strait goer (S->N) and the left turner stops to give right of the way. It stays there after the strait goer is gone, because there is an approaching vehicle (right turner). The right turner stops at the stop position for some reason (this is not intended) and waits till the left turner ends the turn and only turns right after it...
In the attached simulation this happens first at 1:47, and after every green phase.
I use currently v1_3_1+0068-6b9b87bc7e
[crossing_with_TLS.zip](https://github.com/eclipse/sumo/files/3599574/crossing_with_TLS.zip)

**Comment by goksaderdagi** [comment]
hi, i guess that you wanted to obtain left turns at the same time from opposite directions,if it is the problem you can change the radius of the junction in the NETEDIT.

**Comment by namdre** [comment]
The wrong right-of-way rules that you are seeing, are those that apply to the exclusive left-turn phase. In this case, the left turn has precedence over the right turn and therefore this right-of-way relationship becomes encoded in the network.

Unfortunately, the current right-of-way architecture does not allow representing such a reversal in right of way from on traffic light phase to the next.
By default, right turn on red is forbidden during the conflicting exclusive left-turn phase when the plan is generated by netconvert and therefore the problem does not show up.
I'm leaving this ticket open because eventually, such a reversal is desirable as it represents actual traffic behavior better.

In your particular test network however, the presence of an exclusive left-turn phase is questionable since there is no dedicated left-turning lane. Consequently, current netconvert version would not generate such a phase.

**Comment by namdre** [comment]
Update: The problem is not exclusive to "traffic_light_right_on_red" but may also happen at a regular traffic_light when loading a custom signal plan with right-on-red / left-turn conflict.

Fortunately, there is now a solution to make this work with the help of tl-controlled internal junction links that mimic the state of of the entry link for the left turn and thereby resolve ambiguity.
