### ISSUE TITLE
win10 blocks execution of downloaded binaries sumo-gui and netedit

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6095]
block can be disabled with 2 extra clicks but this is less than obvious.
Reason may be due to missing 'distributor' information.

command line applications are not affected.

**Comment by behrisch** [comment]
Applies to the nightly zip download and also the nightly installers but not to the regular installer and is probably not easily fixed since the SmartScreen is reputation based https://stackoverflow.com/questions/48806909/how-to-pass-the-windows-defender-smartscreen-protection.@namdre Maybe just add an FAQ entry?
