### ISSUE TITLE
implement traci.simulation.loadState

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6201]
as a lightweight alternative for #2440 (probably easier to implement)

- keep the network in memory
- purge all vehicles
- reload vehicles from state file

**Comment by namdre** [comment]
user reports indicate it is working as expected (will re-open as required).

**Comment by mschrader15** [comment]
Hey @namdre, I am trying to use `traci.simulation.loadState` to quickly reset my simulation. 

When I call `loadState`, the simulation resets correctly, meaning the vehicles that were in the simulation at **X** time are put back to where they were, but it does not insert subsequent vehicles from the route file. Is that intended?

**Comment by mschrader15** [comment]
Adding the route file as an additional work great. Thanks for the tip!

**Comment by adityakarumanchi** [comment]
I get errors about missing or invalid attributes when I try to use the loadState call.

**Comment by namdre** [comment]
@adityakarumanchi Most likely your installation has outdated schema files. Scheck %SUMO_HOME%\data\xsd ($SUMO_HOME/data/xsd on Linux) and updated the SUMO_HOME variable to 1.9.2.
You can also start sumo with option `--xml-validation never` as a quick workaround).

**Comment by adityakarumanchi** [comment]
@namdre  I'm using the portable version of SUMO. All my TraCI calls, as well as the TraCI tools I imported are directly from the extracted sumo-1.9.2 folder. So the environment variable SUMO_HOME doesn't reference anything on my system. Is this a problem i.e. do I have to install SUMO to avoid this issue?

I also tried adding the `--xml-validation never` option to the `cmd` list when I call `traci.start`, alongside `-c` `mycfg.sumocfg` for instance. However, when I call loadState(), this is causing SUMO to close the connection after raising the `FatalTraCIError`.

**Comment by namdre** [comment]
Xml validation as well as several sumo python tools require the variable SUMO_HOME to point at the root of the sumo folder (the folder that contains bin, data and tools). This works fine with the portable version and no installation is needed.

A crash on loadState might be "legitimate" if the sumo version that saved the state does not match the sumo version which loads it. In this case there should be a least a warning about version mismatch.  If there is no warning, then it's a a bug and I'd be grateful for minimal inputs to reproduce the crash.

- Can you make sumo crash by calling `sumo -n your.net.xml --load-state state.xml` o
- Can you make sumo crash with only traci.start and traci.simulation.loadState ?

**Comment by adityakarumanchi** [comment]
Ok. I'm using SUMO on a work computer, where changing environment variables requires me to raise an IT request. That's why I started using the portable SUMO versions, so I can just use new versions without having to install them through IT.

Regarding the crash testing, I'm not sure if you wanted me to add the `--xml-validation` `never` option to both those cases, so I tested with and without that. Without including that option, I get the same error i.e. "attribute 'type' is not declared for element 'snapshot' " with both methods.

With that option included:

- Running sumo.exe with just the network and the load-state worked OK. A few things I noticed:
- - a lot of vehicles performed emergency stops or collided with other vehicles. This doesn't happen in the normal simulation when I just start all of them from time t=0 without any vehicles loaded from snapshots.
- - The simulation ran longer. Normally the simulation goes to 648 seconds or so, but after using load-state, the final step at which it stopped was 838.2 seconds.
- The traci method seems to load the simulation state OK. I didn't get any error codes, and I got a list of few vehicles when I printed the traci.vehicle.getIDList().But when I try to call traci.simulation.step(), it either runs for several steps before giving the `FatalTraciError`, or it runs way longer than I expected. The same simulation, with the same state file loaded using traci.loadState() kept going even after simulation time of around 1450 seconds, so I terminated it manually.

**Comment by namdre** [comment]
Your OS should permit setting of user-level environment variables without elevated user priviliges. An alternative, would be to set to use `sumo/bin/start-command-line.bat` which opens a command window and sets the necessary variables for this window.

The different behavior when loading just .net.xml and state could result from other options (i.e. if the state was saved in a sublane simulation, vehicles may register collisions if the state was then started in a non-sublane simulation).

I would like to reproduce the crash. Can you provide the net.xml and state file? (attach it to this ticket as a zip or send it directly to namdre.sumo at gmail.com)

**Comment by namdre** [comment]
Thanks. The simulation ran without collisions when started with **--lateral-resolution 8 --step-length 0.1**.
I could not reproduce the crash though. This is what I tried:

```
traci.start(['sumo',
    '-n', 'unreal_layout_custom_widths_final_pedestrians_V3.net.xml',
    '--lateral-resolution', '0.8',
    '--step-length', '0.1',
    ])


traci.load([
    '-n', 'unreal_layout_custom_widths_final_pedestrians_V3.net.xml',
    '--lateral-resolution', '0.8',
    '--step-length', '0.1',
    '--load-state', 'traci_state.xml'])

while traci.simulation.getMinExpectedNumber() > 0:
    traci.simulationStep();

traci.close()
```

When replacing the `traci.load` call with `traci.simulation.loadState('traci_state.xml')`, the simulation also ran to completion after step 662.

Can you provide either one of
- your python file with traci commands to reproduce the crash
- a traceFile of traci commands from your crash (https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands)

?

**Comment by adityakarumanchi** [comment]
I tested the two approaches you posted here [ i.e. calling `traci.start()` without the config file and just the commands you listed above, and then calling `loadState()` and advancing the simulation with `traci.simulationStep()` ]. That worked for me as well, and went till t=662 seconds.

The erroneous behavior occurs when I call `traci.start()` with the sumocfg file I shared with you, and then call `traci.loadState()`. The only difference I can see between using the sumocfg file and the approach you listed above is that the begin time and the route-file for the simulation are not specified when calling `traci.start()`. Is that a problem in that I'm assigning two different inputs to the same field?

I've also emailed you the python file I'm using. You might have to change the SUMO path etc., because I'm referring to the portable version on my PC.

**Comment by namdre** [comment]
- The non-termination issue us now tracked at https://github.com/eclipse/sumo/issues/8947
- You could potentially have triggered a crash via #8927 when using traci.load.
- I was unable to reproduce the crash with simulation.loadState.  From you report it sounded as if the crash happened only infrequently. Do you have any idea how to reproduce this reliably?
- your email did not include the python file, only the trace and a copy of the state.xml. If you resend a python file that can trigger crashing, how often should I expect to run it before it crashes?

**Comment by adityakarumanchi** [comment]
Sorry about not including the python script in the email. I sent it to you in another email earlier today. Regarding reproducing the crash reliably, no, I unfortunately don't know what changes it from non-termination to a crash. I will try to take a look at my script again, and see if I can change some things to make the crash repeatable.

**Comment by namdre** [comment]
Please try with the latest development version (https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version) since it includes the fix for the non-termination issue.

**Comment by adityakarumanchi** [comment]
Sorry about the delayed response. I tried it with the development version and it worked OK. I started traci with the sumocfg file I've been using, and then called loadState() and simulationStep(). I didn't get the non-termination issue or any crashes, but I have a fundamental question about the loadState() call - does it ignore the specifications in the sumocfg file? I'm asking because I specified an end-time in the sumocfg file I started traci with, but the simulation didn't stop there.

My intention behind using saveState() and loadState() is to create small simulation snippets from a big/long simulation. To this end, I want to modify the output of saveState() to only include a few vehicles and persons, and also set a specific end-time in the sumocfg file. So I'm hoping that when I start traci with the sumocfg and then call loadState(), the simulation will only run from the loaded state till the end-time in the sumocfg file.

**Comment by namdre** [comment]
When using traci, the **--end** option does not take effect: https://sumo.dlr.de/docs/TraCI.html#sumo_startup
However, in the latest development version you can use `traci.simulation.getEndTime()` to retrieve the value from the config file and abort accordingly.

**Comment by adityakarumanchi** [comment]
Ah, ok. Didn't think about that. Thank you for the tip, and for your help over the last 10 days.
