### ISSUE TITLE
allow position-tolerance when picking up persons while stopping at a stopping place

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6204]
@behrisch with a new option (?!) or with having applying the existing ride.stop-tolerance option?

**Comment by theDivj** [comment]
fyi
When I looked at this I found that an accessor for `ride.stop-tolerance` & relatively trivial changes to `MSTransportableControl::boardAnyWaiting ` gave me what I wanted for parkingArea boarding but in researching this I also observed:

a) It feels like tolerance should be applicable in `MSVehicle::isStoppedInRange` whether or not the stop length is `<= MIN_STOP_LENGTH`.

b) The check for a waiting vehicle in   `MSVehicleControl::getWaitingVehicle`  feels odd - the iteration stops and a vehicle is returned; if it is out of range and other tests are met;  or  if it is in range and other tests fail. This means an inappropriate vehicle may be returned even if an appropriate vehicle would have been found in a continued iteration.

ie Should `if (vehicle->isStoppedInRange(position, myStopTolerance) ||`  be an enclosing block rather than OR'd into the other tests?

(An inappropriate vehicle is 'caught' in the calling `MSPerson::MSPersonStage_Driving::proceed` & `MSContainer::MSContainerStage_Driving::proceed` which repeats the tests but it feels like there could be an issue with missing an "ANY" ride)

cheers

**Comment by behrisch** [comment]
@namdre I would use the existing option for now

**Comment by namdre** [comment]
@behrisch This implies changing the simulation behavior because the stop tolerance is 10m by default.

**Comment by namdre** [comment]
**--ride.stop-tolerance** is now applied when leaving the vehicle with a custom arrivalPos (#7258)

**Comment by namdre** [comment]
--ride.stop-tolerance is now applied when entering and leaving the vehicle regardless of stop length (#7780)

**Comment by namdre** [comment]
re question b): the other tests are for vehicles that have their departure triggered by this person. In this case the vehicle isn't even stopped.
