### ISSUE TITLE
Lane visualisation vs. vehicle class permissions

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#6207]
According to a [relatively recent commit](https://github.com/eclipse/sumo/commit/d73daba7d4d2122090627986fa1a26a2385d3813#diff-8510cf959f94ddbdc38b34df14b69c41) related to vehicle class permissions, lanes are only drawn as such if they allow the passenger vehicle class. Otherwise, rails are drawn. Why didn't you continue to check against the "meta class" SVC_ROAD_CLASSES which includes many more?

**Comment by namdre** [comment]
There are a few common cases where rail classes and non rail classes are allowed on the same lane (when importing OSM):
1 allow=all
2 allow=tram,passenger,... (highway.tram|higway.primary_link)
3 allow=tram,bus,bicycle,pedestrian (highway.tram|higway.service)
4 allow=rail,pedestrain (railway.rail|highway.path)

I find that networks are easier to understand if 4 and also 3 are rendered as rails and the passenger criterion is the simplest distinguisher. 
That recent commit only undid an experimental change from 5 days earlier. The way it is now is the way it has been since rails were renderered distinctly.

**Comment by behrisch** [comment]
I agree, especially since SVC_ROAD_CLASSES also includes pedestrian.
