### ISSUE TITLE
make step-log frequency configurable

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6377]
- new default 100
- if set, always print step-log output for first and last step

**Comment by behrisch** [comment]
If we enable this by default you would not get any output from sumo if everything goes well (not even a "success" as with the other tools). This might be the expected behavior for the average Linux user but is it also a little confusing. Since the 100 is somehow arbitrary as well, I would rather output some statistics (maybe enable --verbose by default?)

**Comment by namdre** [comment]
I think having the step-log frequency configurable would be a good thing (after all it does serve a purpose to see how quick the simulation is advancing). Also, having the default be something larger than 1 would help greatly with windows performance. In that sense an arbitrary (but configurable) 100 would be an improvement. Also you could make it so that at least one step is printed ensuring some output from the simulation.
Having verbose as default wouldn't hurt though.
