### ISSUE TITLE
VehicleType not used for actualBatteryCapacity value

### ISSUE THREAD

**Issue by tkchouaki** [eclipse/sumo#6412]
Hi,

When trying to use electric vehicles in this way :

```xml
<vType id="electricCar" vClass="evehicle" emissionClass="Energy/unknown" color="1,1,1">=
        <param key="has.battery.device" value="true"/>
        <param key="maximumBatteryCapacity" value="41000"/>
        <param key="actualBatteryCapacity" value="41000" />
        <param key="maximumPower" value="80000"/>
        <param key="vehicleMass" value="1468"/>
        <param key="frontSurfaceArea" value="5"/>
        <param key="airDragCoefficient" value="0.6"/>
        <param key="internalMomentOfInertia" value="0.01"/>
        <param key="radialDragCoefficient" value="0.5"/>
        <param key="rollDragCoefficient" value="0.01"/>
        <param key="constantPowerIntake" value="100"/>
        <param key="propulsionEfficiency" value="0.9"/>
        <param key="recuperationEfficiency" value="0.5"/>
        <param key="stoppingTreshold" value="0.1"/>
    </vType>
```

i was surprised to find that the `actualBatteryCapacity` wasn't taken into account & the vehicles were started with half of their maximum capacity.

When checking the code arounde here:
https://github.com/eclipse/sumo/blob/a131495dd1d7084fc6035d779e5f008ea422b13f/src/microsim/devices/MSDevice_Battery.cpp#L64

I found that, unlike for the other parameters of the battery, the vehicleType wasn't used for the `actualBatteryCapacity` value.

**Comment by jprk** [comment]
I find it correct: The `actualBetteryCapacity` is a private property determining battery SOC for every vehicle and I find it unrealistic to assume that every vehicle of a certain type that enters the simulation has its battery charged to the same level.

But, after all, the `actualBatteryCapacity` in `<vehicleType ...>` could be a default, with `actualBatteryCapacity` for `<vehicle ...>` taking precedence in case that it has been specified.

And maybe we can assume some statistical distribution of the initial SOC so that one does not have to specify it manually for every vehicle?

Jan

**Comment by namdre** [comment]
I suppose that the reason given by @jprk may have prompted the original implementer to treat `actualBatteryCapacity` differently. However, realism has seldomly stopped us from given more power to the user (-:

**Comment by namdre** [comment]
for statistical distribution you could now use https://sumo.dlr.de/docs/Tools/Misc.html#createvehtypedistributionspy
