### ISSUE TITLE
add webwizard checkbox to download satelite background for generated scenario

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6481]
using tileGet.py (#6279)

**Comment by angelobanse** [comment]
in `tileGet.py` it is now possible to specify the layer on which we want the decals to appear -> https://github.com/eclipse/sumo/commit/41b59f6451416c561c7e93c9fe1d75e84371f2c3

this is important in order to have the webwizard put the satellite background below everything else (especially the polygons)

**Comment by angelobanse** [comment]
#6499
