### ISSUE TITLE
Creating cyclical public transportation route with working busStops

### ISSUE THREAD

**Issue by shift-Jaegger** [eclipse/sumo#6550]
Hi, 
I'm trying to simulate a bus service and I want to make each bus to drive around the route, the problem is that I cannot find a way of stopping the bus at every cycle at the designated bus stops, but only on the first cycle.

Currently I'm using a rerouter to cycle the bus on the route, but bus stops are useless after the first cycle.

Thanks for the support!

**Comment by namdre** [comment]
There are two ways of building cyclical routes with stops
- you can get repeating stops with reroutes as long as you put the stops inside the route definition instead of the vehicle. However there is a bug when you use stop attribute 'until'. These times should be updated in every repetition of the cycle but they remain the same.
- the other way to get cyclical public transport routes is by unrolling them. Just create a route file with a route that repeats it's edges over and over and with a long list of all the stops and their depart times ('until').

**Comment by namdre** [comment]
some extra input is needed to define the time period of repeating time-based stops.

**Comment by shift-Jaegger** [comment]
Hello, my current SUMO version 1.4.0 doesn't include the attribute period, nor repeat as part of the stop command.

I would be thankful to know how can I resolve this, also, do you have any idea on more specific SUMO manuals in order to understand better this.

Thanks!
