### ISSUE TITLE
add playback functionality to the python client

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6604]
record a python script that contains all the traci calls and their arguments that were sent in a scenario

**Comment by namdre** [comment]
@behrisch a decorator on all the user-facing methods in main and the domains would should do the trick. I'm not sure whether the overhead of if-record-else-doNothing is relevant.

**Comment by namdre** [comment]
The decorator should only be added if traci.start contains the argument to switch on tracing. Instead of decorating every method explicitly in code, introspection should be used to let the domain-class decorate its user-facing methods. Some special method such as registerStepListener could be exluded via a hard-coded exclusion list.

**Comment by behrisch** [comment]
I know it is late but I just realized that the functionality we reinvent here is basically what texttest does with its python mockups https://github.com/texttest/capturemock. Since it is not that complex now and we probably do not want to introduce a dependency just for that this is just a reminder that if we feel the need to extend this we might look there first.

**Comment by namdre** [comment]
I think it wouldn't have helped much. The current amount of code needed was low and the biggest issue was to figure out what calls to trace (traced methods should not call other traced methods). This would have been necessary with capturemock as well.
