### ISSUE TITLE
What does the  function "traci.edge.getWaitingTime" return ? 

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [eclipse/sumo#6615]
I don't know what causes  the warning "vehicle '1frnln3521.970' performs emergency stop at the end of lane 'FCN23_0' because of a red traffic light (decel=-12.63, offset=3.63), time=7824063.00".
And What does the  function "traci.edge.getWaitingTime" return ? The total delay of a edge or all the vehicle' stop time on the edge?

**Comment by behrisch** [comment]
The doc string clearly indicates the meaning of the value: https://sumo.dlr.de/pydoc/traci._edge.html#EdgeDomain-getWaitingTime. I also updated the docs.

**Comment by namdre** [comment]
Emergency stopping at a red light usually happens when there is no yellow phase (should also give a warning on loading the network) or when the yellow phase is too short in relation to the vehicle speed.
Edge.getWaitingTime returns the sum of current vehicle waitingTimes. (see https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html)

**Comment by Sheldon-Zhou1997** [comment]
What about the warning " Warning: Vehicle 'frnlb2775.920' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=11628338.00."?It always happens during my simulation.

**Comment by namdre** [comment]
It depends. What car-following model are you using? For some models this indicates network or parameter issues, for other other models it is expected behavior (and the warning may be safely disabled).
