### ISSUE TITLE
How to move the vehicle along the predefined route? 

### ISSUE THREAD

**Issue by siqi95** [eclipse/sumo#6669]
Hi, 
I'm currently working on simulating some road components and using SUMO to simulate the vehicles. I'm planning to have a piece of road-side unit code to send control command to vehicles using Traci. The thing is I want to control the vehicle from my side (all the way) instead of SUMO letting the vehicle follow the route predefined in rou.xml file automatically. To explain it better, for example, I want to keep sending a command like "GO"  or "moveTo" to keep the vehicle moving along the predefined route. I'm wondering is there any way to achieve it?   Thank you very much in advance. 

Best regards,
Siqi

**Comment by namdre** [comment]
Yes. using traci with commands vehicle.moveTo or vehicle.moveToXY.
see 
https://sumo.dlr.de/docs/TraCI.html#traci_commands
https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html

**Comment by siqi95** [comment]
Hi namdre, 
However, it seems once traci.simulationStep() loads, vehicle will move automatically, do I still need that command if I want to move it manually from the beginning?

**Comment by namdre** [comment]
Yes. the move commands override sumo vehicle movements but the simulation still needs to advance in order for time to progress.

**Comment by siqi95** [comment]
So how can I tell if the vehicle is moved by the command or the simulation given that route is the same?

**Comment by namdre** [comment]
If you send a command that happens to replicate the movement that the vehicle would also have done by itself there is no discernible difference.
However, you can still know the difference because you are the one sending the move command.
Also, you could let the vehicle enter the simulation with a short route. 
Left without guidance it would soon arrive at the end of it's route and exit. As long as you are sending moveToXY command in every step you force it to stay in the simulation.
