### ISSUE TITLE
allow custom detectors for delay_based tls

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6773]

**Comment by ZoltanBaksa** [comment]
Hi Jakob,
the possibility to add custom e2 detectors is not working, because the sumo simulation crashes during initialisation, and there is no simulation log generated. Unfortunately the additional parameters I have to define are not editable and not deletable through Netedit, only by editing of network xml.

**Comment by namdre** [comment]
Please provide crashing example input

**Comment by namdre** [comment]
For reference: Currently, custom detectors can only be used when loading the tlLogic from an additional file. When trying to load them for a tlLogic that is part of the .net.xml the user-defined detectors will not be found because they are loaded at a later time.

**Comment by ZoltanBaksa** [comment]
As a workaround I could create the default program in the net as fixed time version, and put the tlLogic programs with custom detectors into an additional file, where the waut will select the extended version for the whole day. Therefore during loading the elements could be existing, and the simulation could run as expected. Am I right?

**Comment by namdre** [comment]
Yes. Also, you would not even need a waut. When loading additional programs for a traffic light, the last loaded program will be active at the start of the simulation.
