### ISSUE TITLE
Departure time is not sorted in routeSampler "flow" output (-f)

### ISSUE THREAD

**Issue by jane212** [eclipse/sumo#6776]
Hi, 

I have tried the newest routeSampler.py with flow (number/probability) output. However, the departure time in route file is not sorted, and the simulation will return the error:
`Warning: Route file should be sorted by departure time, ignoring '0_3'!`
Any ideas to fix this? Thanks!

**Comment by adel0049** [comment]
Hi,
I appreciate if you help me also, because I also faced with this warning, and SUMO is not bringing ignored vehicle into output file!!!
I used following command in config XML but still the issue not solved:
<process>
<vehroute-output.sorted value="true"/>
</process>


Tnx

**Comment by behrisch** [comment]
Is your input also from the routeSampler?

**Comment by adel0049** [comment]
tnx for imidiate response,
some part of it is similar to trci_tls in SUMO toturial folder. But i have changed it and suited for my project.

**Comment by adel0049** [comment]
I also should mention that I am using Traci and python to write my .rou.xml file and I have a "for-loop" to generate vehicles, also I tried following methods but still the issue not solved:

--random-depart-offset
--route-steps
--vehroute-output.sorted

Also I tried to give to SUMO the generated .rou.xml file  instead of generating by for loop but this also could not solve the problem.

still I have receiving following warning for the first 62 generated vehicle out of 315 total vehicle.  for more information: I have put some vehicle (8 vehicles) by fixed commands the for loop started to generate vehicles but once for loop started i see this warning in SUMO then after vehicle number 71 the problem will not show , the warning is in below:

Warning: Route file should be sorted by departure time, ignoring '9'!
.
.till
.
Warning: Route file should be sorted by departure time, ignoring '71'!


Thank you for your help

**Comment by namdre** [comment]
You can use https://sumo.dlr.de/docs/Tools/Routes.html#sort_routespy to sort your self-generated route file.

**Comment by adel0049** [comment]
> You can use https://sumo.dlr.de/docs/Tools/Routes.html#sort_routespy to sort your self-generated route file.

Thank you for the help,
I tried to find how to use this file but i could not find . It would be thankful if you help me how to use this file?

Tnx in advance

**Comment by behrisch** [comment]
Look into tools/route/ of your SUMO installation.

**Comment by adel0049** [comment]
> Look into tools/route/ of your SUMO installation.

thanks 
actually, yes I have already found it there but I do not know how to use it?

**Comment by adel0049** [comment]
> Did you try running the example command given in the documentation?

if you mean sort_routes.py , yes I opened it in pycharm. I import it to my codes  but it did not make any changes. should I changed my codes based on sort_routes.py? if needed i can email my codes to you.

Tnx for attention

**Comment by namdre** [comment]
sort_routes is meant to be run as a stand-alone tool rather than imported as a library into other python scripts. You should run it on the command line (as indicated in the documentation).

**Comment by russell021rad** [comment]
Hello 
I've got this problem in my project 
I want to run that code but I don't know where can I add this code and run 
Plz help me

**Comment by namdre** [comment]
> Hello I've got this problem in my project I want to run that code but I don't know where can I add this code and run Plz help me

See https://sumo.dlr.de/docs/Tools/index.html#how_to_use_python_tools
If you have more questions open up a new ticket

**Comment by rasoulrad021** [comment]
hello again dear @namdre 
i see this link but the proplem is,,
1,where can i add that codes? terminal?
2,how to install python tools (sortroute.py)
in my project
plz help 
tnx

**Comment by namdre** [comment]
both questions are answered by the liked documentation:
1. "Python tools are usually called from the [command line](https://sumo.dlr.de/docs/Basics/Basic_Computer_Skills.html#running_programs_from_the_command_line)."
2. "Tools can be found in the SUMO-distribution under <SUMO_HOME>/tools."
