### ISSUE TITLE
Questions in Area Simulation.

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [eclipse/sumo#6802]
I have traffic data about one area's crossings of a city. I want to simulate all crossings in this area by one Sumo project,but I only know each crossing's flow to every direction. Must I calculate every route's flow and every edge in these routes? If I do this,it's really a hard work for me to calculate thousands of route and input them to xml files.What should I do? Thank you!

**Comment by namdre** [comment]
you could model the traffic at each intersection in isolation but you could also use routeSampler to build a consistent demand model for the whole city: https://sumo.dlr.de/docs/Tools/Turns.html#routesamplerpy (use the latest development version of this tool because it is much better than the 1.5 release).

**Comment by Sheldon-Zhou1997** [comment]
![QQ截图20200320132845](https://user-images.githubusercontent.com/52645665/77168203-6063bb00-6af2-11ea-98f1-b0e6e880d697.png)
![QQ截图20200320132912](https://user-images.githubusercontent.com/52645665/77168205-62c61500-6af2-11ea-8e78-c32e047bffed.png)

**Comment by Sheldon-Zhou1997** [comment]
What does this error mean and how to solve it?
I want to use jtrouter to get all routes' flow.
I've installed sumo1.15.

**Comment by namdre** [comment]
the edgeRelation format is not yet supported in 1.5.0 (the current documentation reflects the current development version, available at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version
I recommend using routeSampler instead of jtcrouter because jtcrouter (like jtrrouter) is known to created implausible routes.
