### ISSUE TITLE
weights.random-factor per vehicle randomization

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#6808]
Very similar to #1353 (duarouter).
Automatic routing: From the [documentation](https://sumo.dlr.de/docs/Demand/Automatic_Routing.html) it is currently unclear if an edge gets one single weight or if gets a weight per vehicle. It would make sense if this were a per vehicle randomization as well.

**Comment by namdre** [comment]
- does every edge get a single weight? : no.
- does every vehicle get a single weight per edge? : no
- every time a vehicle requests the weight of an edge the random factor is determined anew.
I'm not sure how to make this more plain in the documentation because it already says
"This randomization is performed every time an edge weight is used so the same vehicle could select a different route when rerouted on different time steps."

**Comment by ambuehll** [comment]
OK. thanks. One last question: 
if rerouting is synchronized, does that mean that the edge random factor is determined once for all vehicles being re-routed in that time step? Or that still every vehicle looks up the weight separately?

**Comment by namdre** [comment]
randomization is still done separately. The synchronized routing is mostly done for better parallelization (when all vehicles reroute at the same time it's easier to distribute the work onto multiple threads).

**Comment by JayNyce** [comment]
Can I use a script to access weight.random-factor and alter?

**Comment by namdre** [comment]
> Can I use a script to access weight.random-factor and alter?

If you use a script to call sumo you can use a different factor and you can also use another random seed (**--seed**) to change the randomization
