### ISSUE TITLE
Some questions about parallel simulation performance and development plan

### ISSUE THREAD

**Issue by ykwd** [eclipse/sumo#6809]
Dear developers,

We are really enjoying using SUMO, and are currently trying to parallelize it.

I have noticed that SUMO has begun parallelization since 2018 (https://github.com/eclipse/sumo/issues/4767). So I made some benchmarks for branch v1_3_1. The whole simulation takes hours. Surprisingly, the 8-thread parallel execution is even slightly slower than 1-thread sequential execution, on a 16-core server. And I use htop command to check the cpu utilization, which shows that except one thread, the cpu utilization for the other 7 threads are only about 5%. So I wonder is this the normal situation or not?

And does SUMO development team still have interest on parallelization? If yes what is the schedule?

**Comment by namdre** [comment]
We are aware of the issue and have plans to work on parallelization this year.
- not all parts of the simulation loop are running in parallel (lane-change code as well as some computationally expensive outputs are still running on a single thread)
- our threadpool implementation has a very high overhead that eats up our parallelization gains. We need to swap it out for something faster
- there is a unknown factor that affects parallelization performance because I was able to measure slight gains on one machine and decreases in performance on another machine.

**Comment by ykwd** [comment]
Thanks very much for your answer!
