### ISSUE TITLE
How can I prevent lane changing?

### ISSUE THREAD

**Issue by jvtes1** [eclipse/sumo#6871]
Hello guys,

In my simulation, I have two lanes in the same direction. One of them is controlled by a traffic sign to whoever wants to turn left. The other lane, on the right side, has free flow for those who are going straight.

I see during the simulation that some vehicles that should turn left are changing to the right lane instead of waiting in the left lane. And so they end up jamming the right lane, which cannot happen. (picture below)

So what I want is to prevent those vehicles (or all vehicles in the simulation, whichever is easier) from changing lanes.

I have seen some people saying that I can only solve this by running the simulation by TraCI and modifying the command setLaneChangeMode and others saying that I can just add some parameters to the vType vehicles such as laneChangeModel, lcCooperative etc.

I was able to run the simulation by TraCI, but I didn't see any effect on the setLaneChangeMode command (picture below).
I also tried to add the parameters to the vType classes, but didnt see any effect as well. (picture below)

Can you please help me?

![image](https://user-images.githubusercontent.com/63251643/78594064-036c4280-781e-11ea-897a-3c03e8b4c16c.png)
![image](https://user-images.githubusercontent.com/63251643/78593801-95278000-781d-11ea-8d35-49b4f6b82ef7.png)
![image](https://user-images.githubusercontent.com/63251643/78594277-5ba34480-781e-11ea-92c8-e16cb1c798f4.png)

**Comment by m-kro** [comment]
There are several things:

- The TraCI command you cited requires an existing vehicle ID and will effect exactly one vehicle at a time. There are more commands (e.g. traci.vehicle.changeLane) related to lane changing with which you could eventually resolve your problem (or just move it upstream...?).
- You might as well try to parametrize the [lane changing model](https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#lane-changing_models) to focus more on strategic and collaborative lane changing and less on speed gains.
- Check whether you can realistically achieve your objective at all: is your turning below saturation (outflow/inflow >= 1)? Is the approach long enough to do lane changes or are there intersections upstream?
- There are some more modeling tricks. You might add short 2 single lane edges instead of a 2 lane carriageway more upstream to enforce earlier lane changing.

**Comment by jvtes1** [comment]
> There are several things:
> 
> * The TraCI command you cited requires an existing vehicle ID and will effect exactly one vehicle at a time. There are more commands (e.g. traci.vehicle.changeLane) related to lane changing with which you could eventually resolve your problem (or just move it upstream...?).
> * You might as well try to parametrize the [lane changing model](https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#lane-changing_models) to focus more on strategic and collaborative lane changing and less on speed gains.
> * Check whether you can realistically achieve your objective at all: is your turning below saturation (outflow/inflow >= 1)? Is the approach long enough to do lane changes or are there intersections upstream?
> * There are some more modeling tricks. You might insert two short  single lane edges instead of a two-lane carriageway more upstream to enforce earlier lane changing.

Thanks for your help!
I stopped freaking out about the command codes and was able to solve it just by re-modeling the network. As you suggested, I split the road in two sepparated lanes and reallocated the inflow volume to a further point.
