### ISSUE TITLE
adaptive traffic light control

### ISSUE THREAD

**Issue by albertcruzeyork** [eclipse/sumo#6889]
i usually use netEdit to set a traffic light 'actuated' to get a adaptive traffic light. How can i do this by using a python script?

**Comment by namdre** [comment]
When importing the network (i.e. from OSM) you can set option **--tls.default-type actuated**.
To change an existing network you can do
```
netconvert -s old.net.xml --plain-output-prefix plain
netconvert -e plain.edg.xml -n plain.nod.xml -x plain.con.xml --tls.default-type actuated -o new.net.xml
```

**Comment by albertcruzeyork** [comment]
as you've said, all the traffic light in the net will be actuated. how to set a specific traffic light actuated?

**Comment by namdre** [comment]
Using python you can modify the attribute 'tlType' in the plain.nod.xml file for selected nodes before re-assembling with netconvert. See https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#modifying_node_positions_with_the_help_of_sumolib

**Comment by albertcruzeyork** [comment]
Thanks! But why it doesn't have the attribute 'tlType' in 'plain.nod.xml'?

**Comment by namdre** [comment]
The information would be redundant because the file plain.tll.xml already contains the information about the traffic light type. Also, the current approach makes it possible to re-assign the type globally as described in my first comment (If the tlType is set it .nod.xml this overrides the option **--tls.default-type**).
