### ISSUE TITLE
Problem using plot_net_dump.py

### ISSUE THREAD

**Issue by jvtes1** [eclipse/sumo#6900]
Hey guys,

I am trying to run the plot_net_dump.py using the following code:

python plot_net_dump.py -v -n GV.net.xml --xticks 7000,14001,2000,16 --yticks 9000,160001,1000,16 --measures traveltime,traveltime --xlabel [m] --ylabel [m] --default-width 1 -i rawdump.xml --xlim 7000,14000 --ylim 9000,16000 --default-width .5 --default-color #606060 --min-color-value -1000 --max-color-value 1000 --max-width-value 1000 --min-width-value -1000 --max-width 3 --min-width .5 --colormap #0:#0000c0,.25:#404080,.5:#808080,.75:#804040,1:#c00000 -o abc.png

Everytime the console will print:

Reading network from 'GV.net.xml'
Reading colors from 'rawdump.xml'
Reading widths from 'rawdump.xml'

And that's it. I have no error message or anything else. Also no .png file is created. I added a picture below.

I've tried replacing the rawdump.xml with sumotrace.xml but it goes the same way. I saw people saying that this might be a bug from the Python 3 so I have installed Python 2.7 and tried running with "py -2" in the beginning of the code, but the same happens.

I wonder if there's any other way to specify the formatting parameters such as colors, widths... I guess the rawdump.xml file is supposed to contain those parameters and I would just execute the plot_net_dump command and import rawdump, but it does not work.

Can somebody help? Thanks

![image](https://user-images.githubusercontent.com/63251643/79394575-331df780-7f4e-11ea-8b95-086a1515f8f4.png)

**Comment by vxid** [comment]
Interesting, I was about to open a separate issue with exactly the same issue.
Using Linux and SUMO 1.5.0

**Comment by namdre** [comment]
Our nightly tests for this tool seem to be running ok (inputs at https://github.com/eclipse/sumo/tree/master/tests/tools/visualisation/plot_net_dump). 
You might want to reduce parameters to figure out which one is causing the problem.

However, I'm never using the tool because SUMO-GUI is very flexible in coloring edges by a given attribute, by traffic data as well as user-specified data and can also do edge-width scaling (a bit less flexible though). 
Also, SUMO-GUI can show a color legend and create screenshots as raster and vector graphics.
See https://sumo.dlr.de/docs/SUMO-GUI.html#visualizing_edge-related_data

**Comment by vxid** [comment]
@namdre Thank you for the quick reply. It turns out that I had left out the `-o` flag (since I only wanted visualization without saving the figure). Adding the flag makes the program work as expected, but maybe having a warning in case the output is not specified would be nice.
Thank you for the SUMO-GUI reference as well, I did not know it could do that.

**Comment by Boudadits13** [comment]
can anyone give me an exemple of project to test this tool ?

**Comment by namdre** [comment]
> can anyone give me an exemple of project to test this tool ?

https://sumo.dlr.de/extractTest.php?path=tools/visualization/plot_net_dump/plain
