### ISSUE TITLE
Failing assertion 'entryTimestep < leaveTimestep'

### ISSUE THREAD

**Issue by xxArbiter** [eclipse/sumo#6919]
Hi. We are testing a simple simulation scenario with a single intersection, where each approach has a single lane. During the simulation, it will occasionally throughout an error:
`(pid=8541) sumo-gui: /build/sumo-pPezc5/sumo-1.5.0+dfsg1/src/microsim/output/MSInductLoop.cpp:269: virtual void MSInductLoop::leaveDetectorByMove(SUMOTrafficObject&, double): Assertion `entryTimestep < leaveTimestep' failed.`

We are using Traci to control the traffic light, but I don't think this is the issue. Also, we are using multi-processing to train the traffic light controller, but processings should run their simulations separately. So I have no idea why would this error occur. Can you help me with this? Thanks!

**Comment by namdre** [comment]
- can you reproduce this with 1.5 / latest development version? 
- are you able to reproduce this without traci?
- if you need traci, can you figure out which traci commands this issue depends on?

**Comment by xxArbiter** [comment]
Hi, thank you for your reply.

We are using the UCBerkley flow. It seems like it uses a certain version of the sumo. And the flow uses the Traci.

**Comment by namdre** [comment]
The failing assertion has since been removed. Normally, you should not see this unless you have build sumo for debugging (which is much slower and not a good idea for RL). The release mode does not use assertions.

- What is the output of calling `sumo --version` ?
- what is your operating system?
- if you have any output files that were created by sumo while running flow, what are the contents of the file header (the big xml-comment at the top of the file)?

The best idea would be to use an upgraded version of sumo. However, the flow docs warn that there is an incompatibility. That warning itself might be outdated but you would have to ask the flow devs about that.

**Comment by namdre** [comment]
closing for lack of feedback.
