### ISSUE TITLE
Policy on adding new TraCI constants

### ISSUE THREAD

**Issue by schwamborn** [eclipse/sumo#6940]
What is the general consensus on adding new TraCI constants to `src/libsumo/TraCIConstants.h`?

Let's say I have an issue where adding, e.g., `VAR_TOC_STATE` as variable ID (to retrieve the ToC state of a vehicle) would be very convenient. However, you could argue that adding this constant would actually pollute the constants space as the ToC state could also just be retrieved via `VAR_PARAMETER` and key "device.toc.state". The issue with the latter, however, is that the TraCI reply message does not include this key "device.toc.state" (AFAIK), leading to an ambiguous `VAR_PARAMETER` reply value. Or am I missing something? @namdre @behrisch

**Comment by behrisch** [comment]
Currently there is no general policy. The number of ids is limited so it is good to think twice but please don't imit yourself too much. Most of the time it is not important that the answer to a parameter request does not contain the key because you know what you asked for. This is different of course if you are doing subscriptions, here a new constant is more or less mandatory. So if you need a subscription or have otherwise a decoupled setup where the receiver of the answer did not ask the question, then please add a new constant.
