### ISSUE TITLE
Enhancement: show geo position of startPos and/or stopPos in inspection mode for bus lanes

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#6943]
In most real world use cases I was involved before the place of the bus stop is described with geo position of the bus stop sign (in SUMO the endPos) and the capacity as number of specific bus types, (can be transformed to length)

**Comment by namdre** [comment]
Please describe the use case in more detail. 
- To find out a coordinate you can place the mouse on the position and looking at the coordinate in the status bar (or RMC->copy cursor geo-position to clipboard)
- coordinate lookup works by placing a poi at a known geo-coordinates

**Comment by ZoltanBaksa** [comment]
I would like to see the geo position similar as in case of polygons and at pois.
Also it would be useful to be able to define the busStop with geo coordinates similar to polygons with attribute "geo". In this case the combinations could be endPos and length or startPos and endPos

**Comment by ZoltanBaksa** [comment]
A long term enhancement could be to support GTFS format which is a standardized description format for public transportation systems. See description here: https://developers.google.com/transit/gtfs but this could be part of open mobility wg tasks.

**Comment by namdre** [comment]
I'm not sure about the best way to accomplish this consistently. All infrastructure positions could potentially benefit from being defined via geo-coordinates. If such input methods are added they must avoid cluttering the screen for those users that don't need the extra UI widgets.
Maybe this really should be solved via tooling outside nededit because users that have this kind of data typically have lots of data and should not be bothered to add it manually.

Also, see ongoing work at #4596

**Comment by ZoltanBaksa** [comment]
I can agree, such work means a lot of data in case of city simulations.
Where I have had problem was following process:
- I download a map part from OSM, since the size of the map is bigger than webWizard could handle at once, I have an own downloader script, which tears the area automatically into handleable parts
- I use netconvert to join these parts and remove some typically not needed street types, and export public transportation, parking and road sign information
- I use the polyconvert to gather all polygon information for later usage
- I download satellite tiles, create a decal file for backgrounding
- Afterwards comes the manual part, where I adjust the network elements (streets, junctions, connections, zippers, etc.) according to the satellite background.
- When that part is more or less ok, I have to adapt the public transportation lines to the adjusted network, because the original edges in routes, and the lanes and positions in stop definitions usually not usable.
- The last part is to define schedules for each transport line, usually form available sources (GTFS, manually created not standardised formats)

The only way I could do the correction so far was to convert the original PT exports to geo referred data (possible data loss), change them somehow outside netedit, and at routes using tracemapper and map-matching for stop positions, redefine them.
In some cases the recreated route contains wrong ways, because the trace points are near to opposite direction edges, or not enough dens to cover all edges in-between. Bus stops are missing, or placed to the opposite direction or to a wrong lane, if the geo reference is not accurate. Reviewing everything in netedit is not easy, since the visually overlapping routes make hard to have an overview.

In case of public transport systems where GTFS data is not available, I could imagine a special poly line type with additional PT related attributes, which is geo defined, which could represent the routes, and in the same manner a special poi type for stop definitions. These could replace the exported data produced by netconvert at my 2nd step. These could be handled as separate input format in netedit to not overload the other gui elements, and then the tracemapper or the map-matching for stops would have better results.

**Comment by namdre** [comment]
What exactly causes the original osm pt-route and pt-stop information to become unusable? The OSM routes do have the big advantage of referencing the actual network elements which avoids typical map-matching issues.

On a related note, osmGet already supports downloading an area from multiple parts. What features were missing to make it suitable for your use case?

**Comment by ZoltanBaksa** [comment]
The mismatch comes from the changes I have to make during the adjusting work. During my adjustments of the network I try to create a really detailed road structure, I insert intermediate junctions, because for example the bus lane restriction is not that long as the original lane, or I have to create sections with more or less lanes as before, so the original edge sequence in the routes will have missing elements, or would refer to not existing edges.

When I started to work on these scenarios, the webWizard had some issues, so I had to create my own simplified version. Since I usually create demand from real world data, I'm not using the webWizard's scenario builder functionality.

**Comment by namdre** [comment]
I think there should be some way to salvage the OSM pt-route information. Splitting edges still keeps the original edge id for the first part of the split so the original edge sequence can still be used as waypoints (via) to recreate the original route.
Even if the original edge id somehow gets lots, the ids of the split parts still carries enough information to reconstruct the route. I think this would be preferable to the geo-translation-and-map-matching-step. 

Right now, ptlines2flows.py already uses osm route edges as vias which makes it robust against split edges. Maybe it would help to add more reconstruction features (i.e. translating missing edges to edges that have the same prefix and a split-suffix).

Another solution could be to load the pt route file (generated by ptlines2flows for the original network) into netedit so it can be kept up-to-date when fixing the network.

Possibly the gtfs-import script (#4596 ) could hook into the osm routes by matching the transport line references or the list of osm stop names rather than doing the map-matching from scratch.

**Comment by ZoltanBaksa** [comment]
It sounds like a possible solution plan :)

**Comment by namdre** [comment]
There is currently some ongoing work to use ptline-output imported from osm together with gtfs-import. I'm closing this issue as won't-fix because matching lots of geo-coordinates is better handled outside netedit.
