### ISSUE TITLE
 TraCI Function setProgramLogic() Crashes the GUI Simulation

### ISSUE THREAD

**Issue by zhong-byte** [eclipse/sumo#6975]
The GUI simulation crashed at the simulation time step where the TLS logic was updated.

for idx, pTime in enumerate(spatList):
    phaseState = stateList[idx]
    traciPhase = traci.trafficlight.Phase(duration=pTime, state=phaseState, minDur=3, maxDur=3, next=())

    phaseLogic.append(traciPhase)

I used traci.trafficlight.setProgramLogic() to set the traffic light controller (TLS) plan during simulation.  The function can be run without error using command line sumo, but it crashes the sumo-gui simulation. I check the "full-output" and confirmed that the TSL plan did get changed as specified.
But I still want to visually confirm the TSL plan and the repose of the traffic. Below is the python code I ran. Thanks a lots!

spatList = [28,2,1,20,10,7] 
stateList = ['rrrrGGGGrrr', 'rrrryyyyrrr', 'rrrrrrrrrrr', 'rrrGGrrGGG', 'rrrGGrryyy', 'rrrGGrrrrr']
phaseLogic = []
tls_input = traci.trafficlight.Logic(programID='2117', type=0, currentPhaseIndex=0,                                          phases=tuple(phaseLogic), subParameter=None)
    traci.trafficlight.setProgramLogic('2117', tls_input)

**Comment by namdre** [comment]
You current code would not work because you are setting an empty phase list. Also, the list must contain Phase objects. See: https://github.com/eclipse/sumo/blob/6165e976c0e63c7cfaf7188b1c8953a9b0e856a4/tests/complex/traci/trafficlight/trafficlight/runner.py#L52-L59

**Comment by behrisch** [comment]
@namdre It should not crash anyway?

**Comment by namdre** [comment]
It throws a TraCIException as expected

**Comment by garyzhong86** [comment]
update: I use the new code sample but the sumo-gui still crashes, when the GUI zoomed to the level where the traffic light bars are visible.  To sum up
- GUI( traffic light bars visible) - **crashed**
- GUI (without traffic light bars being visible) - **no crash**
- sumo command line - **no crash** 


The output file for the status sate shows the traffic light logic has been updated. The traffic light status matches the input when I extract the traffic light every simulation time step using getCompleteRedYellowGreenDefinition()

But I want to know if the simulation result still valid since I cannot visually verify the traffic lights and traffic.
The error message I got when the exception was thrown

Traceback (most recent call last):
  File "C:/Projects/sumoSim/traciSignall.py", line 194, in <module>
    traci.simulationStep() 
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\main.py", line 165, in simulationStep
    return _connections[""].simulationStep(step)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 319, in simulationStep
    result = self._sendExact()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 98, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO

the revised code for updating traffic light
`while ts <= totalTimeStep:
    traci.simulationStep()
    if (ts == 230):
        phases = []
        phases.append(traci.trafficlight.Phase(15, "rrrrGGGGrrr", 0, 0, [1,2,3], "setViaComplete"))
        phases.append(traci.trafficlight.Phase(2, "rrrryyyyrrr", 0, 0))
        phases.append(traci.trafficlight.Phase(7, "rrrrrrrrGGG", 0, 0))
        phases.append(traci.trafficlight.Phase(11, "rrrGGrrGGG", 0, 0))
        phases.append(traci.trafficlight.Phase(5, "rrrrrrrrGGy", 0, 0))
        phases.append(traci.trafficlight.Phase(6, "rrrrrrrrGGr", 0, 0))
        phases.append(traci.trafficlight.Phase(8, "GGGGrrrrGGr", 0, 0))
        phases.append(traci.trafficlight.Phase(2, "yyyyrrrryyr", 0, 0))
        phases.append(traci.trafficlight.Phase(1, "rrrrrrrrrrr", 0, 0))
        logic = traci.trafficlight.Logic("2117", 0, 0, phases)
        traci.trafficlight.setCompleteRedYellowGreenDefinition('2117', logic)
    tls_origin = traci.trafficlight.getCompleteRedYellowGreenDefinition('2117')
traci.close()`

**Comment by behrisch** [comment]
Can you send your scenario?

**Comment by garyzhong86** [comment]
I created a repo for the scenario.  I attempted to change the tlLogic of '2117' during the simulation via TraCI.
https://github.com/garyzhong86/traci-tl-issue

**Comment by namdre** [comment]
Example script runs successfully when using latest sumo-dev version.
