### ISSUE TITLE
setRoute():Route replacement failed

### ISSUE THREAD

**Issue by tanghui0102** [eclipse/sumo#6996]
Hello.
I encountered a problem, can someone please give me one hand?Thank U.
The car has its own route in *.rou.xml.
When I setRoute() for this car via program:
`traci.vehicle.setRoute('1', ['33.0.00', '-39.0.00', '-29.0.00'])`

An error occurred below:
`Traceback (most recent call last):
  File "client2.py", line 42, in <module>
    traci.vehicle.setRoute('1', ['33.0.00', '-39.0.00', '-29.0.00'])
  File "D:\Program Files (x86)\Eclipse\Sumo\tools\traci\_vehicle.py", line 1214, in setRoute
    self._connection._sendExact()
  File "D:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 108, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Route replacement failed for 1`

From sumo-gui I can see that the car is driving along the revised route, but as soon as it reaches the first intersection(Preparing to turn), it will go wrong.

**Comment by behrisch** [comment]
There may be different reasons for this to fail. Please have a look at the log in sumo-gui whether additional messages show up. Most likely the vehicle is not on or right before the first edge of the new route when it gets the rerouting command.

**Comment by 0102TH** [comment]
Yes, sumo-gui has show logs like that:
![image](https://user-images.githubusercontent.com/47203090/81360347-2c7a3e80-910e-11ea-88a6-b4fd5996fca6.png)

this is the route file about vehicle 1:
![image](https://user-images.githubusercontent.com/47203090/81360472-811db980-910e-11ea-9e9f-32c8846079e2.png)

I don't understand what the "No connection between edge 33.0.00 and edge 33.0.00" means.

**Comment by behrisch** [comment]
Where is the vehicle when you send the rerouting command? Is it still on 33.0.00 and is it close to the end of the edge?

**Comment by 0102TH** [comment]
@behrisch 
It is at the beginning of the edge when the rerouting command works.
The .rou.xml file defines the route of the vehicle indicated by blue line.
![( $%L@2E1I4L 5Q_F1JJD01](https://user-images.githubusercontent.com/47203090/81465115-18137000-91fa-11ea-83d1-1ba14ba38a82.png)
the command defines the route indicated by yellow line.
![image](https://user-images.githubusercontent.com/47203090/81465181-97a13f00-91fa-11ea-8d76-9e265b7f9fad.png)
We can see that the vehicle obeyed the command order ,made the left turn.But made a mistake when the turn was about to succeed.
The error message is as follows
![image](https://user-images.githubusercontent.com/47203090/81465223-0088b700-91fb-11ea-81fe-00ba39558aa2.png)

**Comment by behrisch** [comment]
If your image shows the situation when the command fails, you should not give the 33.0.00 edge in the new route because the vehicle has already left that edge.

**Comment by 0102TH** [comment]
I saw the info
![image](https://user-images.githubusercontent.com/47203090/81517912-f687c500-936e-11ea-8288-36edb02165e2.png)
and I'm trying other setup methods.

**Comment by 0102TH** [comment]
[A vehicle cannot reach its target or takes a circuitous route. Why?](https://sumo.dlr.de/docs/FAQ.html#a_vehicle_cannot_reach_its_target_or_takes_a_circuitous_route_why)
Unexpected routes are often caused by invalid lane-to-lane connections or vClass-restrictions. Even if there are some lanes on every edge that permit the vehicle, they may not be connected. If the vehicle has the default type, it will ignore access restrictions and travel on all lanes. The netcheck tool can be used to visualize connectivity from a starting edge and to discover missing connections. It may be necessary to delete some detour edges from the network to discover the relevant connectivity boundaries.
To investigate connectivity SUMO-GUI can be made to show lane-to-lane connections when customizing the visualization options for junctions. To investigate lane-permission issues, the menu option Edit->Select lanes which allow... can be used for visualizing selected permissions.
No cause found

**Comment by behrisch** [comment]
> I saw the info ...

The statement there is in general true but if your vehicle is already on the junction you should give the next edge as starting point. Furthermore I am not sure about your setup. If the vehicle gets a new route the rerouting comand did succed. Do you send multiple rerouting commands to the vehicle?

**Comment by tanghui0102** [comment]
I  sent one rerouting command.
If the first edgeId in  edgeList  is not the vehicle's place at the moment, sumo-gui would be go wrong at once.

**Comment by behrisch** [comment]
OK, maybe I am a little slow but let me just repeat what I understood about your setup. You have a car (the red one), which has an initial route where it should turn right (the blue line). You send a rerouting command at the very beginning and the vehicle apparently changes the route, because it starts to turn left (orange line). But then all of a sudden (without another rerouting command) the error shows up? Are there any other rerouters or routing devices for the vehicle involved?

**Comment by tanghui0102** [comment]
Yes, what you understood is raight.
The initial route is in rou.xml
![image](https://user-images.githubusercontent.com/47203090/81760333-835e8a00-94f9-11ea-831a-9d2b6c1317fc.png)

The only  rerouting command here
![image](https://user-images.githubusercontent.com/47203090/81760408-aee17480-94f9-11ea-843e-9f46b6e2a2c1.png)

And if the first edgeID is not '33.0.00' in rerouting command,the sumo-gui will go wrong at once when run it

**Comment by behrisch** [comment]
This is a different initial route and also a different rerouting command than in your initial report. Can you maybe send your network and code (attach it in a zip to this ticket) so that I can try to reproduce it locally?

**Comment by tanghui0102** [comment]
Thank U.

[TestTraciFunc.zip](https://github.com/eclipse/sumo/files/4631888/TestTraciFunc.zip)

**Comment by tanghui0102** [comment]
`traci.vehicle.setRoute('1', ['33.0.00', '31.0.00', '-29.0.00', '-0.0.00'])`
`print(traci.vehicle.getRoute("1"))`

Output below:
![image](https://user-images.githubusercontent.com/47203090/82005893-2dc0e380-9699-11ea-8a64-41952a39c5ce.png)

But it still goes wrong like before.

**Comment by tanghui0102** [comment]
Hello.I have to say that there is a miracle.
Before, when the ego_vehicle about to cross the first intersection, it goes wrong like no connection between edge... and edge....
And via printing the rerouting result,it showed the rerouting command worked.

Just now,I add a try and except function into command, then run the sumo-gui.Although the gui prints warning informations:no connections between edge... and eege....
![image](https://user-images.githubusercontent.com/47203090/82008233-b0986d00-969e-11ea-9108-2abf76a73591.png)
But the sumo-gui can run normally not to stop running like before.
`            try:
                traci.vehicle.setRoute('1', ['33.0.00', '31.0.00', '-29.0.00', '-0.0.00'])
                traci.vehicle.rerouteEffort("1")
                print(traci.vehicle.rerouteEffort("1"))

            except:
                pass`
In the end, The ego_vehicle run according to the new rerouting command.And after running the set path, it disappeared automatically
