### ISSUE TITLE
netconvert ignoring --tls.join false

### ISSUE THREAD

**Issue by Luiscri** [eclipse/sumo#7000]
I'm trying to generate a new tls file for my network. The process I'm following was suggested in [this](https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#improving_generated_programs_with_knowledge_about_traffic_demand) section of the documentation:

```
$ ~/sumo/bin/netconvert -s madrid-central-patched-diffs.net.xml --plain-output-prefix plain
$ ~/sumo/bin/netconvert -e plain.edg.xml -n plain.nod.xml -x plain.con.xml -o updated.net.xml --ignore-errors.edge-type --tls.discard-simple --tls.default-type actuated --tls.join false
```

As far as I have understood, this process is intented to separate the network in components, ignore the tll one away and create a new one with netconvert. However, although the `--tls.join` option is set to false by default, and I even explicitly declared it to false to be sure, netconvert keeps on joining near traffic lights into a same cycle. I even tried using the option `--tls.join-dist 5` to reduce the join distance, with it neither worked.

Just to clarify, an example of this is the traffic light with ID `joinedS_5` which can be found at the right of the map.

I'm using the last version of sumo cloned this morning from GitHub.

[madrid-central-patched-diffs.net.zip](https://github.com/eclipse/sumo/files/4593057/madrid-central-patched-diffs.net.zip)

**Comment by namdre** [comment]
The commands are intended to change the signal type to 'actuated' and  supply the green phases with minDur- and maxDur-boundaries.
However, they cannot undo joined traffic lights because that information is included in the file plain.nod.xml (node attribute 'tl').

If you wish to separate joined controllers you need to remove the 'tl' attribute from all nodes before re-assembling the network.
Note, that some intersections may work badly if uncoordinated controllers are in close proximity.

**Comment by Luiscri** [comment]
Do I also have to change the type="traffic_light" attribute and remove the controlledInner="..." one?

**Comment by namdre** [comment]
The attribute type="traffic_light" must remain. The controlledInner setting is not needed (it only occurs when the network was built with legacy options).
