### ISSUE TITLE
Edge length has a massive effect on travel time in jammed mesoscopic scenario

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7001]
Setting up two scenarios which differ only by the fact that once the edge is split in a 45m and a 25m part and once it is a single edge of 70m. Average travel time differs by 40% (25s vs 35s).

**Comment by namdre** [comment]
Jamming happens between segments. A 70m edge is a single segment so no jamming effect will be visible.

**Comment by ambuehll** [comment]
If I may add my two cents: If all taus are set to the same value, this should be less problematic. This yields perfectly triangular fundamental diagram (with a free-flow branch and a backward wave branch). Thus, backward waves are also possible in that case (due to the space taken by a vehicle).

**Comment by behrisch** [comment]
Thanks for sharing your experiences. The problem in my network is that there seem to be lots of short edges and I thought this might be a general problem. If I have an edge where only one vehicle fits in, it is not a good idea to consider it a jam so we might want to consider a length threshold after which we even apply the jam threshold. At least we could warn the user that the network is not well suited for mesoscopic simulation.

**Comment by ambuehll** [comment]
Fair. This is, I think, related to what I reported some while ago:
https://github.com/eclipse/sumo/issues/5909 
and 
[maling list](http://sumo-user-mailing-list.90755.n8.nabble.com/sumo-user-geometry-remove-min-length-td3058.html)

Generally, it might make sense to set a lower bound to the meso-edgelength >> vehicle length.
For OSM derived networks, I suggest setting a relatively high geometry.remove.min-length. I use 50m, which reduces the number of short edges substantially.

**Comment by namdre** [comment]
Short edges do not jam by default (as discussed in #5909). This might still make them ill-suited for meso simulation but for a different reason.

**Comment by behrisch** [comment]
But short edges in this ticket meant shorter than the vehicle length. I am still not convinced that we should consider a segment of 20m jammed when there is a single vehicle on it. In other words the jam threshold should always be larger than the vehicle length. I may have calculated this wrong but I think we currently cannot ensure this.

**Comment by namdre** [comment]
As far as my intention in the code (and my understanding of how it works) goes, a single vehicle can never jam an edge.

**Comment by behrisch** [comment]
Because the code ensures that the threshold is strictly larger than the vehicle length or because it may be equal to the vehicle length and we rely on the `<=` in MESegment::free?
The latter does not seem very robust to me because any vehicle which is only slightly longer than the default length will violate this rule and also we may have floating point issues here since we add and subtract a lot to myOccupancy. But I agree that this is probably not the reason for the different behavior in my scenario. I will look further.

**Comment by namdre** [comment]
I retract my earlier assertion. In the current implementation a single vehicle of lengthWitGap *a* jams a segment of length *b* if:   *7.5 < a* and *7.5 < b < 15*.

After thinking on this, I conclude that the whole concept of having a threshold in '% of length' is ill-suited to simulation with varying vehicle lengths. At higher speeds, the space-requirements of vehicles is dominated by tau*speed rather than length so having a length-threshold is needlessly unstable. I think it makes more sense to re-write the code and define the threshold in vehicleCount instead. This would also make it trivial to enforce the requirement that a single vehicle does not jam a segment.

**Comment by namdre** [comment]
On the other hand, the way that the jam-jam-formula works (multiplying a value derived from tau_jj with the number of vehices in the segment) does not lead to a drop in flow if multiple short segments are jammed this way.

**Comment by namdre** [comment]
@behrisch The discrepancy in the original tests were caused by insertion-related artifacts: when trying to insert 3800 vehs/h on a 1-lane road, the capacity of the first segment has a major effect on the balance between traveltime and insertionDelay. After adjusting the volume to realistic levels, the discrepancy is gone.

**Comment by behrisch** [comment]
But isn't an insertion delayed the same way as an incoming car?

**Comment by namdre** [comment]
No. Insertion hast additional constraints (I think the code was written with calibrators in mind but it is also applied on regular departure):

https://github.com/eclipse/sumo/blob/d5e21f53410b1093ce8f887f20ba4bdb6e82d3ee/src/mesosim/MESegment.cpp#L260-L270

**Comment by behrisch** [comment]
OK, added another tests which also showed no obvious effects, so closing this.
