### ISSUE TITLE
person vehroutes are not usable as input

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7006]
When transfers from walk to train ride occur (over an access) the walk ends at the last pedestrian edge and the ride starts at the train edge leading to an error for a disconnected plan.

**Comment by namdre** [comment]
A working example would be 'devices/rerouting/personTrip/walk_access_walk' (the walk has a busStop as destination, )
An failing test would be 'sumo/devices/rerouting/personTrip/car_public_walk2' (the ride has a busStop as destination but the implicit access is not created).

(the problem is that access stages are only created after walks (MSTransportable::proceed)

**Comment by behrisch** [comment]
My problem was much more trivial and was related to cutRoutes. But I keep this open as it seems to be an issue.

**Comment by behrisch** [comment]
There was another problem concerning "from" attributes in rides which did not match the arrival edge of the previous walk. They are optional in this case anyway but should probably be allowed if they have a reasonable value.
