### ISSUE TITLE
inconsistence between traci and libsumo for vehicle.getLeader

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7013]
if there is no leader, traci returns None whereas libsumoe always returns ("", -1)

**Comment by namdre** [comment]
@behrisch I think traci should also return  ("", -1), what do you think?

**Comment by behrisch** [comment]
None is more self explanatory but the libsumo solution is better for all the people who do automated unpacking. The problem is that such an API change can easily go unnoticed if you just check the boolean value of the result, so `if leader` will now always be True. So I would stay with our premise that "when in doubt, traci is right" and change libsumo instead (unless we find a way to make the API change noticeable).

**Comment by namdre** [comment]
Generally, I agree with our rule but in this case I would be in favor of braking it (for automatic unpacking and general consistency with the internal libsumo API).
Also, getLeader is currently the **only** method that returns 'None' as an error signal which does not strike me as a pattern to be maintained.
I'm rather confident that most users of getLeader check the leader or the distance and would notice pretty quickly that something is amiss.

**Comment by behrisch** [comment]
OK, you are right, currently we never return None except for this one function.

**Comment by namdre** [comment]
After seeing that several tests including simpla break, I think a more gradual approach is needed.
I will add a function to switch on the new and conistent behavior and anounce that the old behavior will be deprecated eventually.
