### ISSUE TITLE
saved state must include traffic light phase and phase duration

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7020]
When a simulation starts at time t, the traffic light state is deduced from the offset and default cycle time. However, this does not allow to reconstruct the phase when loading a saved state:
- actuated traffic light state cannot be reconstructed from simulation time alone
- fixed traffic light offsets are not stored anywhere 
- fixed traffic lights could have been shifted in their timing via traci

affects #6201

- the value of MSInductLoop::myLastLeaveTime must also be saved to ensure accurate state for actuated TLS

**Comment by mtreca** [comment]
Just stumbled into this issue while Googling why my phases would be initialized incorrectly when loading a previously saved simulation state. While not a big deal when knowing phase settings are not saved since they can be manually re-initialized it may be good to mention it in the wiki page [here](https://sumo.dlr.de/docs/Simulation/SaveAndLoad.html) since it can lead to some major differences in simulations.

**Comment by namdre** [comment]
@mtreca. Thanks for the suggestion. It's added now.

**Comment by mtreca** [comment]
Thanks! Quick follow-up question (it might deserve its own issue): is vehicle waiting time affected by loading simulation state as well? I am getting strange results but I did not have time to fully investigate it yet. I will open a new issue if needed.

**Comment by behrisch** [comment]
This seems to be solved

**Comment by namdre** [comment]
No. This has not been solved for normal traffic lights.
