### ISSUE TITLE
I want to simulate a vehicle collision in SUMO and the colliding vehicle does not disappear

### ISSUE THREAD

**Issue by Mzy526** [eclipse/sumo#7230]
Hello, I want to simulate the scene of vehicles colliding in the center of the intersection in SUMO intersection, and the colliding vehicles will not disappear. Could you please tell me how to make the corresponding Settings?

**Comment by angelobanse** [comment]
set the option `--collision.action` to `remove` (https://sumo.dlr.de/docs/Simulation/Safety.html#collisions)

you can also read: https://sumo.dlr.de/docs/FAQ.html#how_to_simulate_an_accident

**Comment by Mzy526** [comment]
`--collision.action`this code in  witch file  to setting? In rou.xml file or in sumo.cfg file ,or others file?

**Comment by angelobanse** [comment]
it is an option when using **sumo** from the command line (type `sumo --help` in your command line for a list of available options). If you necessarily want to use **sumo-gui**, I recommend you take a look at [TraCI](https://sumo.dlr.de/docs/TraCI.html)

**Comment by namdre** [comment]
Application option can also be set in the respective config file (.sumocfg in this case). See https://sumo.dlr.de/docs/Basics/Using_the_Command_Line_Applications.html#configuration_files

**Comment by Chandu-dappadi** [comment]
> Hello, I want to simulate the scene of vehicles colliding in the center of the intersection in SUMO intersection, and the colliding vehicles will not disappear. Could you please tell me how to make the corresponding Settings?

have you got it

**Comment by Mzy526** [comment]
No, I didn't do that, but when the body of the vehicle crashes, when the body of the vehicle overlaps, you can pause the simulation, take a screenshot of the collision, and you can assume that the vehicle has crashed. The way I do it is, if you can't take screenshots and pause the emulation, you can make the emulation slow at first.



发自我的iPhone


------------------ Original ------------------
From: Chandu-dappadi ***@***.***&gt;
Date: Thu,Oct 13,2022 9:12 PM
To: eclipse/sumo ***@***.***&gt;
Cc: Mzy526 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [eclipse/sumo] I want to simulate a vehicle collision in SUMO andthe colliding vehicle does not disappear (#7230)





  
Hello, I want to simulate the scene of vehicles colliding in the center of the intersection in SUMO intersection, and the colliding vehicles will not disappear. Could you please tell me how to make the corresponding Settings?
  
have you got it

**Comment by Chandu-dappadi** [comment]
but I want to stop the vehicle when collision occurs and other vehicles also stoped in that lane and got the message as collision occurs near by
________________________________
From: Mzy526 ***@***.***>
Sent: Thursday, October 13, 2022 6:50 PM
To: eclipse/sumo ***@***.***>
Cc: CHANDRA KALA DAPPADI ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL]Re: [eclipse/sumo] I want to simulate a vehicle collision in SUMO and the colliding vehicle does not disappear (#7230)


EXTERNAL: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

No, I didn't do that, but when the body of the vehicle crashes, when the body of the vehicle overlaps, you can pause the simulation, take a screenshot of the collision, and you can assume that the vehicle has crashed. The way I do it is, if you can't take screenshots and pause the emulation, you can make the emulation slow at first.



发自我的iPhone


------------------ Original ------------------
From: Chandu-dappadi ***@***.***&gt;
Date: Thu,Oct 13,2022 9:12 PM
To: eclipse/sumo ***@***.***&gt;
Cc: Mzy526 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [eclipse/sumo] I want to simulate a vehicle collision in SUMO andthe colliding vehicle does not disappear (#7230)






Hello, I want to simulate the scene of vehicles colliding in the center of the intersection in SUMO intersection, and the colliding vehicles will not disappear. Could you please tell me how to make the corresponding Settings?

have you got it

―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

―

**Comment by namdre** [comment]
@Chandu-dappadi have you read/followed the liked documentation (https://sumo.dlr.de/docs/Simulation/Safety.html#collisions)?

**Comment by Chandu-dappadi** [comment]
Some part

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jakob Erdmann ***@***.***>
Sent: Thursday, October 13, 2022 8:07:13 PM
To: eclipse/sumo ***@***.***>
Cc: CHANDRA KALA DAPPADI ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [eclipse/sumo] I want to simulate a vehicle collision in SUMO and the colliding vehicle does not disappear (#7230)


EXTERNAL: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@Chandu-dappadi<https://github.com/Chandu-dappadi> have you read/followed the liked documentation (https://sumo.dlr.de/docs/Simulation/Safety.html#collisions)?
