### ISSUE TITLE
Problems on importing network from Arcgis using NETCONVERT

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7236]
Hi, I used ArcGIS to make the road network and save it as "my_ shape_ files.shp", "my_ shape_ files.shx ", "my_ shape_ files.proj ", and "my_ shape_ files.dbf "Etc., but when I used netconvert to convert it, there was an error, showing:

Error: SUMO was compiled without GDAL support.
Error: No nodes loaded.
Quitting (on error).

How can I fix it? Thanks in advance.
![error](https://user-images.githubusercontent.com/55737075/85941518-21959a80-b956-11ea-856f-82c30d9368bb.png)

**Comment by namdre** [comment]
due to licensing issues, you need to use the 'extra' version for GDAP support: 
- release: https://sumo.dlr.de/releases/1.6.0/sumo-win64extra-1.6.0.zip
- devel:  https://sumo.dlr.de/daily/sumo-win64extra-git.zip

**Comment by Shiyunyang-seu** [comment]
Hi, thanks for your suggestions.
I successfully solved the format conversion problem, but I found that there are many road right error problems.

![2](https://user-images.githubusercontent.com/55737075/86533384-4fa14e80-bf03-11ea-8f7d-40194e202ac9.png)

**Comment by behrisch** [comment]
Please do not add questions to an unrelated ticket, open a new one instead or write to the mailing list. Did you try merging the junctions?

**Comment by Shiyunyang-seu** [comment]
Thanks for your replying. Actually, what I mentioned is highly related to this problem. When I used Netconvert to convert shp files, I found some problems: 
1. Many road intersections do not form intersections
2. There are some problems with the right of way of vehicles at many intersections, many lanes can only turns around. 
How can I deal with these problems in batches?
Thanks in advance.

[Netconvert_shp.zip](https://github.com/eclipse/sumo/files/4906285/Netconvert_shp.zip)

**Comment by behrisch** [comment]
For the ease of tracking I reopen this ticket but please use a separate ticket next time.

**Comment by namdre** [comment]
It appears that the data from your shapefile provides incorrect topology. This could plausibly have happened because they were only validated visually (i.e. placing two junctions on top of each other instead of a single junction that logically connects edges).
SUMO currently does not provide a tool that could automatically correct this type of error.

My suggestion is to write a scipt using sumolib
- find junctions with close coordinates
- write auto a patch file with '<join>' elements for those junctions (https://sumo.dlr.de/docs/Networks/PlainXML.html#joining_nodes)
- patch your network with those joins (https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#modifying_the_network)
