### ISSUE TITLE
Various tau and tls-penalty values for heterogeneous networks

### ISSUE THREAD

**Issue by aminissn** [eclipse/sumo#7243]
Hi,

I was wondering if it would be possible to assign tau(ff-jj) and tls-penalty values according to the road (and intersection) category e.g. priority values? Obviously, to calibrate an urban road network with different road types it is necessary to assign different values of the meso model's parameter to each category of road. 

Thanks,
Sasan

**Comment by namdre** [comment]
similar to #5745 but the idea for local penalty values is new

**Comment by namdre** [comment]
@behrisch, edge types are already loaded from additional (as well as .net.xml). How about 

```
<additional>
    <type id="highway.motorway" ...>
        <meso tauff="1.13" taufj="1.13" taujf="1.73" taujj="1.4" jamThreshold="-1"
             multiQueue="true" junctionControl="false" tlsPenalty="0" tlsFlowPenalty="0"
             minorPenalty="0" overtaking="false"/>
    </type>
</additional>
```

**Comment by behrisch** [comment]
Could work although it is still not clear to me where to draw the line between network and vehicle properties. Those values are also candidates for vehicle properties which are to be adapted locally. (We discussed this idea of something like calibrators or rerouters changing the vehicle type. I could not find the ticket if there is one.)

**Comment by namdre** [comment]
I think it's worthwile to allow both kinds of heterogenity. An interaction with the vType-tau attribute would be straightforward as described at https://github.com/eclipse/sumo/issues/5745

I think setting the parameters for an edge type rather than for individual edges would be more feasible for the large networks that are typical for a meso simulation (and very local adaptions can still be realized by adding more types).

Local type calibration can already be achieved: https://sumo.dlr.de/docs/Simulation/Calibrator.html#calibrating_vehicle_types

**Comment by behrisch** [comment]
OK but  together with #5745 this can get complex easily. For determining the tau_ff you would need to look at edge parameter, vehicle parameter, vehicle type parameter and the global option where all of them can define the absolute value or an offset to the general tau of the vType?

**Comment by namdre** [comment]
- edge types would simple override the global value
- I would probably postpone the edge parameter thing for now (but it would be an override on the edge type value)
- there would be no vehicle parameters involved only vType parameters and since the vType only has a single tau this would have to be an offset to the (implicit) meso net-tau of 1

**Comment by behrisch** [comment]
I don't like the "offset to an implicit internal value" idea but this is affects only #5745. So yes let's do this (eventually).

**Comment by behrisch** [comment]
One more thing though: This should work for edge types as well as single edges like all the edge type attributes which are basically defaults for edge attributes?

**Comment by namdre** [comment]
For now I would make it work like `<restriction>` which is only accepted in a `<type>` to reduce implementation effort.

**Comment by behrisch** [comment]
OK
