### ISSUE TITLE
can not use duarouter file to do the route assignment

### ISSUE THREAD

**Issue by AnsonChan852** [eclipse/sumo#7276]
can not use duarouter file to do the route assignment
duarouter -c "C:/Users/leiyi/Desktop/X/duarcfg_file.trips2routes.duarcfg" -o od_route_file.odtrips.rou.xml
Error: Could not access configuration 'C:/Users/leiyi/Desktop/X/duarcfg_file.trips2routes.duarcfg'.
Quitting (on error).
[X.zip](https://github.com/eclipse/sumo/files/4869034/X.zip)

**Comment by angelobanse** [comment]
you have some typos in the `duarcfg_file.trips2routes.duarcfg` file:
- on line 4 and 5: you are mixing up different quotation marks. Use `"` instead of `“` at the beginning of the file names.
- also on lines 4 and 5: make sure that the network-file and route-file names match those you are really using.
- on line 8: there is a typo (it should say `<output>`).
