### ISSUE TITLE
Junction information retrieval

### ISSUE THREAD

**Issue by cspatharis** [eclipse/sumo#7301]
Hello,

I'm working with Python and Sumo TraCI (version 1.6.0) and I'm developing a project of handling the incoming vehicles of a junction. I would like to know if there is a solution or a hint for the following problem.

**Problem:** Suppose we have a vehicle veh_X which follows the edges={edge_A, edge_B, edge_C} and passes through junctions={junction_A, junction_B}. Now, junction_A connects edge_A and edge_B while junction_B connects edge_B and edge_C. Let's further suppose that veh_X is currently driving on edge_A and heading towards junction_A. I would like to know if there is a way to retrieve the id of the heading junction (in the example i would like it to return the id of junction_A). The ultimate goal is to find the distance from the center of the junction, but I cannot just compute it from the length and the current position because I would like to compute the incoming traffic from all the incoming edges of a certain junction. For example, if a vehicle_Y was driving at the same moment on edge_C it wouldn't concern vehicle_X, as it would need information only about the vehicles approaching junction_A.

I hope the problem is clearly stated. If there is something not clear enough, please feel free to ask me for further info.

Thanks in advance!

**Comment by m-kro** [comment]
Below I list some sumolib and TraCI functions which might be helpful:

[TraCI:](https://sumo.dlr.de/pydoc/traci.html)
- traci.vehicle.getNextTLS() : get a list of traffic lights along the vehicle route
- traci.vehicle.subscribeContext() : query attributes of other vehicles within a given distance
- traci.edge.getLastStepVehicleIDs(): retrieve vehicles on some edge

[sumolib:](https://sumo.dlr.de/pydoc/sumolib.net.html)
- sumolib.net.node.getIncoming(): retrieve incoming edges of a junction
- sumolib.net.edge.getToNode() : retrieve the directly following junction of an edge

In order to use these sumolib calls, you first have to instantiate a [sumolib.Net](https://sumo.dlr.de/pydoc/sumolib.net.html) instance using sumolib.readNet(). Then, you could first query the junction and its incoming edges with sumolib and then use TraCI to get the vehicles and their data on those.

**Comment by cspatharis** [comment]
Thank you for your comment and your quick response. I managed to solve my problem.
