### ISSUE TITLE
MIN_FALLBEHIND is defined as a speed, but used as an acceleration

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#7316]
`MIN_FALLBEHIND` is used to smoothly slow down to follow a leader.
It is defined as `(double)(7.0 / 3.6)`, so I would assume it is a speed. but when used it is compared to the `targetSpeed` the vehicle should reach after `remainingSeconds` (an acceleration). Is it intended, that the vehicle should at least fall back by `MIN_FALLBEHIND` during the `remainingSeconds`? Or am I missing something? Right now it is used as a minimum required deceleration.

**Comment by Domsall** [comment]
I'll just post my implementation here and hope that it helps. Instead of
`MAX2(MIN_FALLBEHIND, (myVehicle.getSpeed() - targetSpeed) / remainingSeconds));`,
which is used identically in LC2013 and SL2015, I use 
`MIN2(MAX2(0., (myVehicle.getSpeed()+MIN_FALLBEHIND-nv->getSpeed())/remainingSeconds), (myVehicle.getSpeed() - targetSpeed)/TS));`

**Comment by namdre** [comment]
I think this is a case where the code has outrun it's documentation. MIN_FALLBEHIND is just a minimum deceleration now (the value of 1.94m/s^2 has proved itself adequate in our tests and I would not want to change it on a whim.
To make any changes in this area, there would be two requirements:
- an example scenario that behaves better than the old version 
- none of the existing scenarios behaving noticeably worse than the old version

It might be useful to expose more of these hard-coded values to the end user though.

**Comment by Domsall** [comment]
I just went though the TextTest-tests and found two main tests, that have a behavior which is influenced by the "slow down to follow Leader" part. Those Tests are the sumo\lc_model\onRamp and roundabout Tests.
Which parameters do you use, to detect how good a model performes? The Speed/Duration/WaitingTime/TimeLoss statistics?

I think I was misunderstood. I didn't change it on a whim. For a CF-model of mine, I went through the whole LC-model code and tried to identify where oscillations happen.
The Code-comments at this specific part also refer to "slow down smoothly to follow leader", but this is not done smoothly with MIN_FALLBEHIND. targetSpeed is from the actual FollowSpeed-calculation, that would garanty a safe change, so I thought it would be beneficial for the driver to try to reach targetSpeed or at least a slower Speed than the leader, which would also be safe to change then.

**Comment by namdre** [comment]
Sorry for the misunderstanding. Due to the issue title I assumed it was more of a style issue (acceleration vs speed).

The reason for setting a lower bound on deceleration was the observation that the exact targetSpeed computation often leads to failed lane changing when the leader slows down due to random speed variation (or downstream traffic conditions). Smoothness is somewhat sacrificed for effectiveness.

Regarding evaluation: Yes, I look at the statistics you mentioned (also departDelay). But oftentimes I  look at individual tests in sumo-gui to check whether the vehicle behavior still makes sense. Unfortunately, changes to the lane-change model tend to have unexpected effects (i.e. two issues/bugs that somewhat cancel out and if you fix one, the other suddenly becomes visible). This makes it hard to rely on statistics alone. Also, many tests have some degree of noise which makes it harder to interpret the statistics.

I also look at more complex tests (https://github.com/DLR-TS/sumo-scenarios/tree/master/bologna). Besides the default version I'm also running several variations of the acosta scenario (sublane model, ballistic integration, subsecond simulation, ...) to judge the effect of model changes.

**Comment by Domsall** [comment]
thanks a lot for the clarification! I now understand the huge range of possible (negative) effects when carrying out small changes to the LC Code.
I also often look into the sumo-gui to check if changes perform as expected. I just checked the proposed change with the SUMO Tests and an On/OffRamp of mine (bunched vehicles changing off and on the ramp at the same time, deadlock potential), but in this case it isn't really possible to quantify the changes by looking into the gui. The statistics only changed slightly, which could also be some degree of noise.
I extracted some other variables, such as the remainingSeconds and speed at the time of the performed change (to see if the vehicle changes late or slows down more than the base version). I also plotted the time duration between the first lane change desire and the performed change.

It seems that lower deceleration values are bought at the expense of how long it takes until the vehicle can change the lane. I could lower the mean deceleration values by 90% and the 95% percentile by 40%. Nonetheless the time duration of the change doubles (from approx. 2s to 4s) with some vehicles waiting very long for a change (10s). This is still not criticle, as it doesn't really influence the speed. Vehicles of both versions change the lane at similar speeds. I will keep my changes for my subsecond Simulation (0.01-0.1s), as it creates more realistic acceleration trajectories, but like you said, it might not be well suited for other scenarios and configurations.
