### ISSUE TITLE
right turns in SUMO

### ISSUE THREAD

**Issue by alon910** [eclipse/sumo#7318]
Hello,

It seems that in case I have two lanes to turn right, sumo doesn't put the vehicle in the most right side lane, this causes that the vehicles is being put in a lane that is both through and right.

Do you know of a way to tell sumo that in case the vehicle wants to turn right - put it in the most right side lane?

see attached screenshot

![image](https://user-images.githubusercontent.com/7622761/87553426-976e6580-c6bb-11ea-8f29-2d32cd83fef1.png)

thanks :)

**Comment by Domsall** [comment]
I don't really understand. If you have 2 lanes turning right, shouldn't the driver have the freedom to choose which lane suits him better? That is done via internal parameters and variables in the LaneChange model. If you don't want to have the Vehicle on the "second" lane, you could:

- Change the "second" lane to only be a lane, that goes straight. Therefor delete/cut the connection.
- force the vehicle to change the lane via TraCI

**Comment by urielka** [comment]
@Domsall in reality when you have two right turn lanes, users will usually go trough the right most if both are clear

**Comment by Domsall** [comment]
yes and eventually following vehicles will be on the right most lane again. Nevertheless it can happen that vehicles end up being on a neighbor lane due to slow vehicles in front, the ongoing best lane for the route or being in a city and having a free lane choice (as in e.g. Germany you should/have to use the rightmost lane on Highways but are free to choose in cities).

**Comment by urielka** [comment]
@Domsall the problem is that this is the only trough lane and sometimes we have many vehicles trying to go right on that lane, not only one.

Can we force vehicles to go on the right lane when they turn right? it is the most realistic in our region (US)

**Comment by Domsall** [comment]
You can change the Lane Change model Parameters of the vehicle types according to [https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#lane-changing_models](url).
The default values should still result in a realistic lane changing manner, where vehicles choose the lanes best suited for them.
If you don't want any vehicles turning right on the through lane, why not delete the "right-turn connection" of that lane? Then all vehicles, that want to turn right, should end up on the rightmost lane.

**Comment by m-kro** [comment]
@alon910 : Did you check on which lane the vehicle entered the edge and where it heads to? The "best next lane" algorithm seems to favour the least lane changes possible.  I second @Domsall in trying out some changes in the lane change model, e.g. setting lcKeepRight. However, then it applies to all vehicles of a given type, everywhere in the network. Try to balance the lane change parameters so that you get an acceptable result.

@Domsall: Deleting the connection would lead to different behaviour when simulating high volumes. Only an option if you do not care about that case...

**Comment by urielka** [comment]
@Domsall as @m-kro said we can't delete it as it is not the case in reality...
@m-kro we can assign a special vtype to the cars in this route and then play with the lcKeepRight only for them no? seems like an hack but might work

**Comment by Domsall** [comment]
@urielka yes that should lead to more vehicles driving on the rightmost lane. The default value is 1. If you double the value, it means that the vehicles would change the lane to the rightmost one twice as fast.

Deleting the connection was meant to be a hack, if you don't want any vehicles to use that lane when turning right.

**Comment by behrisch** [comment]
Seems to be resolved.

**Comment by namdre** [comment]
again, this is a requirement for lane preferences as discussed in #5480
