### ISSUE TITLE
additional duarouter arguments for randomTrips.py

### ISSUE THREAD

**Issue by apiszcz** [eclipse/sumo#7347]
Would it be possible to a parameter that would pass through arguments for duarouter? in particular the number of processing threads option?

**Comment by namdre** [comment]
You can do this with a two-step process:
1. let randomTrips generate trips
2. call duarouter on those trips

**Comment by JCodyA** [comment]
Hello!  This might be a good one for me but I'm pretty new to this and will need some guidance.  I was looking through randomTrips.py a little and trying to figure it out.  Will this enhancement be as simple as adding a parameter to a constructor or something like that?

**Comment by behrisch** [comment]
Hi, this should add a generic way to provide more arguments to the underlying duarouter call.  It is a little bit more than just adding arguments to constructor. It should allow calls like `randomTrips.py duarouter--duaoption` to pass `--duaoption to the duarouter much like it is done in https://github.com/eclipse/sumo/blob/master/tools/assign/duaIterate.py#L464. Maybe the best way is to move the function https://github.com/eclipse/sumo/blob/master/tools/assign/duaIterate.py#L386 to sumolib and just reuse it.

**Comment by JCodyA** [comment]
Ok this is making more sense.  Where should I move the function to, options.py or do I need to create a new file/class?

**Comment by behrisch** [comment]
Yes options.py looks good to me. Thanks for picking it up!

**Comment by JCodyA** [comment]
Sure thing!  I'll start working on it.  I haven't contributed to sumo before but I have with other eclipse projects.  Do you use the [WIP] tag on pull requests to mark them as works in progress?  Normally I would open a [WIP] PR quickly to allow comment and get help, which will likely be needed.

**Comment by behrisch** [comment]
We haven't used this tag yet but it seems to be a good idea. Just go ahead.

**Comment by namdre** [comment]
@bcoueraud87 for you

**Comment by behrisch** [comment]
If you pick this up, please also have a look at https://github.com/eclipse/sumo/pull/8127

**Comment by namdre** [comment]
randomTrip writes the used options into the header of the generated trips.xml. This doesn't play nicely with options of the form `duarouter--some-option`.

Solution 1: escape the double dashes when writing the options header (ugly)
Solution 2: Instead of re-using the ugly suffix-double-dash notation from duaIterate.py, use a prefix that looks more like a "normal" option:     

use prefix `--duraouter-some-option` and simply replace the `--durarouter-` prefix with `--` before passing the option to the duarouter application.

In a second step we could also let duaIterate accept the new notation (thoug we'd still have to support the old for backward compatibility)

**Comment by namdre** [comment]
As discussed, we'll simply copy feasible options since there aren't actually that many still missing:

- human-readable-time
- write-trips.geo
- routing-threads
- routing-algorithm
- weights.priority-factor
- persontrip.transfer.taxi-walk
- persontrip.transfer.walk-taxi
- persontrip.taxi.waiting-time

**Comment by behrisch** [comment]
> Solution 2: use prefix `--duarouter-some-option` and simply replace the `--durarouter-` prefix with `--` before passing the option to the duarouter application.

I am also strongly in favor of that one
