### ISSUE TITLE
When SUMO Version 1.2.0 and Version 1.6.0 run the same .sumocfg file, the results will be different.

### ISSUE THREAD

**Issue by gaofenxia** [eclipse/sumo#7418]
When SUMO Version-1.2.0 and Version-1.6.0 run the same .sumocfg file, the output file size will be different, resulting in different calculation results of some indicators.  
    For example, I created a new simulation scenario today, all of which are the same. The difference is that I run the .sumocfg file in versions 1.2.0 and 1.6.0 respectively. When I run in Version-1.2.0, the average delay of vehicles is 3.50 seconds, while the average delay of vehicles running in Version-1.6.0 is 3.84 seconds. 
    What are the reasons for this difference? Is there any effect on simulation test?

**Comment by namdre** [comment]
Every release potentially changes vehicle behavior due to bug fixes.
Sometimes, behavior changes are also due to new features that can be switched off by backwards-compatibility options.
The changes are listed here: https://sumo.dlr.de/docs/ChangeLog.html
The tests always reflect the changing behavior.
