### ISSUE TITLE
CACC vehicles do not require external commands to take over automatically in certain environment.

### ISSUE THREAD

**Issue by gaofenxia** [eclipse/sumo#7468]
CACC vehicles need to be downward under certain conditions, but when to take over, which CACC vehicle will take over, the length of the response time, etc. are related to the traffic environment. They are uncertain variables. But most of the tests I saw above Github were about specifying one car to take over, and given the response time, when the car disappeared, the simulation stopped, but it didn't seem to match the actual traffic. 

So how do you get multiple vehicles in traffic to take over spontaneously when certain traffic conditions are met? 
Clarify the demand: 

1.  needs to have multiple vehicles in the traffic take over, not a particular one;
2.  does not specify a response time for CACC vehicles to take over spontaneously according to traffic conditions, which can be traffic diversion obstructions, emergency brakes on vehicles in front of them, etc. 
3.  specifies the simulation time, such as 3600 seconds, 3600 seconds after the simulation ends. 
4.  after the simulation, output the data file, containing all CACC vehicles response time, take-over location and other information.

**Comment by namdre** [comment]
@gaofenxia is this still relevant to you?

**Comment by gaofenxia** [comment]
yes@namdre

**Comment by namdre** [comment]
@schwamborn can you answer this or does the question need clarification?

**Comment by schwamborn** [comment]
I'm afraid I'm the wrong person to ask. Maybe @vmintsis has an idea?

**Comment by vmintsis** [comment]
@gaofenxia Given the current capabilities of ToC Device, take-over requests (TORs) can be dynamically (spontaneously) issued only due to impeded lane changes (please see: https://sumo.dlr.de/docs/ToC_Device.html#dynamic_tors). In the latter case available lead times are situation specific as well (please see Section 2.3.2.2 of the following report for more details: https://usercontent.one/wp/www.transaid.eu/wp-content/uploads/2017/Deliverables/WP3/TransAID_D3.1_Modelling-simulation-and-assessment-of-vehicle-automations.pdf). ToC output can be collected via the activation of the --device.toc.file <STRING> option (please see: https://sumo.dlr.de/docs/sumo.html#toc_device).

As far as the simulation stop issue is concerned, we haven't encountered it while conducting tests or simulation experiments involving control transitions. @namdre, @schwamborn: Could you please assist @gaofenxia with the latter issue?

**Comment by namdre** [comment]
As far as I understand the original question, 'stopped simulation' was only a description about the limitations of existing tests rather than a bug report.
I would consider this question answered. @gaofenxia re-open / rephrase your question as necessary
