### ISSUE TITLE
could not get value of  " traci.lanearea.getJamLengthVehicle" in meso 

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#7488]
As described in title
 
with .sumocfg 

<Mesoscopic>  
     <mesosim  value="true"/>
     <meso-junction-control value="true"/>
   </Mesoscopic>

can not get the returen value of the function of **traci.lanearea.getJamLengthVehicle** .

**Comment by namdre** [comment]
lanearea detectors and multientryexit detectors do not detector vehicles in meso because they are lane-based rather than edge based. Inductionloops will write output but they cannot be access via traci at the moment (#7492).

Note, that traci access to a meso simulation is a recent addition and not all features are implemented
