### ISSUE TITLE
Missing connections to mixed lanes when the bike lane is discontinued

### ISSUE THREAD

**Issue by ArmelliniMG** [eclipse/sumo#7548]
When importing from OSM, connections from bike lanes to mixed traffic lanes are not being built when the bicycle path is discontinued.
Building connections from edges without exclusive lanes to edges with bike lanes seems to be working well.

As an example, a scenario of two intersections in berlin is attached.
[Bike_connections.zip](https://github.com/eclipse/sumo/files/5225621/Bike_connections.zip)

**Comment by namdre** [comment]
This at least in part working as intended: Bikes are supposed to move onto the road before making their turn (#2350).
Arguably this could be replaced with double connections (pending #7550) but I'm not sure which one better reflects reality.
In a way both solutions are unrealistic when using the default model because in does not allow for cars and bicycles to share a lane (which they would do in this type of situation). 

However, there is still a bug with missing connectivity when a bike lane disappears.
Also the #2350 "solution" does not handle green verges between bicycle lanes and road correctly.
