### ISSUE TITLE
extract taxi stands from osm

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7729]
and generate stopping places (parking areas or charging stations or even bus stops?). Probably best done as a separate python script.

**Comment by namdre** [comment]
netconvert already has option `--parking-output` which extracts road-side parking and we could add taxis to that with a sub option.
I would prefer not to duplicate the osm parsing in python.

On the other hand, @lcodeca has done just that to extract off-road parking areas from OSM so you could also grab her codebase and add the taxi stuff on top of that (which she might already have done because she is working on taxis as well).

Note, that the current intermodal taxi routing code can only use *all* busStops or *any* edge and we will need to add some form of whitelisting to filter out the taxi stands.

**Comment by behrisch** [comment]
We probably want to have more flexibility in parameterizing the generated stopping places. I would rather not add all of this to netconvert. Parsing OSM XML is not so hard ;-).

**Comment by lcodeca** [comment]
Apologies for the delay, @behrisch @namdre .

I already wrote the script: https://github.com/lcodeca/SUMOActivityGen/blob/taxi-fleet/generateTaxiStandsFromOSM.py 

You can grab it from there and fix it as you please.

**Comment by behrisch** [comment]
@lcodeca Thanks Lara!
