### ISSUE TITLE
How could I get all available routes in the network?

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [eclipse/sumo#7739]
There are 6 intersections, 10 input points and 10 output points.All routes begin with input points and end with output points.How could I get all available routes in a large scale network?

**Comment by Sheldon-Zhou1997** [comment]
![picture](https://user-images.githubusercontent.com/52645665/97869857-15c74400-1d4d-11eb-93f9-b289f90074dd.png)

**Comment by behrisch** [comment]
This is a standard breadth first or depth first search problem provided you do not allow loops in the route (if you do there are infinitely many). Since it seems to be a recurring question, I added now a script. Please be aware that the number of routes may grow exponentially with the size of your input network.

**Comment by Sheldon-Zhou1997** [comment]
I try to reinstall sumo in ubuntu18.04 by the following instructions.
sudo apt-get install cmake python g++ libxerces-c-dev libfox-1.6-dev libgdal-dev libproj-dev libgl2ps-dev swig
    cd <SUMO_DIR> # please insert the correct directory name here
    export SUMO_HOME="$PWD"
    mkdir build/cmake-build && cd build/cmake-build
    cmake ../..
    make -j$(nproc)
But when I've done these, there is an error:
Command 'sumo' not found, but can be installed with:

sudo apt install sumo


Can I use the script with sumo1.6 in windows10?

**Comment by behrisch** [comment]
There is no need to reinstall sumo, you can just download the script and put it into the tools folder.
