### ISSUE TITLE
emergency braking due to premature left turner

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7764]

**Comment by namdre** [comment]
not related to #7761

**Comment by namdre** [comment]
The junction edges have priority values that prioritize the right turning traffic. The foe-on-junction logic interacts badly with this, thereby causing oncoming vehicles to be ignored by left-turners.

**Comment by namdre** [comment]
one solution could be to always build a straight-priority junction when there is a traffic light.

**Comment by behrisch** [comment]
If I remember correctly, we had this problem before, that the presence of a traffic light should affect the underlying foe logic. I think it is a good idea to build two foe logics for traffic light junctions (at least optionally and of course only if they differ). Or does the foe logic even depend on the signal plan?

**Comment by behrisch** [comment]
> The junction edges have priority values that prioritize the right turning traffic. The foe-on-junction logic interacts badly with this, thereby causing oncoming vehicles to be ignored by left-turners.

But why doesn't the straight going vehicle yield then? It does not look at edge priorities?

**Comment by namdre** [comment]
1) 
- different logic for signal-plan and tls-off: yes. this is a known issue. Building two logics would help here but it's not enough. The cont values also have to be adapted when switching off (#5379)
- different logic for different signal plans: The underlying logic only comes into play when conflicting streams get a green light a the same time. Theoretically there might be plans that require different logics but I don't think this happens in practice.
If conflicting streams get simultaneous green it should be with left-turns and oncoming. 
- then there is an open problem that the right of way logic even differs between phases at a traffic_light_right_on_red junction: by default oncoming right turn gets priority over left turns but in the exclusive left turn phase the left turn gets priority over the oncoming right turns (which may still drive to to right-on-red).

2) the straight going vehicle is allowed to drive onto the junction (because it has 'G') and because the foe vehicle is still safely behind the internal junction (it's not in the way). Only when it suddenly starts driving does the straight vehicle notice the problem and brakes

building an underlying straight-priority junction should solve the current issue for the two most common traffic light layouts: simultaneous-oncoming (tlLayout="opposites") and each-direction-get-its-own-phase (tlLayout="incoming"). Having the option to turn this into a right-turning priority junction when switching off would be "nice" and require a second logic but I don't think this is as urgent.

**Comment by namdre** [comment]
the fix in [803944b4c49c576785] breaks tls programs in acosta tests:
- at tls 235 all incoming-outgoing relations are at an angle. The new code selects the straightest pair which happens to be a minor road that should not get priority in the underlying right-of-way logic
- the tls program is computed with tls_csv2SUMO.py which relies on the underlying right-of-way logic to determine 'g' and 'G'
- the csv input to tls_csv2SUMO.py is quite unusual and lets conflicting streams enter the intersection simultaneously at a 90-degree angle

**Comment by namdre** [comment]
can be solved by setting node attribute `rightOfWay="edgePriority"`
