### ISSUE TITLE
IDM: emergency braking after insertion in subsecond simulation

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7786]

**Comment by Domsall** [comment]
Although this issue has already been closed, I am just going to write down another workaround for the IDM here, as I can't find another open issue to the gap calculation problem for the IDM. The calculation of the SecureGap, maximumSafeFollowSpeed, maximumSafeStopSpeed, etc. works good for the Krauss model, but not for the IDM. Therefore, I rearranged the formula of the IDM to get such safe speed values for the Extended IDM. I think this would also benefit the IDM.
The only problem for this kind of calculation is that you need a desired deceleration value (e.g. myDecel/2), as the IDM doesn't have a "safe speed", and need to have a workaround for the delta-exponent.

I would like to hear your views about the following calculation.

![IDM_SafeSpeed](https://user-images.githubusercontent.com/53042793/99440522-fd435600-2916-11eb-83ca-f5f16d662faf.JPG)

The Code looks something like this:

`double a = 1.;`
`double b = myHeadwayTime * myTwoSqrtAccelDecel - predSpeed;`
`double c = -sqrt(1 - pow(egoSpeed / desSpeed, myDelta) + myDecel / (2*myAccel) ) * gap * myTwoSqrtAccelDecel;`
`// myDecel is positive, but is intended as negative value here, therefore + instead of -`
`// quadratic formula`
`vsafe = (-b+sqrt(b*b-4.*a*c))/(2.*a);`
