### ISSUE TITLE
vType attribute lcKeepRight not working properly

### ISSUE THREAD

**Issue by zmajstorovic** [eclipse/sumo#7795]
Hello everyone, 

I'm having difficulties with that the cars in simulation always keep right lane. I have situation as shown on picture, the cars always go to the right lane and pass straight as orange arrow shows. Those cars should follow the red line, and avoid passing through intersection. Green line is ok. 

![image](https://user-images.githubusercontent.com/18489380/99256208-5925b600-2815-11eb-8607-cb6ec4bb09e3.png)

Firstly, I am using TAZ to direct traffic from one TAZ to another. 

In the [documentation ](https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html)i found the attribute _lcKeepRight_ and I added that in vehicle definition file CAR.vtype.xml:

`<routes>
	<vtype type="CAR" lcKeepRight="0.0"/>
</routes>`

to get _od_trips.odtrips.xml_ i used following function:
`od2trips -c od2trips.config.xml -n tazzone1.taz.xml -od-matrix-files --vtype="CAR" -o od_trips.odtrips.xml`

example of xml output
`<trip id="7065" depart="2.39" from="-304305" to="--305124" type="CAR" fromTaz="taz_12" toTaz="taz_31" departLane="free" departSpeed="max"/>`

Then I use duarouter with this instructios: 
`duarouter -c duarcfg_file.trips2routes.duarcfg`

Duarouter as input takes network file and odtrips.xml which is created in previous step, and in console I get 

> Error: The vehicle type 'CAR' for vehicle 'x' is not known.

Output in file generated by duarouter looks like this: 
`<vehicle id="7065" depart="2.39" departLane="free" departSpeed="max" fromTaz="taz_12" toTaz="taz_31">
        <route edges="-304305 -303422 .....--305096 --305124"/>
    </vehicle>`

-Note that in file which is generated by duarouter, there is no attributes for car type. 

Does anyone have any idea how to solve this problem?

If needed I can upload files so you can inspect for more details.

**Comment by Domsall** [comment]
This issue seems to come from the Duarouter. The calculated default, free flow traveltime seems to be higher on the upper route (red arrow) than on the route with the orange arrow. When you call duarouter without an extra weight file, dynamic time losses at intersections and traffic lights are not taken into account. The fastest way to resolve this, is to lower the edge/lane speed on the ramps (orange arrow). The default free flow traveltime on the ramps will then be higher than on the highway and the vehicles (duarouter) will choose to stay on the highway.

Another possible solution is to use dynamic routing during the simulation (https://sumo.dlr.de/docs/Demand/Automatic_Routing.html). The first few vehicles may then still choose the route with the orange arrow, but after a short period of time, they will all drive the route with the red arrow.

**Comment by zmajstorovic** [comment]
Thank you @Domsall, you were right. The speeds on ramps were higher than the speeds on the highway (red arrow), so I decreased speeds on ramps and the problem is "fixed". It's not the best possible solution since I have large map, but I don't have much choice other than correct manually.

Also, I experimented a little bit with _--device.rerouting.probability_ and it seems to create more natural behaviour of traffic which is good. The cars are taking different routes - I like that.  
After that I tried _--device.rerouting.with-taz_ but it looked like rerouting.probability option worked better. 
Commands I used to run mentioned options: 
`
sumo-gui -c file.sumocfg --device.rerouting.probability 1
`
and 
`
sumo-gui -c file.sumocfg --device.rerouting.with-taz true
`

Q1: What is the difference between those two? 
Q2: Should I use with-taz since I'm using TAZ in my simulation?

**Comment by namdre** [comment]
The options are for completely different things:
- the probability is for setting the proportion of vehicles can reroute in the simulation
- with-taz controls whether the route is computed between the original origin and destination edges of a vehicle or between the taz (which could lead to drastic shortening of routes because the shortest route between any of the fromTaz edges and to any of the toTaz edges is chosen). The latter option is only recommended for special applications.

**Comment by namdre** [comment]
>  It's not the best possible solution since I have large map, but I don't have much choice other than correct manually.

You can use netedit selection mode to filter for all edges of type motorway-link with a speed above a given threshold. Use "keep"-mode to combine criteria: https://sumo.dlr.de/docs/netedit.html#modification_mode

**Comment by zmajstorovic** [comment]
@namdre, your tips helped me a lot! I saw that selection mode in the Netedit but it never crossed my mind that I actually could use it. So, I tried as you suggested and it worked almost perfectly. I managed to filter out and correct most of the problematic intersections.
Thank you!
