### ISSUE TITLE
make the config file directory the default dir for ssm output

### ISSUE THREAD

**Issue by rummel123** [eclipse/sumo#7847]
I have a simulation using the ssm device. If I start the simulation via command line with `sumo` or `sumo-gui`, the ssm device output file is created and filled.
If I start the `sumo-gui.exe` in windwos with double click and load the sceanrio, there is no output file created. Also after running the sceanrio there is no output file.
[ssm_device_output.zip](https://github.com/eclipse/sumo/files/5582586/ssm_device_output.zip)

**Comment by namdre** [comment]
I'm pretty sure the files are on your computer. Since you did not specify an output file path, the output files are created in the current working directory. When running executables via double-click windows sets the working directory to the folder of the executable (bin). SSM device is pretty much the only component that guesses an output file name for you. This is because it can switch between all-outputs-in-one-file and one-file-for-each-vehicle and you can also configure the file via vehicle or vType parameter 'device.ssm.file'.

**Comment by rummel123** [comment]
output file is explicitly set via `--device.ssm.file conflicts.out.xml` in the config file

**Comment by rummel123** [comment]
The file is created in the `bin` folder of sumo. That's an unexpected behavior.

**Comment by namdre** [comment]
Sorry, I missed that option when looking at your config )-: This is indeed unexpected.

**Comment by loveliyliy** [comment]
Maybe you have to set the ssm_device under <vehicle> or <vType> first. Then use <device.ssm.xxx >in .sumocfg to control the action of  ssm_device. It is not a button to equip devices for all vehicles, but a button to control the installed device.
