### ISSUE TITLE
error dialog when quitting SUMO launchers with Command + Q on macOS

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#7854]
`⌘`+`Q` closes the Apps (as it should) but then displays an "X Fatal error" dialog. If I remember correctly, that did not occur with the previous Platypus-launchers.

Exiting the apps using the `red X button` , `File -> Quit` or `Ctrl + Q` does not show that error.

Relates to https://github.com/eclipse/sumo/issues/7806

**Comment by RobertHilbrich** [comment]
Yes, this is an issue with XQuartz - I think. `⌘`+`Q` does not close SUMO-GUI, but XQuartz instead, so that SUMO-GUI (or the Fox library) complains with an "X Fatal error". The way XQuartz works on macOS, I think all X windows have to be closed with `ctrl + Q` and then you can close XQuartz with `⌘`+`Q`. This is not related to the launchers, I think.

**Comment by angelobanse** [comment]
But you can close XQuartz applications using `⌘`+`Q`, you just get a dialog asking if you want to close X11, not an error.

Open **sumo-gui** from the terminal (do not use the launcher/shortcut) and try closing it with `⌘`+`Q`.

**Comment by angelobanse** [comment]
> 
> 
> But you can close XQuartz applications using `⌘`+`Q`, you just get a dialog asking if you want to close X11, not an error.
> ⬇️
> Try opening **sumo-gui** from the terminal (do not use the launcher/shortcut) and close it with `⌘`+`Q`.

you do get the "X Fatal error", but in the terminal...

This seems to be out of our hands.
