### ISSUE TITLE
OD2trips: Wrong flow output (ending time and from/to)

### ISSUE THREAD

**Issue by FrederikRB** [eclipse/sumo#7885]
Hello.

When using OD2trips to generate flows instead of trips, the ending time is 3600000 for one hour instead of 3600. Furthermore it says from="<taz-id>" to="<taz-id>" instead from and to edge-ids which caters for issues when loading the flow file as input for a simulation.

Thank you.

**Comment by namdre** [comment]
Our tests are working as expected. Please attach (zipped) input files and options to reproduce this issue.

**Comment by FrederikRB** [comment]
Absolutely, please see the attachments. 
[OD2trips-Test.zip](https://github.com/eclipse/sumo/files/5623367/OD2trips-Test.zip)

**Comment by namdre** [comment]
I was able to reproduce and fix the invalid times. However, all `from` and `to` attributes where valid in your example. Please re-open ticket if that problem persists and attach another input example.

**Comment by FrederikRB** [comment]
Great, thank you. 
Regarding the from and to attributes: In the my results the from and to refer to taz-IDs however should they not refer to the edges according to the taz-input file as they do when creating trips with the OD2trips tool? Please see the attachement for comparison between trip and flow output.
[OD2trips-Test2.zip](https://github.com/eclipse/sumo/files/5629316/OD2trips-Test2.zip)

**Comment by namdre** [comment]
The whole point of od2trips is to dis-aggregate the taz into (random) depart and arrival edges. Usually, most trips between the same taz pair will differ in regard to those edges.
When writing a flow instead of trips, only a single source and origin can be defined. It doesn't make much sense to pick one source and origin at random and then let all the vehicles use those. Hence, when writing vehicle flows, the attributes fromTaz and toTaz will be used and the original taz ids are written. Then in the simulation a shortest path routing between all edges of the from-taz to all edges in the to-taz will be used. Note, that the resulting simulation is completely different from the trip-based simulation and the shortest-path-between-taz route is only useful under special circumstances.
Personflow was using the wrong attribute.

**Comment by FrederikRB** [comment]
Super, thank you for the fix and the explanation. :)

Short question: I am relatively new to github and SUMO, how do I implement the changes you did to my SUMO?

**Comment by namdre** [comment]
download the nightly version from https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version

**Comment by FrederikRB** [comment]
Great, thank you very much for your help. :)
