### ISSUE TITLE
Fix OSG tests

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7914]
They crash non-deterministically and seem to delay the whole nightly build

**Comment by m-kro** [comment]
Probably due to missing locks

**Comment by namdre** [comment]
Unfortunately, the lock `vc->secureVehicles()` doesn't have the intended effect. It is only used to secure coordination between meso drawing and vehicle parameter access (please check the code to find all other cases where the lock is used).

Microsim uses lane-level locking (`lane->getVehiclesSecure`)

**Comment by m-kro** [comment]
Daily test machine for Windows still complains about unknown OpenGL constant, possibly because its graphic driver only supports an older version of OpenGL:
`OpenGL error 'invalid enumerant' after applying GLMode 0x803a` 
For this reason, the responsible call to scale normals has been disabled. Usually, normals should be normalised where the 3D object is created anyway.

**Comment by m-kro** [comment]
Tests look rather good by now...
