### ISSUE TITLE
Netedit: left mouse push in move mode does not grab the start or end points of edges appropriatly

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#7918]
Hi,
I use latest dev version v1_8_0+0072-308c602359
There is an issue with the grab start/end points of the edge geometries, because the position of the mouse event must be extreme precise. If I do not push the mouse button exactly on the middle of the circle, it does not grab the point, and the mouse move moves the view. At in-between geometry points this is not an issue. It is also an issue, that sometimes not the start or endpoint is grabbed, but a new in-between point is created, although the mouse is above the endpoints circle.
This makes network editing a real pain.

**Comment by namdre** [comment]
as far as I can tell the, the quarter-circle that overlaps with the original edge shape can be grabbed reliably. All other parts of the circle do not work. Most likely, the click test checks whether the edge was clicked rather than the circle.

@pablo: An efficient solution would be to draw quarter-cicles instead of full circles for and those points and to shift the identifiying letter slightly. This would also avoid the commonly encountered overlap when the end point of one geometry overlaps with the start point of the reverse-direction edge.
