### ISSUE TITLE
canBrake/canBrakeBeforeStopLine for IDM-vehicles at traffic lights

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#7956]
I am having problems with vehicles violating red traffic lights when using the IDM or the Extended IDM. I couldn't find a similar issue so I opened a new one. I already varied `jmDriveAfterYellowTime`and `jmDriveAfterRedTime`, but couldn't receive good results.

I have a scenario with vehicles passing a traffic light. When the IDM decel parameter is set too low (2.0 is already critical, especially with higher speeds), the vehicles show unrealistic behavior: When I set `jmDriveAfterRedTime<0`, then vehicles brake hard when the traffic light turns red, because at yellow they thought they would make it through, but didn't. When I set `jmDriveAfterRedTime>0`, then the vehicles may violate traffic lights which have been red for a long time. They first start to brake slightly, but then run the red light because the calculated brakeDist (with the brakeGap-function and myDecel) is higher than the seen distance.
The problem arises from two areas:
- The IDM uses the Decel-Parameter as a "desired braking" parameter, which could therefore be low for anticipatory drivers. The IDM vehicle can and will still brake harder in critical situations.
- The IDM starts off by braking slowly and not hard straight away, which can result in the brakeDist exceeding the seen during braking.

I was thinking of adding a specific brakeGap-function for the EIDM/IDM. But this function is used in many different areas and works perfectly for those and I am only having problems with one: the canBrakeBeforeStopLine and canBrake calculation at traffic lights. I previously used a changed Code line, but this doesn't work well with other Models:
Instead of 
`cfModel.brakeGap(myState.mySpeed, cfModel.getMaxDecel(), 0);`
I used a lower bound and an extra brakeDist value only for the traffic light calculation in planMoveInternal and processLinkApproaches to ensure braking when needed
`cfModel.brakeGap(myState.mySpeed, MAX2(3.5,cfModel.getMaxDecel()), 0.);`

What is the best way to improve the vehicle behavior of the IDM at traffic lights?
Thanks for your response in advance!

**Comment by namdre** [comment]
The yellow phase duration of traffic light is computed under the assumption of a minimum deceleration (**--tls.yellow.min-decel** with default 3). This means, vehicles that do not **wish** to brake at 3m/s^s will always run the risk of running a red light (or performing emergency stop) regardless of the car following model whenever they see a yellow light and think ''I won't be able to brake in time. lets just keep driving".

Since the assumed tls.yellow.min-decel is something of a real world network-wide constant (that must be assumed by real world traffic light engineers as well) it might make sense to just use this as a simulation constant as well and override low desired 'decel' when computing braking distance at traffic lights. 
Running a red light would still occur if the emergency decel (physical braking capability) is actually that low (frozen road or something).

**Comment by Domsall** [comment]
Thank you very much for the fix!!! The overshoot correction works good with the IDM/EIDM. I have one remaining question.
The vSafe speed doesn't get set in MSVehicle::processLinkApproaches, because the canBrake value there is still calculated using the brakeGap with getMaxDecel. So the vehicles calculate a vLinkWait, but don't use/set the value?! Or am I missing something?

**Comment by namdre** [comment]
The fix operates at an earlier point: In planMoveInternal, the vehicel "decides" whether to brake for the yellow light or not. Earlier it decided that it will not manage to brake and thus keep going (unsuccessfully). Now it decides that it will brake for yellow due to the higher available decel value.
I don't think it's necessary to change the computation in processLinkApproaches.

**Comment by Domsall** [comment]
I found the issue why the vehicles were still ignoring the yellow light and then braking hard when red. First of all they needed a minimum decel value to brake in time. The newly implemented `min-decel` helps a lot. But the IDM still has problems with the `brakeGap` comparison. When braking at a junction, the IDM starts off by decelerating softer at the beginning of the brake process and harder to the end of it. So at first the vehicle brakes at a yellow light, but then the `stopDistance` exceeds the `brakeDistance`, because the vehicle doesn't brake with the decel value straight away. After all, I now think that I actually need a CF-specific brakeGap-function.
Is it possible to make the brakeGap function inheritable/virtual for the different CF-Models?

**Comment by namdre** [comment]
The overshoot correction was a quick fix because I didn't want to extend the stopSpeed api to allow passing a custom decel value but I may have to do this after all.

**Comment by Domsall** [comment]
Thank you very much for the changes!!!
