### ISSUE TITLE
No lane change before intersection

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7976]
Hi, can I use Traci or other methods to set that vehicles can not change lanes within a certain range before the intersection. For example, when vehicles need to go straight but are in the lane which can only turn left, then the vehicles can only turn left and re-plan the route?
Thanks in advance!

**Comment by namdre** [comment]
you can use `traci.vehicle.setLaneChangeMode` to disable lane-changing but you will still have to trigger rerouting explicitly using `traci.vehicle.rerouteTraveltime`.
The vehicle will not consider the effort of lane changing while computing the route so in order to block the straight  route you can use call `traci.vehicle.setAdaptedTraveltime` to make the traveltime on the straight edge very large and thereby force another route.
