### ISSUE TITLE
SUMO was compiled without GDAL support and no nodes loaded

### ISSUE THREAD

**Issue by AvonTay** [eclipse/sumo#8058]
Hi, am aware there were similar post but i am still not able to figure out how to resolve.. 

1) SUMO was compiled without GDAL support - understood we need to download an older version for it to work ? The Steps that i've taken are as follows:
 a) downloaded sumo-0.32.0
b) in my folder (my_file) where the .dbf, .shp and .shx files are, i typed cmd in the header followed by netconvert --shapefile-prefix my_file
c) there is no highway in the folder but rather it contains info such as lanes, buildings, light, zone, blocks.

when i clicked enter, the 2 errors msg popped out =(

Any advice what else could be done ? Even tho SUMO was compiled but without GDAL what's the implication ? How do i remove the errors ? Deeply appreciate any suggestions/recommendations.

**Comment by namdre** [comment]
Using an older version is not the recommended solution. See https://sumo.dlr.de/docs/FAQ.html#error_sumo_was_compiled_without_gdal_support

**Comment by AvonTay** [comment]
thanks ! hmm the nightly-extra version seemed to have an URL error ... any other alternative ? I'm not familiar with Linux so didnt want to go this route..

**Comment by namdre** [comment]
Thanks for pointing out the dead link (now fixed)
https://sumo.dlr.de/daily/sumo-win64extra-git.zip
The extra-version of the latest release is also available at https://sumo.dlr.de/releases/1.8.0/sumo-win64extra-1.8.0.zip

**Comment by AvonTay** [comment]
Thanks. Have downloaded it. Sorry, new to this, still have the error popping out. Might have missed out some steps.. May i know once i've downloaded, do i copy the files into the SUMO folder or something ?

**Comment by AvonTay** [comment]
hi, would also like to seek some guidance assuming i  am using the osmWebWizard.py script but the area of interest does not have details such as roads, buildings etc, but i do have a Shapefiles (containing shp, .shx, .dbf, .proj, .sbn, .sbx), is there any way i can use netconvert to overlay them into the area of interest ? Thanks in advance once again !

**Comment by namdre** [comment]
> Thanks. Have downloaded it. Sorry, new to this, still have the error popping out. Might have missed out some steps.. May i know once i've downloaded, do i copy the files into the SUMO folder or something ?

If you replace the previous contents of the sumo folder with the contents of the zip archive that should work. If you run 'sumo' in a command line window it should list GDAL as a build feature. (also sumo-gui in the help/about dialog)

**Comment by namdre** [comment]
Yes. You can merge two networks by loading them both with netconvert optin **-s** if they are both geo-referenced. For details and limitations in the 1.8.0 version, see #8019

**Comment by AvonTay** [comment]
Thank you so much ! Saw GDAL being listed in cmd window.. 

Was trying it again and got this 
Error: Required field 'nolanes' or 'speed' is missing..  
Error: Available fields: objectid lane organizati country_co site terminal uid objectuniq.....

I went in to see the .dbf but there's only st_area_sh and st_length_.. and wasnt able to find any from nodes or to nodes information inside.. does it mean these info are lacking hence i am not able to run it ?

**Comment by namdre** [comment]
if any of the fields (i.e. 'lane') correspond to the number of road lanes you can set option **--shapefile.laneNumber lane**.
Otherwise, set option **--shapefile.use-defaults-on-failure**

**Comment by AvonTay** [comment]
thanks ! did this >netconvert --shapefile-prefix LANE --shapefile.use-defaults-on-failure

Not sure why i've this errror --> Road geometry must be of type 'linestring' or 'linestring25D' (found '3')

was searching online "https://qgis.org/api/2.18/classQgsWKBTypes.html" and found it's type 3 polygon ? Does it mean polygon is missing ? cos mine is just importing lane... 

Would also like to seek some guidance assuming i've a folder A, folder B and folder C containing the various .dbf, .shp and .shx files. do i combine all the files within each folder and rename it to e.g. FINAL and do a netconvert on FINAL ? Each of these folder contains specific things e.g. A is streetlight, B is Lanes, C is gate etc..

**Comment by AvonTay** [comment]
hi, wanted to add that i've tried:
netconvert --shapefile-prefix LANE --shapefile.laneNumber lane as there's a column called lane in the .dbf file but it didnt work. Hence, have changed it to --shapefile.use-defaults-on-failure. Does it mean the "lane" column in the .dbf is somehow not the correct file ?

**Comment by namdre** [comment]
> was searching online "https://qgis.org/api/2.18/classQgsWKBTypes.html" and found it's type 3 polygon ? Does it mean polygon is missing ? cos mine is just importing lane...

yes. roads cannot be given as a polygon. they have to be line or linestring. You may be able to convert polygon to linestring with GIS software such as qgis.

> Would also like to seek some guidance assuming i've a folder A, folder B and folder C containing the various .dbf, .shp and .shx files. do i combine all the files within each folder and rename it to e.g. FINAL and do a netconvert on FINAL ? Each of these folder contains specific things e.g. A is streetlight, B is Lanes, C is gate etc..

Streetlights and gates are not supported by the shapefile importer. Just ignore these folders and use the road geometry only.

> netconvert --shapefile-prefix LANE --shapefile.laneNumber lane as there's a column called lane in the .dbf file but it didnt work. Hence, have changed it to --shapefile.use-defaults-on-failure. Does it mean the "lane" column in the .dbf is somehow not the correct file ?

What was the error message when using **-shapefile.laneNumber lane** ?
What are the contents of the 'lane' column. If their are numbers, that should work.

**Comment by AvonTay** [comment]
Hi, can i presume the reason why it's polygon is because of the 2 parameters: "st_area_sh" and "st_length" ? Cos i cant find any other fields within that make sense. May i know typically how are linestring values reflected ? Is there a number as well or an ID with to and from to specify the length or sort ?

The error message when i was using --shapefile.laneNumber lane are as follow:

Error: Required field 'lane' or 'speed' is missing (add fields or set option --shapefile.use-defaults-on-failure).
Error: Available fields: objectid lane organizati country_co site terminal uid objectuniq cad_status db_14slo_h handle layer lyrfrzn lyrlock lyron lyrvpfrzn lyrhandle color entcolor lyrcolor blkcolor linetype entlinetyp lyrlntype blklinetyp elevation thickness linewt entlinewt lyrlinewt blklinewt refname ltscale extx exty extz docname docpath doctype docver docupdate version featurelab st_area_sh st_length_
Error: No nodes loaded.

Yes, the contents under the "lane" column are numbers ranging from 1 to 6. 

Just realized there were alphabets within. Have replaced them with numbers but still with these errors:

Error: Required field 'lane' or 'speed' is missing (add fields or set option --shapefile.use-defaults-on-failure).
Error: Available fields:
Error: No nodes loaded.
Quitting (on error).

**Comment by namdre** [comment]
try setting both options **--shapefile.laneNumber lane --shapefile.use-defaults-on-failure**. (speed is still 
missing).
Line/Linestring are geometry fields like polygon. An extra length field would not be needed since the linear geometry has an implicit length (though this would be shorter than the curve it approximates).

**Comment by AvonTay** [comment]
Hi, i've tried tt too and below was the error:

Error: Road geometry must be of type 'linestring' or 'linestring25D' (found '3')
Error: No nodes loaded.
Quitting (on error).

**Comment by namdre** [comment]
maybe something like this would help: https://support.esri.com/en/technical-article/000007707
Though, if you just need roads for your city, importing from OSM maybe the easier route: https://sumo.dlr.de/docs/Tutorials/OSMWebWizard.html

**Comment by AvonTay** [comment]
Yeah I started off with this but had to go via the net convert route as the area of interest is an empty patch currently without any road network etc..  are there any other alternatives? Or it's not workable based on e files that I've and the errors encountered?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by namdre** [comment]
If the polygons look like proper road geometries in a gis tool, I would try the polygon->linestring conversion (open source solution: https://gis.stackexchange.com/questions/15819/transforming-polygon-to-linestring-in-qgis)

**Comment by AvonTay** [comment]
hi, thanks for the advice. i've managed to convert to line in QGIS. May i know what can i do to use the data and import it back into sumo ? Do i need to use netconvert again and how do i read the polygon to linestring file cos it's in .qgz format ? 

Thanks in advance once again.

**Comment by namdre** [comment]
you need to save the linestring data in shapefile format (qgis is able to do this, just ask google) and then proceed as you did originally.

**Comment by AvonTay** [comment]
ok, got it. Thank you so much !

**Comment by AvonTay** [comment]
hi, sorry to re-open this..  would like to seek some advice again cos i've used QGIS to convert the polygon to lines, saved it as Shapefile and used netconvert function to the shapefile but somehow the lanes are missing..  wanted to know if there could be some errors in the conversion or something ? Thanks in advance =)

![SUMO](https://user-images.githubusercontent.com/77043318/104694685-8378ee80-5746-11eb-8e67-2ef26912476e.png)
![QGIS](https://user-images.githubusercontent.com/77043318/104694696-870c7580-5746-11eb-8695-86d682b8d023.png)

**Comment by behrisch** [comment]
It looks as if you have drawn multiple lines on top of each other but it is hard to tell from the picture alone why some are missing. Please attach the shape file and post the exact netconvert call you used. BTW: Drawing / modifying networks might be easier using SUMO's netedit.

**Comment by AvonTay** [comment]
Hi, thanks for the reply. Previously the issue was that the lanes are polygons (based on the original file that i received - i did not make any tweaks on my end) instead of lines hence i've used QGIS to upload the shapefiles and then i've transformed the polygon to lines. After conversion, i see the green lines in QGIS in the diagram above. 

Thereafter, i did this:

netconvert --shapefile-prefix AGV_Lane_Test --shapefile.laneNumber lane --shapefile.use-defaults-on-failure.

[AGV_Lane_Test.zip](https://github.com/eclipse/sumo/files/5819203/AGV_Lane_Test.zip)

Was able to build it successfully but with warnings below:

Warning: Edge '3' connects identical nodes, skipping.
Warning: Edge '4' connects identical nodes, skipping.
Warning: Edge '5' connects identical nodes, skipping.
Warning: Edge '7' connects identical nodes, skipping.
Warning: Edge '8' connects identical nodes, skipping.
Warning: Found sharp turn with radius 4.01 at the start of edge '0'.
Warning: Found sharp turn with radius 8.00 at the end of edge '106'.
Warning: Found sharp turn with radius 8.00 at the end of edge '2'.
Warning: Found sharp turn with radius 8.00 at the end of edge '29'.
Warning: Found sharp turn with radius 8.00 at the end of edge '31'.
Warning: Found sharp turn with radius 6.00 at the end of edge '65'.
Warning: Found sharp turn with radius 4.01 at the start of edge '81'.
Warning: Found sharp turn with radius 4.01 at the start of edge '82'.
Warning: 86 total messages of type: Edge '%' connects identical nodes, skipping.
Warning: 8 total messages of type: Found sharp turn with radius % at the end of edge '%'.
Success.

**Comment by behrisch** [comment]
The first five warnings show why there are missing edges. Try splitting the edges in the editor.

**Comment by AvonTay** [comment]
Hi, may i know how do we identify where are the edges e.g. which is edge 3, 4 etc in QGIS ? By splitting the edges meaning, do you mean to use the vertex tool and then we select all the vertex (in this case when i mouse over a specific lane, there are numerous vertex and i need to select all and shift them?)

**Comment by behrisch** [comment]
I don't know how you can find out an edge id / label in QGIS but this is rather a QGIS problem than a SUMO one and I am pretty sure it is not too hard. Concerning the split you need to add another node for the edge serving as start or end point such that there are two different nodes whichthe edge connects.

**Comment by vishalmhjn** [comment]
Hi, I get this error on Mac (12.0.1, used to happen with previous ones too)

`polyconvert -n ../network.net.xml --shapefile-prefixes taz_shapes -o output.poi.xml`
`Error: SUMO was compiled without GDAL support.`
`Quitting (on error).`

SUMO version:
`Eclipse SUMO sumo Version 1.9.0
 Build features: Darwin-19.6.0 x86_64 Clang 12.0.0.12000032 Release Proj GUI
 Copyright (C) 2001-2021 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.`

I could not find any thread on this. The solution [here](https://sumo.dlr.de/docs/FAQ.html#error_sumo_was_compiled_without_gdal_support) is for Windows or Linux. It would be great if someone could help me here.

thanks in advance! :)

**Comment by behrisch** [comment]
Did you install all the dependencies as mentioned here https://sumo.dlr.de/docs/Installing/MacOS_Build.html ? If problems persist, please open a new ticket because it seems to be a new problem

**Comment by vishalmhjn** [comment]
Yes, building it from the source helped.  This is somewhat related to earlier issue #7279. I resolved it by uninstalling brew gdal and installing the one from https://www.kyngchaos.com/software/frameworks/ This also helped https://github.com/r-spatial/sf/issues/1207

Thanks again!

**Comment by schwamborn** [comment]
@vishalmhjn Have you tried the brew formula with the `--with-gdal` option? (cf. https://github.com/DLR-TS/homebrew-sumo#usage)

**Comment by vishalmhjn** [comment]
@schwamborn I didn't know about this option. thanks for sharing it.

**Comment by mohammad-bgr** [comment]
Hi,
I am trying to import a shape file (that is exported from PARAMICS) to SUMO. I have 3 file type (*.dbf; *.shp; *.shx). I am following the instruction provided in the SUMO documentation and use the following command line:

**netconvert -v --shapefile-prefix links -o net.net.xml --shapefile.from-id StartNode --shapefile.to-id EndNode --shapefile.use-defaults-on-failure**  
as the result the following warning are rising and a net.net.xml file is created. 

proj_create: Error 1027 (Invalid value for an argument): utm: Invalid value for zone
Warning: Invalid longitude -6951.85
done.
 Import done:
   120 nodes loaded.
   221 edges loaded.
Proj projection parameters used: '+proj=utm +zone=-1127 +ellps=WGS84 +datum=WGS84 +units=m +no_defs'.
Removing self-loops ... done (2ms).
Removing empty nodes ... done (0ms).
   0 nodes removed.
Moving network to origin ... done (1ms).
Computing turning directions ... done (0ms).
Assigning nodes to traffic lights ... done (0ms).
Warning: Found sharp turn with radius 3.89 at the start of edge '1'.
Warning: Found sharp turn with radius 2.03 at the end of edge '1'.
Warning: Found angle of 152.95 degrees at edge '105', segment 2.
Warning: Found sharp turn with radius 2.29 at the end of edge '105'.
Warning: Found angle of 155.20 degrees at edge '107', segment 2.
Warning: Found sharp turn with radius 1.94 at the end of edge '107'.
Warning: Found sharp turn with radius 3.68 at the start of edge '114'.
Warning: Found angle of 157.72 degrees at edge '114', segment 10.
Warning: Found sharp turn with radius 1.92 at the end of edge '114'.
Warning: Found angle of 148.88 degrees at edge '115', segment 0.
Warning: Found sharp turn with radius 1.99 at the start of edge '115'.
Warning: Found sharp turn with radius 3.70 at the end of edge '123'.
Warning: Found angle of 105.94 degrees at edge '126', segment 2.
Warning: Found sharp turn with radius 3.67 at the start of edge '139'.
Warning: Found sharp turn with radius 7.44 at the start of edge '140'.
Sorting nodes' edges ... done (0ms).
Computing node shapes ... done (9ms).
Computing edge shapes ... done (4ms).
Computing node types ... done (0ms).
Computing priorities ... done (1ms).
Computing approached edges ... done (2ms).
Guessing and setting roundabouts ... done (0ms).
Computing approaching lanes ... done (1ms).
Dividing of lanes on approached lanes ... done (1ms).
Processing turnarounds ... done (0ms).
Rechecking of lane endings ... done (0ms).
Computing traffic light control information ... done (4ms).
Computing node logics ... done (3ms).
Computing traffic light logics ... done (0ms).
 0 traffic light(s) computed.
Building inner edges ...
Warning: Connection '178_0->172_0' is only 0.01m short.
Warning: Speed of straight connection '178_0->171_0' reduced by 7.05 due to turning radius of 8.50 (length=22.14, angle=179.74).
Warning: Connection '177_0->175_0' is only 0.02m short.
Warning: Speed of straight connection '177_0->176_0' reduced by 7.01 due to turning radius of 8.60 (length=22.38, angle=179.35).
Warning: Speed of straight connection '187_0->179_0' reduced by 7.73 due to turning radius of 6.90 (length=17.47, angle=179.17).
Warning: Speed of straight connection '190_0->191_0' reduced by 9.29 due to turning radius of 3.85 (length=8.78, angle=179.91).
Warning: Speed of straight connection '83_0->200_0' reduced by 9.31 due to turning radius of 3.82 (length=8.70, angle=180.00).
Warning: Intersecting left turns at junction '126' from lane '35_0' and lane '126_0' (increase junction radius to avoid this).
Warning: Connection '209_0->36_0' is only 0.06m short.
Warning: Connection '139_0->45_0' is only 0.01m short.
Warning: Intersecting left turns at junction '42' from lane '77_0' and lane '204_0' (increase junction radius to avoid this).
Warning: Intersecting left turns at junction '53' from lane '22_0' and lane '219_0' (increase junction radius to avoid this).
Warning: Connection '158_0->102_0' is only 0.01m short.
done (16ms).
-----------------------------------------------------
Summary:
 Node type statistics:
  Unregulated junctions       : 0
  Dead-end junctions          : 2
  Priority junctions          : 118
  Right-before-left junctions : 0
 Network boundaries:
  Original boundary  : -8714.83,-3666.58,-6058.24,-1412.88
  Applied offset     : 8714.83,3666.58
  Converted boundary : 0.00,0.00,2656.59,2253.70
-----------------------------------------------------
Writing network ... done (30ms).
Warning: 18 total messages of type: Connection '%_%->%_%' is only %m short.
Warning: 72 total messages of type: Found angle of % degrees at edge '%', segment %.
Warning: 62 total messages of type: Found sharp turn with radius % at the end of edge '%'.
Warning: 40 total messages of type: Found sharp turn with radius % at the start of edge '%'.
Warning: 47 total messages of type: Speed of % connection '%' reduced by % due to turning radius of % (length=%, angle=%).
Warning: 861 total messages of type: Unable to project coordinates for edge '%'.
Success.
-----------------------------------------------------------------------------------------------
but as I go to open the xml file in netedit I come up with the error of: 

**Error: Could not build projection!
done.
Error: No nodes loaded.
Error: Failed to build network.**

I would be very grateful if someone could help me with this matter. Thanks in advance for your time.

**Comment by behrisch** [comment]
@mohammad-bgr  Please do not abuse an unrelated ticket for your question. Please open a new one and attach your input if possible.
