### ISSUE TITLE
What causes pedestrians to not obey the traffic light

### ISSUE THREAD

**Issue by GyChou** [eclipse/sumo#8088]
I used the default striping pedestrian model. But he does not obey the traffic light
![L)X}VYVTP 4~EDPUHH {@89](https://user-images.githubusercontent.com/30279942/104700838-bd022780-574f-11eb-8663-9c9286d729c2.png)

**Comment by namdre** [comment]
please attach the scenario files

**Comment by GyChou** [comment]
sumo-gui -c ./exp.sumocfg
[multi_lane_v2.zip](https://github.com/eclipse/sumo/files/5820767/multi_lane_v2.zip)

**Comment by namdre** [comment]
The horizontal road permits pedestrians on all lanes and therefore the walkingarea goes all the way across and the crossings aren't even used. The network has an issue quite similar to #7625. The crossings are invalid because there is nothing to cross but this was not detected when building the network.
