### ISSUE TITLE
issues with getNeighbors

### ISSUE THREAD

**Issue by Mikemraz** [eclipse/sumo#8119]
I found a bug regarding traci.vehicle.getNeighbors(), in which the neighbor vehicle could not be extracted **if that neighbor vehicle has just executed a lane change manuver from other lanes** in the last second. I do not know if this is related to issue #5210. Can someone help me with this issue? it is a serious problem in my case as vehicles would not behave safely if surrounding vehicles are not fully detectd.

**Comment by namdre** [comment]
This is unrelated to #5210 and has to do with the order of operations. (vehicles compute their lane changes per edge ordered in the upstream direction and store their neighbors afterwards).  I would expect that the leading vehicles are always retrieved correctly (because they are computed earlier than the ego vehicle) but that vehicles which became neighboring followers in the previous step are missing. Can you confirm this pattern?

**Comment by Mikemraz** [comment]
Thanks for your quick response @namdre. And yes, you are right. The pattern you decribed held in my case. After identifying the root cause, is there anything you suggest me handle this? Or it is a bug we cannot walk around at least for the near future?

**Comment by namdre** [comment]
On second thought, the issue could also arise for leading neighbor vehicles on subsequent edges if those edges are processed after the ego vehicle edge. The issue isn't trivial to fix either (a new processing stage would have to be added after the lane change computation with adverse impact on simulation speed).

You could use a filtered context subscription instead. This users another code path to determine neighboring vehicles.
```
traci.vehicle.subscribeContext(objID, traci.constants.CMD_GET_VEHICLE_VARIABLE, viewRange, traci.constants.VAR_POSITION])
traci.vehicle.addSubscriptionFilterLCManeuver()

```
