### ISSUE TITLE
recheck tauWithVehLength for short segments with long vehicles

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8156]
probably it should not take the vehicle length into account but rather the minimum of vehicle and segment length

**Comment by namdre** [comment]
After looking at it some more I don't think there is a bug:

1) https://github.com/eclipse/sumo/blob/0cc81d2b4a7a30e3d0d65e7c8bced700c9e4ac0b/src/mesosim/MESegment.cpp#L511
This computes when the next vehicle can leave the short segment after ego leaves (setBlockTime). Having the headway increase with vehicle length regardless of segment length is correct.

2) https://github.com/eclipse/sumo/blob/0cc81d2b4a7a30e3d0d65e7c8bced700c9e4ac0b/src/mesosim/MESegment.cpp#L589
This computes the earliest exit time after the leader leaves the segment. This code path will not be used since the ego vehicle will always be  alone on the short segment. Nevertheless the code computes a consistent time headway between vehicles

3) https://github.com/eclipse/sumo/blob/0cc81d2b4a7a30e3d0d65e7c8bced700c9e4ac0b/src/mesosim/MESegment.cpp#L598
This computes when the next vehicle can enter the segment after ego (setEntryBlockTime). Having the headway increase with vehicle length regardless of segment length is correct.

The other occurrences are for jam threshold (not applicable to short segments) and speed computation (code path not used for short segments).
