### ISSUE TITLE
Collision-inclusive simulation using SUMO

### ISSUE THREAD

**Issue by miracelplus** [eclipse/sumo#8192]
Hi,

We have been trying to develop a collision-inclusive simulation using SUMO. Additionally, we use self-defined C++ car-following and lane-changing models. However, when we are trying to run the simulation, we noticed that the simulation will automatically block some collisions if we left the speedmode and lanechangemode unchanged. However, when we close all safety checks provided by sumo (set speedmode and lane change mode to 0), the self-defined car following model and lane changing model will not work and the vehicle will run with constant speed. Therefore, I wonder if there is a method that will allow us to close all the safety checks in the simulation without disabling the internal car following model and lane changing model? Thanks!

Best regards
Haowei

**Comment by namdre** [comment]
1) using speedmode=0 only makes sense if you are constantly providing updated speeds via traci.vehicle.setSpeed or slowDown (your carFollowModel is outside sumo and connected via TraCI).. It is not meant to work alongside a C++ carFollowModel.

2) your C++ carFollowing model should be able to cause rear-end collisions by itself. It should also allow "dangerous" lane changing since the lane changing model uses the carFollowModel to determine secure gaps. Note, that you can use the global variable `MSGlobals::gComputeLC` to detect whether the carFollowModel is being called from a lane-changing context.

The junction model will do it's best to prevent collisions on junction. You can tune this with junction model attributes (i.e. jmDriveAfterRedTime) or by manipulating the permitted deceleration. Possibly something like #8078 is needed for your use case as well.

**Comment by miracelplus** [comment]
Thanks a lot! We will look into details.
