### ISSUE TITLE
Relative coordinates?

### ISSUE THREAD

**Issue by pgrandinetti** [eclipse/sumo#8201]
The `vehicle_x`, `vehicle_y`, and `vehicle_z` output of `full car data` are relative coordinates?
If yes, relative to what point?
Can this be changed in the configuration files?

P.S. I wanted to ask this in the mailing list, rather than a github issue, but never got the approval email.

Thanks.

**Comment by angelobanse** [comment]
https://sumo.dlr.de/docs/Simulation/Output/FCDOutput.html#generated_output

**Comment by namdre** [comment]
by default, the network origin 0,0 is the lower left corner of the road network. You can shift this by using the netconvert options **--offset.x --offset.y --offset.z**. If you set the option **--offset.disable-normalization** during initial import of geo-referenced network then the coordinates will be raw utm (not recommend because the large values increase numerical errors).
