### ISSUE TITLE
SUMO gui blank screen on Mac

### ISSUE THREAD

**Issue by pikeas** [eclipse/sumo#8208]
I've built SUMO with:

```
$ cmake -DPYTHON_EXECUTABLE=[...]/python3 \
               -DPYTHON_INCLUDE_DIR:PATH=[...]/Python.framework/Headers \
               -DPYTHON_LIBRARY:FILEPATH=[...]/lib/libpython3.9.dylib ..
$ cmake --build . --parallel 10
```

When I run `sumo-gui`, XQuartz opens but the SUMO window doesn't appear. This worked previously, so I suspect that something has gone wrong with a homebrew and/or Apple dependency.

I've updated to the latest macOS 11.2, latest homebrew packages (`brew upgrade`), and re-built SUMO from a fresh download of the 1.8 src.

I've also tried the official homebrew package (`brew install dlr-ts/sumo/sumo`), and `/usr/local/Cellar/sumo/1.8.0/bin/sumo-gui` has the same issue.

**Comment by pikeas** [comment]
Solved by running `DISPLAY=:0 sumo-gui`, not sure what the consequences may be.

Also worth noting that there's a beta for a new version of XQuartz, this will be the first new release in 4 years and may cause unexpected issues.

**Comment by schwamborn** [comment]
Thanks for your feedback. Maybe you didn't log out and in again after installing XQuartz? As they also state in their [release notes](https://www.xquartz.org/releases/XQuartz-2.7.11.html) (both for 2.7.11 and 2.8.0_beta3):

> If this is your first time installing XQuartz, you may wish to logout and log back in to update your DISPLAY environment variable.

**Comment by schwamborn** [comment]
Related to https://github.com/XQuartz/XQuartz/issues/66

**Comment by handsomehu0627** [comment]
I have the same problem and I temporarily fixed it.
It is caused by processes communication issues, the sumo-gui process and the netedit process are depend on xquartz to visualize. But they do not find the xquartz process. This may be the environment variable problems or parameter problems.
So, solution for this is:

use command line xquartz to explicitly open the xquartz process(program)
use command line sumo-gui or netedit to open the corresponding app you want, this time they'll be able to find the quartz process which they depend on. It is also viable to click the icon to start the sumo-gui and netedit .

**Comment by rikdev2001-art** [comment]
I installed sumo using package on my mac, and netedit is having black screen issue, how to fix this, Thanks in advance.

![Image](https://github.com/user-attachments/assets/d02b61ef-8745-4fab-b339-e2793fb4e108)
