### ISSUE TITLE
edges.join-tram-dist looses traffic light information

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8219]
Even though the junction is not affected by the join (at least not visibly) it has a traffic light when built without the option and none otherwise. Example is in the bugreports folder.

**Comment by namdre** [comment]
added test in ce31b2d16507aaf1a11c46e7fbacc46e436a0a7b

**Comment by namdre** [comment]
join-tram did merge a tiny edge that was then removed during junction joining.
Actual cause was the loss of traffic light information when using **--tls.discard-simple** and **--junctions.join**. join-tram only exposed this by via impact on geometry.remove (which propagates discarded simple-tls information).
