### ISSUE TITLE
departSpeed seems to be checked with lowest Speedlimit on edge

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#8226]
Hello,

I attached a Carla SUMO example where the definition of departSpeed="5.00" throughs warnings (from MSEdge::validateDepartSpeed). It seems that the departSpeed isn't checked for the departing lane (~13m/s), but for the lowest Speedlimit on the edge. In the attached Scenario, this happens to be the hard shoulder with ~2m/s. Is this changeable?!
Thanks in advance!!!

For a while now, I am also having problems with right clicking on vehicles to get the parameters. Sumo-gui freezes for a while before creating the drop-down list. Did I maybe setup something wrong?! Or does this just happen with these larger networks?!

[examples.zip](https://github.com/eclipse/sumo/files/5967483/examples.zip)

**Comment by namdre** [comment]
departSpeed is checked for the configured departLane. 
The default departLane is the rightmost lane that permits the vClass. Setting departLane=1 would solve this. 

Since typical (osm-derived) sumo networks don't have lane specific speeds the issue of factoring speed limit into depart lane selection never came up (configurable selection criteria are density and strategic benefit).

Regarding the right-click, see #7927

**Comment by Domsall** [comment]
Unfortunately the departSpeed check isn't working as intended and is still throwing errors, even when I define the correct departLane.
When I set the departSpeed to max, everything works fine and the vehicle departs with the expected speed (even when I don't set the departLane). But when I set the departSpeed to a specific value, then I get a warning and a huge change in the SpeedFactor. I also get this warning, when I add the correct departLane with a higher Speedlimit.
