### ISSUE TITLE
How to increase the sensitivity for collisions in intersections

### ISSUE THREAD

**Issue by Izzatbrg** [eclipse/sumo#8312]
I'm trying to increase the sensitivity for collisions in intersections, so I did 
` --collision.mingap-factor` and I tried to increase the mingap but both affected just on the collisions at the same lane, not the collisions within the intersection. Is there any way to increase it?
![collision](https://user-images.githubusercontent.com/45941207/109817259-0213e780-7c32-11eb-9ca7-fb63c42bc927.PNG)

**Comment by namdre** [comment]
set option **--collision.check-junctions**

**Comment by Izzatbrg** [comment]
I did but the sensitivity still the same. I want to increase it up to 2m. for example in the image below no collision was detected even when I do 
`traci.start(["sumo-gui", "-c", "D:/Programms/sumo/sumo-test/test.sumocfg","--step-length" ,"0.1", "--collision.check-junctions", "--collision.mingap-factor","2","--collision.action", "warn"])`.
thanks a lot for your help
![collison](https://user-images.githubusercontent.com/45941207/109942420-799a5300-7cd4-11eb-9067-f9b31442fd00.PNG)

**Comment by namdre** [comment]
At the moment, the minGap value is only used when detecting collisions during car-following.
The reason here is that some carFollowModels enforce the minimum gap and any violation of minGap points to a bug in the implementation.
Other models are more relaxed so an occasional minGap violation is expected and hence doesn't need to trigger a warning.

I'm taking this is a suggestion to add new parameter for configuring the junction-collision sensitivity.
