### ISSUE TITLE
allow vClass specific speeds on junctions

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8380]
if the normal predecessor edge and the normal successor edge of an internal lane have the same edge type,
inherit speed restrictions for that edge type

**Comment by yunpangfloetteroed** [comment]
If a vehicle (e.g. AV) is programmed to run at a lower speed at (certain or all) intersections, can we set max speed restrictions for the respective internal links?  Currently, it is not possible to do this setting, since internal links have no type definition. 

I tried to create a fictive road type "internal_through" and set the max speed of one internal link for AV is 1 m/s (normal max speed is 3.5 m/s) in a speedRestrictions.typ.xml. And I added a type attribute with this type defintion in the respective internal link definition in the network file. But it seems that this addition makes no speed difference when observing the simulation.

**Comment by namdre** [comment]
@yunpangfloetteroed In your scenario you could add a very short edge before and after the intersection with the type "internal_through" and then the type will (now) also apply to the junction itself. For more convenience (no edge-splitting) you need #8383

**Comment by namdre** [comment]
should also use the average speed of both restricted speeds if the edges before and after have different edge types with vClass specific speeds.

**Comment by namdre** [comment]
If the network is built with option **--junctions.higher-speed** (#8535), the restricted speed on the junction will be the higher of before and after speeds instead of the average.
