### ISSUE TITLE
Emergency braking on junction

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8504]
quoting @Domsall 
> I have vehicles which wait on a junction to turn. Everything is fine until the foe vehicle drives onto the junction. The "ego" vehicle, wanting to turn, then already starts to drive although the junction is not free. It then brakes hard and waits again. It seems that the ego vehicle looses the foe vehicle for a short time and then sees it again.
> Minimal Example:
> [JunctionBraking.zip](https://github.com/eclipse/sumo/files/6324605/JunctionBraking.zip)

**Comment by Domsall** [comment]
oh ok, sorry and thanks!

**Comment by Domsall** [comment]
I hope it helps, if I describe the bug on the Code level using the posted example:

- Vehicle f21 drives onto the junction to turn left
- Vehicle f21 has to wait for f42 to pass. f21 checks this via `MSVehicle::processLinkApproaches`->`MSLink::opened`, as vehicle f42 is in `myApproachingVehicles`
- f42 actually exists two times in `myApproachingVehicles`, once as a vehicle driving from edge 1 to edge 2 and once as a vehicle driving from internal link 1 to edge 2.
- When f42 drives onto the junction, `myApproachingVehicles` changes and only has one entry left: vehicle driving from internal link 1 to edge 2. This is as expected.
- f21 now starts driving, even though f42 is still on the junction, because in `MSLink::opened` vehicle f21 only checks the link from edge 1 to edge 2 and not the link from internal 1 to edge 2.
- f21 still emergency brakes and does not crash, because the calculation in `planMoveInternal` -> `checkLinkLeaderCurrentAndParallel` intercepts the bug. I would assume, that `checkLinkLeaderCurrentAndParallel` should not check vehicle f42, because it is a vehicle on a different link, but in this case it avoids the collision.
(f42 is the result of `link->getLeaderInfo`)
