### ISSUE TITLE
uncomplete nodes' coordniates when using netDiff.py and unable to merging two nets with netconvert

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#8582]
when netDiff.py generates the differences between two networks (update.net.xml and original/net.net.xml), nodes' coordinates are not written out completely, if only x or only y is changed. 

When commenting out these nodes errors with "The from-node is not given for edge *****" have appeared.

**Comment by yunpangfloetteroed** [comment]
The files locate under S:\Sumo\Bugreports\8582_uncomplete_coordinates_and_errors_when_merging_two nets

**Comment by namdre** [comment]
The problem comes when creating a diff between networks A and B and then applying that diff to network C.

Netdiff only holds partial attributes for an edge (in order to updated an edge that exists in A) but then tries to use the partial information with network C where the edge is missing -> hence the error
