### ISSUE TITLE
How to add a new car-following model in SUMO

### ISSUE THREAD

**Issue by Zhangweichong** [eclipse/sumo#8664]
I want to know how to add a new car-following model in SUMO?  Is it about changing the code in GitHub?  If so, how will the changes in the web address be applied to my computer?  If not, how to do it?  I hope someone can give me detailed steps. Thank you very much.

**Comment by namdre** [comment]
You need to download the code from github, modify it as described at https://sumo.dlr.de/docs/Developer/How_To/Car-Following_Model.html and build sumo as described here: https://sumo.dlr.de/docs/Developer/index.html#build_instructions

Due to the basic nature of your question I strongly suggest that you find a local person proficient in programming to guide you in your efforts.
