### ISSUE TITLE
A question of showing Background Images in GUI

### ISSUE THREAD

**Issue by meco2020** [eclipse/sumo#8682]
Hi, I'm trying to load one image in GUI, but I find the size of the image didn't match the net, the net is the motorway between"杭州市" and "宁波市"，I attempted to change  center x, center y and width one by one, but the result is not good，do you have any methods to math the net and the image
![image](https://user-images.githubusercontent.com/65943065/119680214-8d88c780-be73-11eb-934a-125b7ae47ebc.png)

[test.zip](https://github.com/eclipse/sumo/files/6547514/test.zip)

**Comment by namdre** [comment]
The sumo network uses the UTM projection to map spherical lon,lat-coordinates into the x,y plane.
Unless your Satellite image uses the same projection, you cannot get a match (though the error may be small if the map is small as well). The recommended format for satellite background images is geoTiff since sumo-gui will automatically place them at the correct x,y coordinates based on their embedded location information (but make sure that they have the correct projection).
