### ISSUE TITLE
netconvert - wrong association between OpenDrive signal-ID to 'tl' 'linkIndex' when generating .net.xml from .xodr

### ISSUE THREAD

**Issue by avibab** [eclipse/sumo#8695]
netconvert Version 1.8.0
netconvert command:
`$SUMO_HOME/bin/netconvert --opendrive-files TrafficSignals_Simple.xodr -o TrafficSignals_Simple.net.xml --type-files ftx_netconvert.typ.xml --output.original-names true  --opendrive.import-all-lanes true  --offset.x 0  --offset.y 0  --precision 8`
Input and output files attached
[netconvert_bug.zip](https://github.com/eclipse/sumo/files/6552974/netconvert_bug.zip)

Expected in TrafficSignals_Simple.net.xml
```
<connection from="3.0.00" to="-1.0.00" fromLane="3" toLane="3" via=":4_2_0" tl="4" linkIndex="2" dir="r" state="o">
    <param key="origId" value="14_1"/>
    <param key="signalID" value="33"/>
</connection>
```

Found instead
```
<connection from="3.0.00" to="-1.0.00" fromLane="3" toLane="3" via=":4_2_0" tl="4" linkIndex="2" dir="r" state="o">
    <param key="origId" value="14_1"/>
    <param key="signalID" value="32"/>
</connection>
```

**Comment by m-kro** [comment]
This is due to mixing the physical and logical positions of signals in a bad way:

- the signal is placedon the sidewalk corner and **assigned** to the same road item
- the actual controlled links are the opposite right/through movements
- netconvert assigns the signal to the right turn movement along the corner where the signal is placed
