### ISSUE TITLE
vehicle Lane change unnormal

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#8704]
hello,sumo developer ,how to set the parameter of lanechange model (or other) for vehicle can avoid such phenomenon(like the picture
![problem](https://user-images.githubusercontent.com/59630993/119991550-29453f80-bffc-11eb-9289-f4953faa920e.png)
) .....thank you for help!

**Comment by namdre** [comment]
It's difficult to avoid this completely since you can always insert vehicles in such a configuration.
The easiest way to reduced the likelyhood for these situations to inserted vehicles into your simulation with attribute `departLane="best"` 
Sometimes it also helps if the lanes on which vehicles must swap are made longer.
The options --time-to-teleport and --time-to-teleport.highways are meant to resolve these deadlocks.
