### ISSUE TITLE
Cannot upgrade SUMO from homebrew on Mac OS Catalina due to the fox error

### ISSUE THREAD

**Issue by Tan-Guo** [eclipse/sumo#8753]
The system environment is Mac OS Catalina 10.15.7. I have installed SUMO 1.7.0 successfully through homebrew. But when I input “brew upgrade sumo” in the terminal, it returns:

```
==> Installing sumo from dlr-ts/sumo
Error: fox: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fox.rb:15: syntax error, unexpected <<
<<<<<<< Updated upstream
^~
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fox.rb:21: syntax error, unexpected ===, expecting end
=======
^~~
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fox.rb:27: syntax error, unexpected >>, expecting end
>>>>>>> Stashed changes
^~
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fox.rb:63: syntax error, unexpected end, expecting end-of-input

```

Is there something wrong with the fox/homebrew or the system itself? 

Looking forward to your reply! thanks~

**Comment by schwamborn** [comment]
It looks like you made local changes to the fox formula (maybe due to #6242) which lead to a conflict during merge.
You need to resolve this conflict in `fox.rb` first before moving on.
If you are unsure on what the file should look like, take a look here:
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/fox.rb

**Comment by Tan-Guo** [comment]
Thanks a lot! The problem was solved after I upgraded homebrew and fox:
```
brew update
brew upgrade fox
brew upgrade sumo
```
