### ISSUE TITLE
Unexpected Connectivity in Netconvert from PlainXML

### ISSUE THREAD

**Issue by kschrab** [eclipse/sumo#8796]
Given the following network ([netconvert-connectivity-error.zip](https://github.com/eclipse/sumo/files/6727123/netconvert-connectivity-error.zip)) and a connections file with the content:

```xml
<connections>
    <connection from="gneE0" to="gneE2"/>
    <connection from="gneE0" to="gneE7"/>

    <connection from="gneE3" to="gneE7"/>

    <connection from="gneE4" to="gneE5"/>

    <connection from="gneE7" to="gneE6"/>
    <connection from="gneE7" to="gneE5"/>
</connections>
```
Call of `netconvert -n test.nod.xml -e test.edg.xml -x test.con.xml` results in the following net.xml, with wrong connectivity compared to the input file:

![image](https://user-images.githubusercontent.com/2386865/123656089-e4e1d500-d82f-11eb-95bb-57d5df9586a2.png)

* `gneE7 -> gneE5` is missing (!)
* `gneE6 -> gneE4`  was not declared in connections-file
* `gneE2 -> gneE3`  was not declared in connections-file

**Comment by kschrab** [comment]
With netconvert of SUMO 1.0.1 the connection ? `gneE7 -> gneE5` is correctly added:

![image](https://user-images.githubusercontent.com/2386865/123656614-5faaf000-d830-11eb-863d-c3f98873c7bd.png)

**Comment by namdre** [comment]
- the network you attached was built without the .con.xml file (as indicated by the options in the header comment)
- the turnaround connections are built because 1) no connections are specified for gneE6 and gneE2 and 2) building of turnarounds is enabled by default. Since connection guessing (including turnarounds) is always active for edges which do not occur in the .con.xml, you have to add 
```
<connection from="gneE2"/>
<connection from="gneE6"/>
```
In this particular case you could also set the turnaround options: https://sumo.dlr.de/docs/netconvert.html#junctions

- the missing connection from gneE7 to gneE5 is a bug (as a workaround you can specify all connections from gneE7 using attributes fromLane and toLane

**Comment by namdre** [comment]
Bug: connections with only 'from' and 'to' is ignored if it happens to be a turn-around.

**Comment by kschrab** [comment]
Thank you very much Jakob! :)
