### ISSUE TITLE
Sumo-Option WalkingArea intermediate points

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#8797]
When loading a SUMO configuration/simulation WalkingAreas get a predefined number of intermediate points.

It would be great to have an option similar to netconverts `--junctions.internal-link-detail` to smooth out WalkingLanes within the intersection. With the current implementation, the angle difference between the start/ending of WalkingLanes and Edges can be extremly high.

**Comment by namdre** [comment]
The responsible code is in https://github.com/eclipse/sumo/blob/35c5ed5661c1f5fe417e0a997efaee03d23d652a/src/microsim/transportables/MSPModel_Striping.cpp#L320

**Comment by Domsall** [comment]
After testing different implementations, I recognized that adding a few lines of Code like the following should solve the problem:

```
const OptionsCont& oc = OptionsCont::getOptions();
const int numPoints = oc.getInt("junctions.internal-link-detail");
shape = shape.bezier(numPoints);
```

Does this solve the problem?! Do you have any suggestions for the naming?!

**Comment by namdre** [comment]
since the shapes are specific to the striping model, I would name the option **--pedestrian.striping.walkingarea-detail**

The current implementation has shapes with either 4 or 2 points. The bezier function should only be applied to the 4-point shapes but should then lead to reasonably smooth shapes in most cases.
The shapes will become longer though and I'm not sure whether that will increase realism.
But since it's optional, I see no problem with this.
