### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by gmuharre** [eclipse/sumo#8836]
Hello!

I am a new user to SUMO and I am running into this error 

Library not loaded: /usr/local/opt/fox/lib/libFOX-1.6.0.dylib
  Referenced from: /usr/local/bin/sumo
  Reason: image not found

I have been trying to find solutions on the web but could not find anything until now.

I would appreciate some help!

**Comment by palvarezlopez** [comment]
Hi @gmuharre,

did you installed FOX using package manager?

**Comment by schwamborn** [comment]
@gmuharre It looks like you are running macOS. I suggest you try [homebrew for installing SUMO](https://sumo.dlr.de/docs/Installing/index.html#macos).

**Comment by schwamborn** [comment]
Closing due to missing feedback.

**Comment by angelobanse** [comment]
@SuperSweetNicky can you tell me your macOS version, and the SUMO version you (attempted to) install(ed)? I assume you installed SUMO using Homebrew. Did you get any errors during the installation?

**Comment by SuperSweetNicky** [comment]
My macOS version is macOS Catalina 10.15.7, I am not sure which version of SUMO because I cannot use "sumo --version" command. In fact, I follow that tutorial for installing SUMO for macOS (https://flow.readthedocs.io/en/latest/flow_setup.html#installing-flow-and-sumo). After execute "scripts/setup_sumo_osx.sh", and test with "sumo --version /sumo-gui", it has the above problem.
    However, I had attempted to follow the tutorial (https://sumo.dlr.de/docs/Installing/), but it usually fails when utilizing "brew install" (it is so slow and often fails).
  Thank you so much for your help!

**Comment by SuperSweetNicky** [comment]
> @SuperSweetNicky can you tell me your macOS version, and the SUMO version you (attempted to) install(ed)? I assume you installed SUMO using Homebrew. Did you get any errors during the installation?
  My macOS version is macOS Catalina 10.15.7, I am not sure which version of SUMO because I cannot use "sumo --version" command. In fact, I follow that tutorial for installing SUMO for macOS (https://flow.readthedocs.io/en/latest/flow_setup.html#installing-flow-and-sumo). After execute "scripts/setup_sumo_osx.sh", and test with "sumo --version /sumo-gui", it has the above problem.
    However, I had attempted to follow the tutorial (https://sumo.dlr.de/docs/Installing/), but it usually fails when utilizing "brew install" (it is so slow and often fails).
  Thank you so much for your help!

**Comment by SuperSweetNicky** [comment]
> > @SuperSweetNicky can you tell me your macOS version, and the SUMO version you (attempted to) install(ed)? I assume you installed SUMO using Homebrew. Did you get any errors during the installation?
> > My macOS version is macOS Catalina 10.15.7, I am not sure which version of SUMO because I cannot use "sumo --version" command. In fact, I follow that tutorial for installing SUMO for macOS (https://flow.readthedocs.io/en/latest/flow_setup.html#installing-flow-and-sumo). After execute "scripts/setup_sumo_osx.sh", and test with "sumo --version /sumo-gui", it has the above problem.
> > However, I had attempted to follow the tutorial (https://sumo.dlr.de/docs/Installing/), but it usually fails when utilizing "brew install" (it is so slow and often fails).
> > Thank you so much for your help!
[
I think the version is that:(https://github.com/eclipse/sumo)

**Comment by SuperSweetNicky** [comment]
![![image](https://user-images.githubusercontent.com/127573548/228154213-36e96139-1c36-4e86-a6ae-a6090a28d5
![question](https://user-images.githubusercontent.com/127573548/228154390-4844c5b9-6dc5-4bff-a567-f82db338e0b9.jpeg)
c1.png)

**Comment by SuperSweetNicky** [comment]
> ![![image](https://user-images.githubusercontent.com/127573548/228154213-36e96139-1c36-4e86-a6ae-a6090a28d5 ![question](https://user-images.githubusercontent.com/127573548/228154390-4844c5b9-6dc5-4bff-a567-f82db338e0b9.jpeg) c1.png)

- I try again to install sumo following that:
-(https://sumo.dlr.de/docs/Installing/MacOS_Build.html#prerequisites).this is the question I met with.
Thank you so much for your attention!
