### ISSUE TITLE
When doing 3D simulation

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#8857]
Hello~

I get the following error when doing 3D simulation.

How can I fix it?

![image](https://user-images.githubusercontent.com/62294108/127091197-94c0d813-af12-4de6-ad35-56d31ca42ff5.png)

**Comment by behrisch** [comment]
There seems to be a problem with the path separator "\". Which windows version do you use and do you have some unusual encoding? You just started the bs3Dosm.sumocfg or did you modify it? What is the value of SUMO_HOME?

**Comment by parksanha** [comment]
1. window ver 10 x64
2. No files have been arbitrarily modified.
3. SUMO_HOME : C:\Program Files (x86)\Eclipse\Sumo
(my sumo path)

**Comment by behrisch** [comment]
Can you load other sumocfg-files?

**Comment by parksanha** [comment]
Other cfg files that I've created work just fine.

**Comment by namdre** [comment]
Try the same input files on another computer.

**Comment by parksanha** [comment]
@namdre 
Ok. I'll try and tell you again.

**Comment by m-kro** [comment]
I had the same error messages when trying out 3D sample networks with the precompiled SUMO 1.11.0 "extra" version. Either path separator "/" or "\" didn't change anything. 
However I suspect the error is due to **missing dll files in the precompiled version**: When compiling SUMO myself, I get a plugins directory inside "bin" directory with specific OpenSceneGraph (OSG) dlls. According to [OSG docs](http://www.openscenegraph.org/index.php/documentation/user-guides/61-osgplugins), the plugins are loaded depending on the input file type (e.g. .3ds).

**Comment by behrisch** [comment]
osg dlls are now packaged again
