### ISSUE TITLE
Counter error for TrafficLights.GetControlledLinks

### ISSUE THREAD

**Issue by MaAnKa89** [eclipse/sumo#8891]
The counter value returned by the response to TrafficLights.GetControlledLinks() falls one point short.

File:    <sumo-root>\src\traci-server\TraCIServerAPI_TrafficLight.cpp
Method:   ...processGet(...)
Case:    libsumo::TL_CONTROLLED_LINKS
Here, the counter should be increased  right after writing the link size.

Ths bug got found by trying to implement missing functions in TraCI.NET.

Before fixing this, keep in mind that the python implementation for traci seems to already handle this bug by some kind of exception handling.

Best regards,
André

**Comment by namdre** [comment]
Thanks for reporting this. The `cnt` value which holds the response length is not needed to interpret this particular response and all working clients simply read and ignore it:

- https://github.com/eclipse/sumo/blob/5f20f6e761e1440dc4d9d47bca246cfa1c161f6b/src/libtraci/TrafficLight.cpp#L117
- https://github.com/eclipse/sumo/blob/5f20f6e761e1440dc4d9d47bca246cfa1c161f6b/src/utils/traci/TraCIAPI.cpp#L1691-L1692
- https://github.com/eclipse/sumo/blob/5f20f6e761e1440dc4d9d47bca246cfa1c161f6b/tools/traci/_trafficlight.py#L114

You should be able to implement the function in TraCI.NET in the same fashion.

@behrisch I suggest to correct the count since it probably won't break any third party clients.

**Comment by behrisch** [comment]
see also #7966
