### ISSUE TITLE
Strange connectivity when a combined bike/car street splits up

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8899]
see failing test

**Comment by namdre** [comment]
The problem persists even when all bike lane and sidewalks are removed. The issue stems from the 
Bresenham algorithm for incoming lane assignment.  The algorithm tries to separate the lanes targeted by the eastern arm from those targetd by he southern arm. This might be useful for some uncontrolled intersections or for right-on-red layouts since it removes a potential conflict when entering the northern outbound arm.

**Comment by namdre** [comment]
The problem is also independent of the number of lanes from the eastern arm (EC).  

When building a special case for junction type="traffic_light", what should be the guiding principle?
a) for straight connections, target all lanes on the outgoing edge
b) for straight connections, ensure that the rightmost lane is targeted
c) for all connections (regardless of direction) target all lanes on the outgoing edge
d) ???

Either one of these would cause wide ranging changes to most networks.

**Comment by behrisch** [comment]
We could also recheck whether it is an OSM import bug, The real world network has two lanes coming from the south.

**Comment by namdre** [comment]
The latest [OSM data](https://www.openstreetmap.org/way/997936740) also shows 2 lanes in the forward direction. That doesn't really solve the qestion from https://github.com/eclipse/sumo/issues/8899#issuecomment-892386813 of what the general rule should be.

**Comment by namdre** [comment]
I'm going for a) with some extra rules for priority-junctions to add reasonable connections while maintaining conflict-free arrangements.
