### ISSUE TITLE
How to make some edges of the network prohibit lane change and some edges allow lane change?

### ISSUE THREAD

**Issue by JadeKing666** [eclipse/sumo#8983]
![image](https://user-images.githubusercontent.com/17810735/130347822-ca1b32a1-adbb-4fda-a296-78fd77e3a0b3.png)
QUESTION 1：We've built a two-lane ring network, but it's not clear how to set the properties to allow lane changes on some edges and prohibit them on others. 
![image](https://user-images.githubusercontent.com/17810735/130347995-5ee10e34-ec93-4946-b4de-e24601908592.png)
QUESTION 2：After passing the zipper node all cars follow the route of the outer ring, how do we keep the cars that were previously on the inner ring moving along the inner ring?
Looking forward to your reply, we have been stuck in this place for a while.  T_T(cry)
Thank you in advance.

**Comment by namdre** [comment]
Q1: use attributes changeLeft, changeRight: https://sumo.dlr.de/docs/Networks/PlainXML.html#lane-specific_definitions

Q2: 
- When going counter-clockwise, cars will prefer the outer ring due to keepRight behavior 
  - can be disabled with vType attribute `lcKeepRight="0"`
  - don't forget to set **--lanechange.overtake-right** if you want overtaking on both sides
- There is no memory of a preferred lane that could be remembered from before the zipper merge
- Sumo lanes of the same edge have the same length by definition regardless of curvature (It's a technical trick that greatly simplifies lane-changing code). This means there is no natural preference for the inside lane in a circular track
  - you can trick the vehicles to prefer the inside lane by raising the speed limit on those lane
- "natural" distribution of vehicles among lanes (faster vehicles on the left) usually emerges as an interaction of vehicle speed distribution, keepRight-Behavior and overtaking action

**Comment by namdre** [comment]
re: inside lane speed: this doesn't work yet (#8984, #8985)
