### ISSUE TITLE
Problem with lane change command in Traci

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#9147]
Hi,

I made a TWLTL by overlapping two opposite direction lanes. Using Traci, I ordered vehicles to change lane and move to TWLTL when they pass a specific point in the road segment. Some vehicles cannot complete their lane change. For instance, you can consider vehicle "f10_T.0." Please find attached the required files.

Regards,
Reza.

**Comment by namdre** [comment]
The vehicle accepts the traci request but uses the invalid maneuverDist=0 and thus doesn't move laterally.

**Comment by MohamadReza-Haghani** [comment]
Thanks. Is there a way to fix it by changing maneuverDist or other parameters?

**Comment by namdre** [comment]
You could work around it by calling traci.vehicle.changeSublane(vehID, laneWidth)

**Comment by MohamadReza-Haghani** [comment]
When I do not use sub-lane model, all the lane-changing orders of Traci are preformed perfectly. I was wondering what is the difference of lane-changing processes with and without sub-lane model.

**Comment by namdre** [comment]
In the default lane changing model there is no concept of maneuverDistance (each maneuver is defined by the direction alone). The lane-changing model is quite a bit more complicated in sublane mode and thus can also exhibits bugs which the normal model doesn't have.

**Comment by MohamadReza-Haghani** [comment]
Thank you. I was also wondering what is maneuverDistance. Is there a link or a manual that explains more about it.

**Comment by namdre** [comment]
When the sublane model decides on a lateral movement it also decides the desired lateral distance to move (which may take multiple simulation steps to reach). In your case, the sublane model didn't want to move at all and thus decided on distance 0. Then traci overruled this decision and said "move left" but instead of setting an appropriate maneuverDistance (i.e. the minimum distance to enter the next lane) the maneuverDistance was left unchanged.

**Comment by MohamadReza-Haghani** [comment]
I used changeSublane command instead of changeLane, and it worked. Thank you very much for your help.
