### ISSUE TITLE
Try out vcpkg instead of SUMOLibraries

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9291]
It seems people want to use it https://github.com/microsoft/vcpkg/issues/5147 and it has at least the basics (proj, gdal, xerces-c) except for fox toolkit and would save us from maintaining the libraries ourselves.

**Comment by palvarezlopez** [comment]
@behrisch I am against using vcpkg:
- In CMakeList is very easy to distinguish between 32 and 64 bits.
- We have full control about the libraries version. (for example, to avoid problems like currently with FFMPEG)
- SUMOLibraries is a git clone, vcpkg need an extra step.
- Maintain SUMOLibraries only take one or two of hours per version.

**Comment by behrisch** [comment]
Maybe reducing the SUMOLibraries size is enough

**Comment by timmeh87** [comment]
this thread is my top google result for "vcpkg sumo"
@behrisch  Hello I got here when I was searching if sumo was on vckpg. (right now it isnt). It would theoretically be possible to add SUMO to vcpkg as a package (they call them "ports"). You can do this work without the help of the SUMO maintainers, as long sources are public on the internet, one can make a port of it and integrate it into vcpkg. It is possible to make the port private for your own uses ("overlay" feature), or if you feel like it you may submit it to vcpkg and they will accept it if it passes CI. It will then be maintained by the vcpkg community. Then every time you want sumo you can just type "vcpkg install sumo". A large project like sumo might be hard to make into a port but Im doing it right now because I require it for work. Since I dont need it to work on linux or macos I will prob not do a PR to vcpkg, its too much hassle to make it work perfectly but if there is interest I could prob throw it onto a public git or smth

**Comment by behrisch** [comment]
@timmeh87 Please do so and leave a note here (or even better open a new ticket) if you need help.
