### ISSUE TITLE
How to draw basic graph model

### ISSUE THREAD

**Issue by emotion68** [eclipse/sumo#9433]
Define a certain number of cars in the route.xml file, how to draw the density-flow and  density-speed diagrams in the basic graph model, showing a trend that the flow rate first increases and then decreases as the density increases?
I used the ‘flow’ in the e1 detector to represent the detected flow, ‘occupancy’ to represent the density, and the ‘meanSpeed’ in the e2 detector to represent the speed. Why is the trend not in line with the normal theoretical trend?

**Comment by namdre** [comment]
most likely because your setup does not permit increasing the density beyond the critical density.
For a discussion of this, see https://sumo.dlr.de/docs/Tutorials/FundamentalDiagram.html

also related to #9031

Note, that you can also use edgeData to obtain the necessary values: https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html

**Comment by namdre** [comment]
please reopen if you still have problems to reach high densities.
