### ISSUE TITLE
NEMA does not work and the gui got stuck

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#9709]
Hello, I want to know how to set the configuration about NEMA file. According to the document from the documentation, I try to do it but the sumo-gui got stuckfor a while,then it auto exit. The attachment is my simulation files about it. Hope you can help me solve it, thank you very muc
[nema_test.zip](https://github.com/eclipse/sumo/files/7633750/nema_test.zip)
h!

**Comment by namdre** [comment]
The value of `<param key="coordinatePhases" value="X,Y"/>` is currently mandatory even if coordinate-mode is false.

@qichaow it appears that the value of `r1coordinatePhase` and `r2coordinatePhase` are used even if coordinate-mode is false. The documentation seems to imply that the values are not needed in this case. Can you recheck the code / explain?

**Comment by qichaow** [comment]
The parameter coordinatePhases defines another barrier beside the parameter barrierPhases. 

In your additional file, _<param key="barrierPhases" value="2,6;4,8"/>_ should be _<param key="barrierPhases" value="2,6"/>_ and set _<param key="coordinatePhases" value="4,8"/>_ even it's not in coordinated mode.

I notice that it's confusing. @namdre Maybe we should change the name "coordinatedPhases" to "barrier2Phases." Not sure if that's okay given that SUMO 1.11.0 is out.

**Comment by namdre** [comment]
@qichaow the parameter name can stay as it is. We just need to make sure it's behavior is well documented

For every parameter we must consider the following
- is it mandatory or optional?
- if it is mandatory, can we set a reasonable default (i.e. "2,6" for coordinatePhaes)?
- if there is a default, can we detect if the default makes no sense (i.e. phase 2 or 6 are missing)?

Then:
- document for every parameter whether it has a default or whether it must always be set by the user (only mandatory parameter names are written in bold in the parameter table, the others in normal font)
- document the default value if it exists (new column in the parameter table)
- adapt the code so it generates an error (`throw ProcessError`) if a mandatory option is missing or the default cannot be used. The last point is very important since sumo has a strict "no crashing"-policy.

**Comment by namdre** [comment]
thanks for #9715 (the rest of my recommendation remains valid)

**Comment by qichaow** [comment]
@namdre Thanks for the recommendation. I thought the documentation was clear but maybe it was only clear to my inner self. :) I will have at least another person to read the write up before I post it in the future.
The coordinatePhases could vary depending on the set up. Probably good to not give default as it may create more issues (e.g., conflicting phases).
I will add throw ProcessError to the code once I fix my OS. (I cannot boot into linux after installing a software for some reasons.)

**Comment by namdre** [comment]
@qichaow  Do you think we can get a bit more configuration error handling into NEMA before the release next week? (or maybe @mschrader15 could help?)

**Comment by thinker310** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mschrader15** [comment]
Though it would be a substantial change, I think that having a "mode" parameter that is one of the options in [Table 5.1 here](https://ops.fhwa.dot.gov/publications/fhwahop08024/chapter5.htm#5.2) would make sense. 

Each mode would then have a combination of parameters that NEMA Controller should expect. If any are missing we could through an error.

@qichaow what are your thoughts?

**Comment by qichaow** [comment]
@namdre we should and we will. 

@mschrader15 the modes in table 5.1 can be achieved by a combination of coordinated mode and recalls which is a way of practice in places. I will check with some traffic engineers in the field to see their thoughts. (Maybe we can get more feedback from the ITE webinar that I'm hosting in March.)

I can take a lead on this one as I have many constraints for the input in mind already. @mschrader15 feel free to take a look at my fork maybe tomorrow morning and chime in.

**Comment by namdre** [comment]
Missing parameters is certainly an important aspect of validation. Would it be feasible to put something like Table5.1 into the documentation at https://sumo.dlr.de/docs/Simulation/NEMA.html and then check whether the given parameters match any of the permitted configurations? This way would do not need a new 'mode' parameter.

A mode parameter might still be useful for configuring sensible defaults if parameters are missing.

We also had issues where the numerical parameters of the phase were in some sense invalid (01964e4731d18e4697). @qichaow do you think this kind of problem could be detect during initialization?

From my perspective there is a hierarchy of requirements here:

- [ ] never crash. Aborting with an error is fine.  (ideally this is would be fixed until next Monday since we want to release on Tuesday.
- [ ] give sensible warnings on misconfigured input (missing parameters / unsuitable combination of parameters)
- [ ] detect faulty timings and give a warning
- [ ] handle missing values gracefully (i.e. fill defaults based on a 'mode' parameter)

**Comment by qichaow** [comment]
Yes. The parameter values will be validated.

**Comment by mschrader15** [comment]
Sounds good @qichaow @namdre !

**Comment by qichaow** [comment]
My thinking on the mode parameter is that it gives an extra degree of freedoms for make it easier to break. Maybe have mode default to "" so that it's not activated for checking. If it's set to a value, then check the corresponding parameters. Within each mode of operations parameters can be checked by coordinated mode and recalls separately.

**Comment by mschrader15** [comment]
That's true @qichaow . I just know that traffic engineers are used to seeing the mode on the traffic light front panel like below (free mode):

![image](https://user-images.githubusercontent.com/57813331/149965975-e5f1e774-a5a5-4ca7-aa5c-37e175f0bb8b.png)

**Comment by qichaow** [comment]
@mschrader15 I was doing a test for error handling and found that your test case under NEMA/fully_actuated/barrier_1_extension broke the barrier. Do you want to fix that? One action could be changing the maxDur of phase 5 to 20.

**Comment by qichaow** [comment]
@mschrader15 you can check my fork and leave any comments.

**Comment by mschrader15** [comment]
@qichaow  https://github.com/eclipse/sumo/blob/main/tests/sumo/basic/tls/NEMA/fully_actuated/barrier_1_extension/tls_state_switch.sumo breaks the barrier? I don't see this in my test?

**Comment by mschrader15** [comment]
`NEMA/fully_actuated/barrier_1_extension` is a pretty unique test and actually with the incorporation of #9937 , the results do not mean much as there is no cross traffic.  2+6 would be extended regardless in green rest.

Below is what I see in my test compiled from head of sumo/main

![image](https://user-images.githubusercontent.com/57813331/150138542-d2aa9bb4-b52b-4fe9-a77c-6a2f0ad7ea04.png)

**Comment by qichaow** [comment]
The NEMA code won’t let it break but the timing breaks the barrier. It’s
not a good timing when you draw the NEMA diagram. Phase 1 + 2 should add up
to phase 5 + 6.

**Comment by mschrader15** [comment]
@qichaow that timing is taken directly from a controller configuration that is in use in the field. You can change it if you would like though!

**Comment by qichaow** [comment]
Let me only throw a warning so that you don’t have to fix the field timing.

**Comment by mschrader15** [comment]
Sounds good!
