### ISSUE TITLE
suspicous NEMA phase names

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9971]
In the complex test results (i.e. complex/traci/trafficlight/NEMA/offset), the states change but the phase names do not: 

```
state="grrrrrrGGrrr" name="4+4"/>
state="grrrrrrGGrrr" name="4+4"/>
state="grrrrrrGGrrr" name="4+4"/>
state="grrrrrrGGrrr" name="4+4"/>
state="grrrrrrGGrrr" name="4+4"/>
state="grrrrrrGGrrr" name="4+4"/>
state="GGGGGrrrrrrr" name="4+4"/>
state="GGGGGrrrrrrr" name="4+4"/>
state="GGGGGrrrrrrr" name="4+4"/>
state="GGGGGrrrrrrr" name="4+4"/>
```

Since the first traci action comes at step 30, this seems to be an issue with the basic operation (or maybe a faulty configuration?).

@qichaow  @mschrader15  can you take a look?

**Comment by mschrader15** [comment]
I will look into this

**Comment by mschrader15** [comment]
@namdre It looks like that has been an issue since commit `77cdc5e24bd6bc15cee3db98f9e9fa134d7580f1` `tests/complex/traci/trafficlight/NEMA/offset/tls_state.complex` ([here for reference](https://github.com/eclipse/sumo/commit/77cdc5e24bd6bc15cee3db98f9e9fa134d7580f1#diff-f064e92c03c68baa06b555bd7f8ff3f4141df9d636bc6fae8ae9030e988909da))

I think it was an error in initialization that I thought I solved with Lines 607-609 in https://github.com/eclipse/sumo/pull/9970/commits/1cc8ec969f6ae7b84802b434e64d173ec5b81fe9.

**Comment by mschrader15** [comment]
The same error was actually present in all tests https://github.com/eclipse/sumo/blob/01964e4731d18e4697c8476edb05686a2295c2c2/tests/sumo/basic/tls/NEMA/basic/tls_state.sumo

**Comment by mschrader15** [comment]
@namdre I am not seeing the error in tests run on `HEAD`. I believe that https://github.com/eclipse/sumo/commit/1cc8ec969f6ae7b84802b434e64d173ec5b81fe9 resolved this.

**Comment by namdre** [comment]
You are right. Sorry for the bother )-:
I was looking at those tests to see why they produce different results after your commit but failed to see that it solved this very problem.

**Comment by mschrader15** [comment]
No problem! 

For future reference, do you prefer PRs that address multiple issues or should I try and keep one PR per Issue? My mess of PRs yesterday was pretty confusing lol
